### ISSUE TITLE
Templating of service restart commands

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#10]
Feedback from #7:

We need templating of restart commands in order to handle commands with arguments that are based on changed settings.

For example, instead of reading `/etc/hostname`, systemd's hostnamectl accepts the new hostname as an argument.  To do this, we'd want to have a template command like `hostnamectl set-hostname {{ settings.hostname }}`

**Comment by tjkirch** [comment]
I think the right answer here is to use the same solution as #231 for templating.  We have a use case for #231, and not for this yet, so this is not as urgent.

Note: #231 means templating happens once, not every time we fetch the setting, so it only works for "permanent" settings.  If we expect hostname to change, for example, we shouldn't use templating like in the example above.

**Comment by etungsten** [comment]
The usecase for passing changed settings to restart-commands has been addressed by https://github.com/bottlerocket-os/bottlerocket/pull/1480. There are no other clear use-case for templating service restart-commands right now. Let's re-open this if we ever identify another use-case.
