### ISSUE TITLE
logdog: support the ecs variant

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#1039]
`logdog` needs to output different information for `ecs` than what is currently hard-coded.

Small complication:

Currently `logdog` assumes that everything we need can be collected by running a shell command with `std::process::Command`. However, the ECS requires something like `curl localhost:51678/v1/tasks` and we don't ship curl on Bottlerocket. A redesign of logdog's abstractions will be needed.

**Comment by tjkirch** [comment]
If we move inputs to a file rather than being hardcoded, we can structure them a bit more.  Straw-man: still plain text, but prefixed with a "mode", like `sh echo hi` to get the output of a shell command and `http localhost:51678/v1/tasks` to get the body of an HTTP response.
