### ISSUE TITLE
modeled_types: Use FromStr instead of TryFrom<&str>

### ISSUE THREAD

**Issue by iliana** [bottlerocket-os/bottlerocket#1061]
[`FromStr`](https://doc.rust-lang.org/std/str/trait.FromStr.html) and [`TryFrom<&str>`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) are functionally equivalent traits, but the former has existed since Rust 1.0.0 and has much wider support across the ecosystem; `serde_plain` is a key example of this.

**Comment by matheusmonte** [comment]
Can I try to start this change?

**Comment by tjkirch** [comment]
@matheusmonte Sure, thanks!  Let us know if you have any questions or troubles.

**Comment by mchaker** [comment]
Additional testing underway.

**Comment by webern** [comment]
Have we fully vetted that this is the right thing to do?

In favor of TryFrom?
- https://internals.rust-lang.org/t/pre-rfc-deprecate-fromstr-in-favor-of-tryfrom-str/12331

In favor of FromStr?
- https://stackoverflow.com/a/71487402

Ambiguous?
- https://stackoverflow.com/a/67386103

**Comment by stmcginnis** [comment]
@mchaker is this still being worked on? Or can it be closed?

**Comment by mchaker** [comment]
@stmcginnis It turned out that, when I attempted fixing this issue previously, much more involved testing was required for this issue than I thought.

I'm currently working on issue 1703, and can focus on this again after I complete that issue.

**Comment by webern** [comment]
The way we have modeled types set up currently, I'm pretty sure all of these impls are defined and it's an implementation detail as to how we go about it. I'm going to close this because I don't think it's relevant anymore (the code may have been different in Aug 2020). Re-open if I'm wrong. Thanks.
