### ISSUE TITLE
[ECS] App Mesh support

### ISSUE THREAD

**Issue by samuelkarp** [bottlerocket-os/bottlerocket#1078]
This issue is tracking adding support for [AWS App Mesh](https://aws.amazon.com/app-mesh/) to the ECS variant of Bottlerocket.

This will require adding the [AWS VPC CNI plugin](https://github.com/aws/amazon-vpc-cni-plugins).

**Comment by abhijitherekar** [comment]
@samuelkarp Was curious on this issue, I had few questions.

1. Is CNI supported on BottleRocket as of today?
2. If CNI is supported then will CNI chaining be supported. If yes then if I want to add a custom CNI plugin what is the best way to copy my custom CNI binary into the bottleRocket FS?
3. Will there be a API exposed for copying the custom CNI binary for CNI chaining support. 

Thanks, Appreciate your help.

**Comment by ssypi** [comment]
Is there any progress or plans regarding this? I saw that the support for awsvpc networking mode with the CNI plugins was added in #1246 but there was a mention that the appmesh plugin was left out for now.
