### ISSUE TITLE
Interactive `busybox:latest` image segfaults under Docker on Arm instances

### ISSUE THREAD

**Issue by samuelkarp** [bottlerocket-os/bottlerocket#1083]
**Image I'm using:**
`aws-ecs-1` though I expect this to reproduce on `aws-dev` as well

**What I expected to happen:**
A container based on the `busybox:latest` image to run interactively

**What actually happened:**
Running a container like `docker run -it busybox:latest` causes the ash shell prompt to print and the container to immediately exit with code 139 (indicating a segfault).

**How to reproduce the problem:**

1. Launch an `aws-ecs-1` AMI on an Arm instance (I used `m6g.medium`)
2. Connect to the admin container, use `sudo sheltie` to get a shell on the host
3. Run `docker run -it busybox:latest`

**Additional information:**
The `busybox:latest` image on Arm is the same as the `busybox:uclibc` image and consists of a Busybox binary built with [uClibc](https://uclibc.org/).  Other variants of the `busybox` image, including `busybox:musl` and `busybox:glibc` do not exhibit this problem.

Only interactive containers exhibit this problem.  Omitting the `-it` flags (keep STDIN open and attach a tty, respectively) or overriding the container command so the shell does not expect interactive behavior (e.g. `docker run -it busybox:latest sh -c 'echo hello'`) allows the container to behave normally and exit 0 without segfaulting.

When failures occur, there are no errors in the Docker daemon log (including with debug logging enabled) or the containerd log.  There are also no visible errors in `dmesg` output.

Disabling seccomp (via `--security-opt seccomp=unconfined`) does not appear to affect the behavior.  Adding the `super_t` process label (via `--security-opt label:type:super_t`) does not appear to affect the behavior.

Extracting the Busybox/uClibc binary from the container filesystem and injecting it into another, normally-running container (like one based on the `debian:latest` image, for example) allows the failure to be reproduced in an environment where tooling can be installed.  I was able to use `strace` on the Busybox binary with this method:

<details>
<summary>strace output for the Busybox/uClibc binary</summary>

```
root@b4ea6ca3b0a4:/# strace /host-cache/sh                                                                                            [6/1151]
execve("/host-cache/sh", ["/host-cache/sh"], 0xffffca9b0380 /* 7 vars */) = 0
brk(NULL)                               = 0x118db000
brk(0x118db6f0)                         = 0x118db6f0
brk(0x118dbe00)                         = 0x118dbe00
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getuid()                                = 0
brk(0x118dce00)                         = 0x118dce00
brk(0x118dd000)                         = 0x118dd000
getpid()                                = 272
rt_sigaction(SIGCHLD, {sa_handler=0x45860c, sa_mask=~[], sa_flags=0}, NULL, 8) = 0
getppid()                               = 269
newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, ".", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x45860c, sa_mask=~[], sa_flags=0}, NULL, 8) = 0
rt_sigaction(SIGQUIT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_IGN, sa_mask=~[], sa_flags=0}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=SIG_IGN, sa_mask=~[], sa_flags=0}, NULL, 8) = 0
brk(0x118de000)                         = 0x118de000
openat(AT_FDCWD, "/dev/tty", O_RDWR)    = 3
fcntl(3, F_DUPFD_CLOEXEC, 10)           = 10
close(3)                                = 0
ioctl(10, TIOCGPGRP, [269])             = 0
getpgid(0)                              = 269
rt_sigaction(SIGTSTP, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=~[], sa_flags=0}, NULL, 8) = 0
rt_sigaction(SIGTTOU, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTOU, {sa_handler=SIG_IGN, sa_mask=~[], sa_flags=0}, NULL, 8) = 0
rt_sigaction(SIGTTIN, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
setpgid(0, 272)                         = 0
ioctl(10, TIOCSPGRP, [272])             = 0
brk(0x118df000)                         = 0x118df000
rt_sigaction(SIGHUP, {sa_handler=SIG_DFL, sa_mask=[HUP], sa_flags=SA_RESTART}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
openat(AT_FDCWD, "/root/.ash_history", O_RDONLY) = -1 ENOENT (No such file or directory)
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
geteuid()                               = 0
openat(AT_FDCWD, "/etc/passwd", O_RDONLY) = 3
ioctl(3, TCGETS, 0xfffff07f9608)        = -1 ENOTTY (Inappropriate ioctl for device)
brk(0x118e0000)                         = 0x118e0000
read(3, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 926
close(3)                                = 0
ioctl(0, TIOCGWINSZ, {ws_row=52, ws_col=142, ws_xpixel=0, ws_ypixel=0}) = 0
getcwd("/", 192)                        = 2
geteuid()                               = 0
rt_sigaction(SIGWINCH, {sa_handler=0x4beb10, sa_mask=[], sa_flags=SA_RESTART}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
write(1, "/ # ", 4/ # )                     = 4
getrlimit(RLIMIT_NOFILE, {rlim_cur=1073741816, rlim_max=1073741816}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffef7f9550} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault
```
</details>

**Comment by samuelkarp** [comment]
It looks like the binary is stripped, so a core dump doesn't provide a useful backtrace.  Next steps might be rebuilding the image from https://github.com/docker-library/busybox/blob/master/uclibc/Dockerfile.builder#L246-L248 (and making sure the error reproduces!) and getting a non-stripped binary (either by changing the target to `busybox_unstripped` or setting `SKIP_STRIP=y`) to examine.

**Comment by stmcginnis** [comment]
We have not seen this issue in the 2+ years since, so it looks like this may have been addressed indirectly through other updates. Going to close for now, but if anyone else runs across this, please feel free to file a new issue and we will track it down.
