### ISSUE TITLE
Read/Write access to NVMe volumes

### ISSUE THREAD

**Issue by chonton** [bottlerocket-os/bottlerocket#1088]
**What I'd like:**
Many AWS instance types offer "[Instance store volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html#instance-store-volumes)".  When running stateful services inside kubernetes, local storage would increase performance (and decrease cost). Unfortunately, most kubernetes cluster management terminate node instances for upgrades, causing the local storage to be lost.   The bottlerocket upgrade scheme is appealing because it provides half of the solution.

How do I make the local volumes available to pods?  The boot volume is read-only, any pods only have access to boot volume.

**Any alternatives you've considered:**
- [storage-local-static-provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/getting-started.md#option-5-eks-experimental)
- [eks ssd provisioner](https://github.com/brunsgaard/eks-nvme-ssd-provisioner) - fails with ```failed to mkdir "/pv-disks": mkdir /pv-disks: read-only file system```

**Comment by bcressey** [comment]
It's not a complete answer, but modifying the EKS SSD provisioner to use `/var/lib/pv-disks` instead of `/pv-disks` would work around the read-only filesystem error.

**Comment by bcressey** [comment]
We landed the OS side of this feature in #1173; NVMe volumes will show up under `/dev/disk/ephemeral` and can be used as persistent volumes.

I've used Helm to install the local volume provisioner using these steps:
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/master/helm#install-with-helm-install-directly
```
$ helm install \
  -f ./bottlerocket.yaml local-volume-provisioner \
  -n kube-system ./helm/provisioner
```

Here's my `bottlerocket.yaml`:
```
 common:
  useNodeNameOnly: true
classes:
- name: local-storage
  hostDir: "/dev/disk/ephemeral"
  mountDir: "/dev/disk/ephemeral"
  storageClass: true
```

Please try it out and let us know if you run into problems.

**Comment by ei-grad** [comment]
Is it possible to use ephemeral disks for both - local-volume-provisioner and [{/var/lib/containerd,/var/lib/kubelet,/var/log/pods}](https://bottlerocket.dev/en/os/1.22.x/concepts/bootstrap-commands/#configure-ephemeral-disks) directories?
```
0s                      Warning   FailedMount            Pod/lpv-test                     MountVolume.MountDevice failed for volume "local-pv-b7da8313" : local: failed to mount device /dev/disk/ephemeral/nvme-Amazon_EC2_NVMe_Instance_Storage_AWS22D48D92FFF9C0309_1 at /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/local-pv-b7da8313 (fstype: ext4), error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/local-pv-b7da8313 --scope -- mount -t ext4 -o defaults /dev/disk/ephemeral/nvme-Amazon_EC2_NVMe_Instance_Storage_AWS22D48D92FFF9C0309_1 /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/local-pv-b7da8313
Output: Running scope as unit: run-r7ebe80bfc44740e69f69eea6fdd1cb48.scope
mount: /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/local-pv-b7da8313: /dev/nvme2n1 already mounted on /mnt/.ephemeral.
       dmesg(1) may have more information after failed mount system call.
```

**Comment by ytsssun** [comment]
Hi @ei-grad , it is actually possible to use ephemeral disks for both. You just need some extra little configuration here.

The error you were seeing is because you specified the device path of the NVMe volume to local-volume-provisioner. With the bootstrap-command you used to prepare those ephemeral storage paths, it would create the mount to the NVMe device already using the mounting point `/mnt/.ephemeral` as suggested by your error message.

To workaround this, you need to create a new directory under the mounting point `/mnt/.ephemeral` (e.g. `/mnt/.ephemeral/local-storage`) and point `local-volume-provisioner` to it. You would need to use the bootstrap container to create such directory.

Sample userdata:
```
[settings.bootstrap-commands.k8s-ephemeral-storage]
commands = [["apiclient", "ephemeral-storage", "init"], ["apiclient", "ephemeral-storage", "bind", "--dirs", "/var/lib/containerd", "/var/lib/kubelet", "/var/log/pods"]]
essential = true
mode = "always"

[settings.bootstrap-containers.create-volume-local]
mode = "once"
user-data = "IyEvdXNyL2Jpbi9lbnYgc2gKc2V0IC1ldW8gcGlwZWZhaWwKbWtkaXIgLXAgLy5ib3R0bGVyb2NrZXQvcm9vdGZzL21udC8uZXBoZW1lcmFsL2xvY2FsLXZvbHVtZQo="
```

The `user-data` field under the `bootstrap-container.create-volume-local` is basically the base64 encoded string for below script:
```bash
#!/usr/bin/env sh
set -euo pipefail
mkdir -p /.bottlerocket/rootfs/mnt/.ephemeral/local-volume
```

And the `bottlerocket.yaml` used for the helm override is:
```
common:
  useNodeNameOnly: true
classes:
- name: local-storage
  hostDir: "/mnt/.ephemeral/local-volume" # <--- Updated with the new directory
  mountDir: "/mnt/.ephemeral/local-volume"
  storageClass: true
```

The `local-storage-provisioner` runs fine with this 
```
I0506 23:32:56.708326       1 main.go:69] Loaded configuration: {StorageClassConfig:map[local-storage:{HostDir:/mnt/.ephemeral/local-volume MountDir:/mnt/.ephemeral/local-volume BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType: NamePattern:*}] NodeLabelsForPV:[] UseAlphaAPI:false UseJobForCleaning:false MinResyncPeriod:{Duration:5m0s} UseNodeNameOnly:false LabelsForPV:map[] SetPVOwnerRef:false}
I0506 23:32:56.708401       1 main.go:70] Ready to run...
I0506 23:32:56.708573       1 common.go:444] Creating client using in-cluster config
I0506 23:32:56.721603       1 main.go:95] Starting config watcher
I0506 23:32:56.721631       1 main.go:98] Starting controller
I0506 23:32:56.721706       1 main.go:102] Starting metrics server at :8080
I0506 23:32:56.721802       1 controller.go:91] Initializing volume cache
I0506 23:32:56.823271       1 controller.go:163] Controller started
```

Let me know if that works for you.
