### ISSUE TITLE
pubsys: template AMI names

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1093]
Per #1091, it would be nice if users could specify in `Infra.toml` a template of desired AMI names.

Currently there's a template baked into `Makefile.toml` called `PUBLISH_AMI_NAME_DEFAULT` that users can override using `cargo make ami -e PUBLISH_AMI_NAME=foo` (with #1091), but if you have a consistent naming pattern, keeping a template in `Infra.toml` is simpler.

**Comment by stmcginnis** [comment]
We may need something like this for out of tree builds, but that effort will address that if/when needed. Since we don't need a separate issue specifically for that part of it, going to close this as not something we've found we've strongly needed otherwise.
