### ISSUE TITLE
On-prem Deployment

### ISSUE THREAD

**Issue by Zeal0us** [bottlerocket-os/bottlerocket#1097]
**What I'd like:**
Deployment for non AWS environments.  I can't say I know enough about bottle rocket to point out flaws, but the following came to mind:

- DNS SRV record relying on the DNS suffix from DHCP.  I believe this is a fairly common strategy - point it at a server expected to hold the configuration in some standard way.
- DHCP option with a path to a configuration file to be fetched via HTTPS.
- PXE install and configuration similar to Kickstart with CentOS.

Would any of these make more (or any) sense?  I imagine they would involve a variant and some changes to how the configuration is gathered, I'm not sure beyond that what would be needed.

**Any alternatives you've considered:**

(See Above)

**Comment by zmrow** [comment]
Thanks for the issue! 

On-prem is something that has been on our minds since we started the project and we’d love to get Bottlerocket running on-prem. We don’t have a full list of all the work needed to get this done, but we have some good starting thoughts in these few issues:
https://github.com/bottlerocket-os/bottlerocket/issues/841
https://github.com/bottlerocket-os/bottlerocket/issues/968

**Comment by bcressey** [comment]
I like the DNS and DHCP options you mention. One idea I've been mulling over is something like an IMDS proxy that would listen on `169.254.169.254` and forward requests to some other endpoint. That would minimize the changes to `early-boot-config` and other components like `pluto` that expect to query that address.

The logic for discovering which address to forward to could live in the proxy, and it could even support a local option like reading from a virtual CD-ROM device.

**Comment by stmcginnis** [comment]
Sorry, I know this is a kind of old issue, but wanted to check on things. We now have bare metal and VMware support (https://github.com/bottlerocket-os/bottlerocket/blob/develop/PROVISIONING-METAL.md).

There are some cool ideas listed here, but wondering if that meets your needs? Any other use cases that are not covered by the current support?

**Comment by udf2457** [comment]
@stmcginnis I've just been lurk-watching this ticket, so I obviously cannot speak for the OP.  However from my perspective it might be nice if you went beyond support VMware, e.g. to Proxmox.

**Comment by stmcginnis** [comment]
Thanks @udf2457, that's good to know!

Since it would be easy to lose in a general issue like this, would you mind filing a new issue specifically asking for proxmox support? That could help gauge any interest from others too, so we can try to get input on prioritization.

Thanks!

**Comment by stmcginnis** [comment]
Closing since we now have metal and VMware, and an issue to track Proxmox. If there are any other specific platforms, please open a new issue targeted for the desired support.
