### ISSUE TITLE
[ECS] SpotInstanceDraining Agent Configuration

### ISSUE THREAD

**Issue by mkulke** [bottlerocket-os/bottlerocket#1099]
**What I'd like:**

I need to be able to set this parameter to `true` via user data, to evict workload safely from to-be-terminated spot instances in my cluster

**Any alternatives you've considered:**

This agent functionality could be implemented in bottlerocket (see https://github.com/reach-now/spot-termination-handler), but I would not see a good reason why this would be preferable.

**Comment by cari73** [comment]
What is this
