### ISSUE TITLE
Zero out buildid to create reproducible builds of kubernetes targets

### ISSUE THREAD

**Issue by bnrjee** [bottlerocket-os/bottlerocket#1102]
**What I'd like:**
In kubernetes upstream,  '-buildid=' was [added ](https://github.com/bnrjee/kubernetes/blob/1274ed81d5f08dd491ca6fde252bac14b4969544/hack/lib/golang.sh#L796)as a GOLDFLAG for the purpose of creating reproducible builds. We should export that change to bottlerocket. 
In bottlerocket, we should remove the patch 0002-do-not-omit-debug-info.patch and export GOLDFLAGS as "-buildid=" in the spec files of the different kubernetes versions. This change will require renumbering the bottlerocket patches that were created for kubernetes.
Environment:
Platform: linux/amd64

**Comment by chadbrewbaker** [comment]
Is there a good reference for locking down gcc/llvm to get reproducible builds in general? Ideally it would be nice to have everything thunkable to a hash when building the distro.

**Comment by zmrow** [comment]
^Thanks for the PR!

**Comment by zmrow** [comment]
Closing as PR was merged! Thanks!
