### ISSUE TITLE
Add recommended HDD space when building the project

### ISSUE THREAD

**Issue by sxiii** [bottlerocket-os/bottlerocket#1104]
**What I'd like:** The documentation isn't telling anything about the build size. First, I cleared up 10 GBs. It failed. Then I cleared 30 GB. It failed again. I think the BUILDING documentation markdown file should include a section on how much space will the build take so people are ready to free like 40 or 50 GBs and not follow my errors.

**Comment by cari73** [comment]
[![Uploading 92251739...]]()

**Comment by zmrow** [comment]
Thanks for the recommendation! Another user commented about the same issue and there's currently a PR (#1107) to address it!
