### ISSUE TITLE
some dependencies are not enumerated in BUILDING.md 

### ISSUE THREAD

**Issue by troyaws** [bottlerocket-os/bottlerocket#1106]
Requirements for available disk space for the build is not stated.  

Dependencies from rust's build process are not enumerated.  Because rust messages are unclear, this is a frustrating user experience.

**Comment by zmrow** [comment]
Thanks for the PR!

**Comment by samuelkarp** [comment]
We've merged https://github.com/bottlerocket-os/bottlerocket/pull/1107, so I'm going to close this issue.  Thanks for bringing it to our attention and contributing a fix!
