### ISSUE TITLE
[ECS] Task ENI capability

### ISSUE THREAD

**Issue by ryphon** [bottlerocket-os/bottlerocket#1123]
**What I'd like:**
For Bottlerocket to support enabling the ecs.capability.task-eni attribute.

**Any alternatives you've considered:**
My task requires an ENI for each individual task. This attribute capability is a hard requirement.

**Comment by samuelkarp** [comment]
Hi @ryphon, we're tracking awsvpc support in https://github.com/bottlerocket-os/bottlerocket/issues/1077.  I'm going to close this issue in favor of that one.
