### ISSUE TITLE
sysctl settings 

### ISSUE THREAD

**Issue by chathsuom** [bottlerocket-os/bottlerocket#1129]
Is there a way to set kernel parameters. 
For e.g. to run elasticsearch docker, we need to set `vm.max_map_count`

**Comment by samuelkarp** [comment]
Hi @chathsuom! I'd like to use https://github.com/bottlerocket-os/bottlerocket/issues/1125 to track the general question of how we'd model kernel parameters in Bottlerocket, so I'm going to close this issue.  The work-around suggested by @hendrikhalkow in that issue (run a privileged container that writes the expected value to `/proc/sys/vm/max_map_count`) will likely work for you as well in the mean time.

**Comment by Riyan-plivo** [comment]
But with the existing settings , we can tune the kernel parameters right : 
```
[settings.kernel.sysctl]
"vm.swappiness" = "1"
"net.core.somaxconn" = "<val>"
"vm.max_map_count" = "<val>"
"fs.file-max" = "<val>"

```

**Comment by ytsssun** [comment]
> But with the existing settings , we can tune the kernel parameters right :
> 
> ```
> [settings.kernel.sysctl]
> "vm.swappiness" = "1"
> "net.core.somaxconn" = "<val>"
> "vm.max_map_count" = "<val>"
> "fs.file-max" = "<val>"
> ```
Correct, with this settings you can configure the kernel parameters.
