### ISSUE TITLE
How to build image for bare metal

### ISSUE THREAD

**Issue by zhouji3x** [bottlerocket-os/bottlerocket#1131]
I known from https://aws.amazon.com/cn/bottlerocket/ that bottlerocket support bare metal host:
"Bottlerocket is a Linux-based open-source operating system that is purpose-built by Amazon Web Services for running containers on virtual machines or bare metal hosts. "

How to build image for bare metal?

Thanks

**Comment by zmrow** [comment]
Hi @zhouji3x!

Currently we support bare metal on EC2 and you can [build images via `cargo make`](https://github.com/bottlerocket-os/bottlerocket/blob/develop/BUILDING.md)!

Booting Bottlerocket on bare metal elsewhere will take some kernel work we that we haven't scoped or prioritized yet. Additional considerations for running Bottlerocket outside of EC2 are covered in: #968 , #1097, and #1114.

**Comment by samuelkarp** [comment]
Closing as @zmrow answered the question and related questions are addressed by the issues linked above.
