### ISSUE TITLE
[ECS] Can't connect to instance via Aws Session Manager

### ISSUE THREAD

**Issue by namiops** [bottlerocket-os/bottlerocket#1139]
I'm follow QUICKSTART-ECS with the role setting for lauching EC2 instances, but I can't connect to any Bottlerocket instance with SSM (Session Manager).

But It work, until I attached additional Policy "AmazonEC2ContainerRegistryReadOnly" to the running EC2's role.

**Platform I'm building on:**
AWS ECS

**What I expected to happen:**
Connect to EC2 Instances with Session Manager

**What actually happened:**
Can't connect without the policy AmazonEC2ContainerRegistryReadOnly

**How to reproduce the problem:**
Attach addtional policy AmazonEC2ContainerRegistryReadOnly to EC2's Role

**Comment by tjkirch** [comment]
Thanks for the input!  We do have a note in the [README](https://github.com/bottlerocket-os/bottlerocket/blob/17c1e29ec3fa5cade1ab631e899141267118fecc/README.md#exploration), but it probably also belongs in the QUICKSTART guides.
