### ISSUE TITLE
Kernel Module Support: Publish kernel-devel & /proc/config.gz artifacts for each bottlerocket release

### ISSUE THREAD

**Issue by faarshad** [bottlerocket-os/bottlerocket#1141]
**What I'd like:**
- For building out-of-tree kernel modules (e.g. [falco kernel module](https://github.com/falcosecurity/falco-website/blob/e10197ab6eb57939456c08c7fa121c476e3145ed/content/en/docs/source.md#build-kernel-module-driver)), it would benefit the community to have public access to `kernel-devel-*.rpm` and `/proc/config.gz` for each released bottlerocket-os version(e.g. `bottlerocket-aws-k8s-1.16-x86_64-v1.0.1-2a181156`) 
- Please also consider backporting i.e. publishing `kernel-devel.*.rpm` for already released versions

**Any alternatives you've considered:**
- Using a running host admin container is inconvenient since it requires to standup a runtime os and has manual steps involved.
- Also, bottlerocket-sdk versions are not aligned 1-1 with a particular bottlerocket-os release which results in difficulty correlating the two.

cc: @bcressey @jhaynes

**Comment by bcressey** [comment]
The kernel config is included in the devel archive as `/usr/src/kernels/%{version}/.config`, so we probably don't need a separate `config.gz` artifact.

Retroactively publishing archives for the existing releases is a great idea.

Progress on getting a portable artifact out of the SDK can be tracked in bottlerocket-os/bottlerocket-sdk/issues/7. We might end up publishing a toolchain artifact here along with each release.

**Comment by bcressey** [comment]
I have not tested it, but these toolchains from [toolchains.bootlin.com](https://toolchains.bootlin.com) should work in the interim:
* [x86_64](https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64-core-i7/tarballs/x86-64-core-i7--glibc--stable-2020.08-1.tar.bz2)
* [aarch64](https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--glibc--stable-2020.08-1.tar.bz2)

We're currently on GCC 9.3.0 and binutils 2.33.1, which matches up with their stable release.

**Comment by bcressey** [comment]
#1275 is our current plan to integrate this into the release process.

**Comment by arnaldo2792** [comment]
Hello @faarshad, as @bcressey pointed out, it is now possible to use the [kmod-kit](https://github.com/bottlerocket-os/bottlerocket/blob/develop/BUILDING.md#building-out-of-tree-kernel-modules) to build out-of-tree kernel modules. We have this [Github discussion](https://github.com/bottlerocket-os/bottlerocket/discussions/1725) that explains how to compile and load out-of-tree kernel modules, using orchestrated containers.
