### ISSUE TITLE
Add support for BPFFS mount.

### ISSUE THREAD

**Issue by izaakschroeder** [bottlerocket-os/bottlerocket#1159]
**What I'd like:**

To be able to install Cilium on top of bottlerocket-based EKS clusters. Since the rootfs is immutable, CNI plugins that rely on bootstrapping to mount `bpffs` won't work (i.e. Cilium).

**Any alternatives you've considered:**

There aren't any really… the underlying FS can't be modified so there isn't really any way around this 😢

**Comment by samuelkarp** [comment]
Per https://github.com/bottlerocket-os/bottlerocket/pull/1160#issuecomment-725692670, the bpffs mount is already present at `/sys/fs/bpf` in our 1.0.2 release.  I'm going to go ahead and close this, but please feel free to re-open or open a new issue if you run into further issues.  Thanks for using Bottlerocket!
