### ISSUE TITLE
apiclient should return distinct exit statuses for temporary and permanent failures

### ISSUE THREAD

**Issue by mifisignal** [bottlerocket-os/bottlerocket#1164]
Some API operations such as `GET /updates/status` return temporary failures such as `423 Unable to obtain shared lock for reading update status: Resource temporarily unavailable (os error 11)`. Yet `apiclient` does not distinguish between temporary failures such as these from permanent failures that are unlikely to succeed without some sort of intervention on the user's part. In both cases, the return/error code is 1.

This makes it difficult when writing scripts around `apiclient` to switch behavior based on whether the request is retriable. For example, we need to be able to retry if `GET /updates/status` returns the above error, but treat the error as a hard failure if the request returns any other kind of 4xx response.

**Comment by zmrow** [comment]
Good find! Would you expect a custom error code in the case of a "retry-able" failure?

I'm curious how the scripts are calling `apiclient` - do you mind sharing?

**Comment by mifisignal** [comment]
> Would you expect a custom error code in the case of a "retry-able" failure?

Yes, please. Even 0 for success, 1 for hard failure, and 2 for soft failure would be sufficient.

Here's a brief example:


```sh
# fetch update catalog
apiclient -m POST -u /actions/refresh-updates

# Wait until the catalog has been fetched. 
# NOTE: Here is where we have an ambiguous situation. A temporary failure returns exit code 1 here -- but what if there's
# a fatal error in the background refresh process? How can we know this? 
# Or, what if there's some other problem with the API service?
until apiclient -u /updates/status; do sleep 1; done

# set version to be used - $VERSION can be "latest" or "1.0.2" etc
apiclient -m PATCH -u /settings -d '{"updates": {"version-lock": "$VERSION", "ignore-waves": true}}' && apiclient -m POST -u b/tx/commit_and_apply

# fetch update according to `version-lock` and prepare it
apiclient -m POST -u /actions/prepare-update

# Wait until the update has been prepared. Same issue with ambiguity as above: What if the update preparation fails?
until apiclient -u /updates/status; do sleep 1; done

# activate update (flip partition)
apiclient -m POST -u /actions/activate-update

# Wait until the update has been activated. Same issue with ambiguity as above: What if the activation step fails?
until apiclient -u /updates/status; do sleep 1; done

apiclient -m PATCH -u /settings -d '{"updates": {"ignore-waves": false}}' && apiclient -m POST -u b/tx/commit_and_apply

# reboot
apiclient -m POST -u /actions/reboot
```

**Comment by bcressey** [comment]
We addressed this use case with the high-level update subcommands in #1219 - since we know user intent, we can drive the API ourselves, and paper over the distinction between hard and soft errors.
