### ISSUE TITLE
Provide some way to extract fields from apiclient output

### ISSUE THREAD

**Issue by mifisignal** [bottlerocket-os/bottlerocket#1165]
For scripting purposes, it would be useful to provide some way to extract fields from the JSON responses returned by `apiclient`. This will be particularly useful when running shell scripts via the SSM Agent. (The Bourne shell is the only higher level language that can be used there at this time and it doesn't have built-in JSON parsing capability.)

Some alternatives include:
1. Add some sort of JSONPath/JSONQuery support to `apiclient`, à la `kubectl get -o jsonpath=...` or `aws --query`
2. Provide `jq` or equivalent in the control and admin containers. It'd need to be in the control container because that's where the SSM Agent runs

**Comment by zmrow** [comment]
Thanks for the issue!

Since the control container is [based on Amazon Linux 2](https://github.com/bottlerocket-os/bottlerocket-control-container/blob/c14ebe6ec28010cb9ce44586616e27930cf74a23/Dockerfile#L3), and `jq` should be available in the repos, you should be able to install it.  Others may have different opinions, but I think installing `jq` is preferable to building additional complexity into the `apiclient`, which is a very thin wrapper over http requests.

I'm also curious what kind of scripting you're doing against the `apiclient`.

**Comment by mifisignal** [comment]
I’m trying to build a reasonably intelligent and idempotent Bottlerocket updater process via SSM automations. (It should do nothing, and exit cleanly, if there is nothing to do.) `updog` isn’t accessible from the control container, and `apiclient` invocations used to update the OS are not idempotent. This can lead to ambiguous situations if the only signal we can use is its exit status (see #1164). 

So, I want to be able to parse out the fields returned by `apiclient -u /updates/status` and examine them in more detail to ensure all the corner cases are properly handled.

Separately, the API server doesn’t return prettified/indented JSON, so just being able to run `apiclient` output through `jq .` would be nice.

**Comment by tjkirch** [comment]
> updog isn’t accessible from the control container

We're working on a design for a higher-level update client that interfaces with the API, making it usable from the control container without updog.  It's still early, but it should address concerns like these, and may address what you're aiming for in #1164 as well.

**Comment by bcressey** [comment]
#1219 addresses the underlying use case of making it easier to drive the updates API, and #1238 addresses the related problem of managing settings related to updates.

With that in place it should just be a matter of:
```
apiclient set updates.ignore-waves=true updates.version-lock=latest
apiclient update apply --check --reboot
```

For other scenarios we'd prefer using a dedicated tool to parse the JSON output.
