### ISSUE TITLE
Docker Container Base Image

### ISSUE THREAD

**Issue by macbash** [bottlerocket-os/bottlerocket#1177]
we have amazon base images for docker, it will be good, if you folk releasing BottleRocket images also.

**Comment by zmrow** [comment]
Hi @macbash ! 

Bottlerocket isn't built to be used inside a container, instead it is meant to be the OS where you run containers (an EC2 instance or VM). Bottlerocket releases are currently available as [AWS AMIs](https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART.md#finding-an-ami) that can be launched in EC2. If you have other use cases in mind, let us know!

Related to #940
