### ISSUE TITLE
support ephemeral storage on older instance types

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#1181]
**What I'd like:**
In #1173 we added symlinks for ephemeral storage on the newer, Nitro-based instance types.

Older instance types where the xen-blkfront driver is used for both EBS and ephemeral disks are a problem, since there's no easy way to tell them apart.

We could query IMDS to find the block device mapping and then try to match devices that way. This is complicated because the devices show up before the network is up. We'd have to do the query at a later point during boot, save the mapping somewhere, and trigger a change event on the devices so they get processed again.

**Any alternatives you've considered:**
Using newer instance types.

**Comment by stmcginnis** [comment]
@bcressey is this still something we need/want to do?

**Comment by bcressey** [comment]
I haven't seen interest in expanding this feature over the last couple years, so I'm happy to resolve it.
