### ISSUE TITLE
systemd-journald: journal logs produced is not readable by older versions of systemd-journald

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket#1200]
**Image I'm using:**
bottlerocket-aws-k8s-1.17-x86_64

**What I expected to happen:**
I expected the system journal log produced by systemd in bottlerocket to be readable on other hosts with older systemd versions.

**What actually happened:**
This new change in systemd v246: https://github.com/systemd/systemd/blob/a54bcb901677b297a8073b0cb92992a6fff8c954/NEWS#L964-L972 enables hardening of the hash tables in journal files so system journal log generated by v246 is not readable on any older version of systemd (< v246)

On AL2 (systemd v219)
```
$ sudo journalctl -D ./journal/
Journal file ./journal//ec2ca5d6a8873aad3c2a8331aca0efb9/system.journal uses an unsupported feature, ignoring file.
-- No entries --
$ journalctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

On ubuntu 20.04.1 (systemd v245)
```
$ sudo journalctl -D var/log/journal/
Journal file var/log/journal/ec2ca5d6a8873aad3c2a8331aca0efb9/system.journal uses an unsupported feature, ignoring file.
Use SYSTEMD_LOG_LEVEL=debug journalctl --file=var/log/journal/ec2ca5d6a8873aad3c2a8331aca0efb9/system.journal to see the details.
-- No entries --
$ systemd --version
systemd 245 (245.4-4ubuntu3.3)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

```

**How to reproduce the problem:**
Launch any instance with the latest Bottlerocket image and detach the data volume and attach it to another host.
Try to inspect the system log with `journalctl -D /path/to/bottlerocket-system-journal-on-data-volume`

**Comment by jahkeup** [comment]
The changelog indicates we should be able to address this by setting an environment variable which will restore backwards compatibility:

          If the $SYSTEMD_JOURNAL_KEYED_HASH boolean
          environment variable for systemd-journald.service is set to 0 this
          new hardening functionality may be turned off, so that generated
          journal files remain compatible with older journalctl
          implementations.

So we should be able to set this in-unit either by way of a drop in unit or patched into the service itself.

```ini
# Configure journald to use compatible hash method.
[Service]
Environment=SYSTEMD_JOURNAL_KEYED_HASH=0
```
