### ISSUE TITLE
Request for documentation on default volumes

### ISSUE THREAD

**Issue by aclevername** [bottlerocket-os/bottlerocket#1203]
**Image I'm using:**
`bottlerocket-aws-k8s-1.17-x86_64-v1.0.2-ddeb03c8`
`ami-0666e6f3cd7b00794`

**question:**
- Why does bottlerocket AMI spec state that two volumes need to be attached? How are the two volumes used? I could not find any documentation on this 😄 
```
{
    "Images": [
        {
            ...
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/xvda",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-086fb7e858e18cff4",
                        "VolumeSize": 2,
                        "VolumeType": "gp2",
                        "Encrypted": false
                    }
                },
                {
                    "DeviceName": "/dev/xvdb",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-037dd9b80045d742b",
                        "VolumeSize": 20,
                        "VolumeType": "gp2",
                        "Encrypted": false
                    }
                }
            ],
            ...
        }
    ]
}
```

Thanks,
Jake & @Callisto13

**Comment by samuelkarp** [comment]
Hello!  `/dev/xvda` is used to hold the operating system itself and contains the active & passive partitions, the bootloader, the dm-verity data, and the data store for the Bottlerocket API.  `/dev/xvdb` is used for all of the things you run on top of Bottlerocket: container images, storage for running containers, and persistent storage/volumes.

I'll leave this issue open to track making sure we have this documented.

**Comment by aclevername** [comment]
> Hello! `/dev/xvda` is used to hold the operating system itself and contains the active & passive partitions, the bootloader, the dm-verity data, and the data store for the Bottlerocket API. `/dev/xvdb` is used for all of the things you run on top of Bottlerocket: container images, storage for running containers, and persistent storage/volumes.
> 
> I'll leave this issue open to track making sure we have this documented.

Thanks!

**Comment by remiflament** [comment]
Did it appear that the documentation skip again this description? The change made on https://github.com/bottlerocket-os/bottlerocket/pull/1588 are gone.
