### ISSUE TITLE
The CPU usage is very high(almost %100) when app is running in the bottlerocket node

### ISSUE THREAD

**Issue by jackie-JD** [bottlerocket-os/bottlerocket#1226]
I have two EKS clusters, one is based on bottlerocket and the other is based on Amazon Linux 2.

issues:
1. 
I switch to the bottlerocket cluster, and run my deployment which used to run my docker image(my app is in it).
After deployment is created, I login to the scheduled worker nodes(**actually it is the admin container**)and use top command to see the CPU usage, it is very high and lasts about about 10mins.
![image](https://user-images.githubusercontent.com/74808927/100315211-39e80f00-2ff3-11eb-94f8-50fb88b44670.png)

2 And in order to compare, I switch to the other cluster which based on Amazon Linux 2, use the same deployment yml file to deploy my docker image
After deployment is created, I login to the scheduled node and use top command to check. The CPU usage is less %1.

For the case, how can I debug it ? I am not sure where cause this issue.
I need your help. Thank you.

**Comment by bcressey** [comment]
There's a chance this is related to #1136, so if you're not on v1.0.3 yet, it might be worth upgrading to see if it helps. We've seen related issues with older versions of RPM, for example, where they'd spend an excessive amount of time closing a large number of file descriptors.

If that doesn't help, I'd try `perf top` during the period of high CPU utilization, to see if it's immediately obvious where the cycles are going, and then move on to creating a [flame graph](https://github.com/brendangregg/FlameGraph) for the process in question. Profiling for a minute or so should be enough to identify where in the application the time is spent.

**Comment by jackie-JD** [comment]
Thank you @bcressey. I update the bottlerocket to 1.0.3 and the issue is resolved.
