### ISSUE TITLE
Upstream cri patch for default RLIMIT_NOFILE

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#1240]
Bottlerocket carries [a patch to `cri`](https://github.com/bottlerocket-os/bottlerocket/pull/1180) that sets a default `RLIMIT_NOFILE`, introduced to help remediate [this OOM issue](https://github.com/bottlerocket-os/bottlerocket/issues/1136).  

This configurable limit seems more generally useful, so we should upstream the patch.

**Comment by rverma-dev** [comment]
@zmrow we are also facing issues with rlimit on our elasticsearch clusters, and the current openfiles are shown as (-n) 65536. Is there a way to use the increased limit, the clusters are bootstrapped using eksct.

**Comment by zmrow** [comment]
Thanks for letting us know - we'll take this into consideration when planning and considering if or how we can make this more configurable.

**Comment by zmrow** [comment]
Upstream issue: https://github.com/containerd/containerd/issues/6063

**Comment by zmrow** [comment]
PR: https://github.com/containerd/containerd/pull/6064

**Comment by tanvp112** [comment]
hi @zmrow, I tested with `1.7.2-28782dce`, there's one last setting that required to pass elasticsearch boostrap check which is the [memlock](https://www.elastic.co/guide/en/elasticsearch/reference/current/_memory_lock_check.html). Is it possible to have memlock hard limit set to `unlimited`?

Thanks.

**Comment by stmcginnis** [comment]
@zmrow do you know what happened with this?

**Comment by webern** [comment]
We deleted the patch in #2697 because we now set it via the OCI-defaults

**Comment by stmcginnis** [comment]
I'm wondering about @tanvp112's memlock mention. Maybe that should be its own issue so we can track it there and not muddy things.

Any idea if that is still needed @tanvp112?

**Comment by bcressey** [comment]
Seems like it's still needed and we should expand the `oci-defaults.resource-limits` settings for all the limits in any case.

**Comment by tanvp112** [comment]
@stmcginnis, yes, this setting is very much needed for in-memory (eg. redis, elk... just to name a few) workloads.

**Comment by stmcginnis** [comment]
I am going to close this since the topic of this issue has been addressed and open a new issue to track expanding the `oci-defaults.resource-limits` knobs.

Tracking in #2814
