### ISSUE TITLE
Bottlerocket containerd runtime version has unknown string

### ISSUE THREAD

**Issue by mikestef9** [bottlerocket-os/bottlerocket#1241]
When pulling the containerd runtime from EKS 1.18 variant, an "unknown" string is appended to version that gets returned as shown below

Container runtime
containerd://1.3.7+unknown

**Image I'm using:**
Bottlerocket v1.18 EKS

**What I expected to happen:**
Should return containerd version without "unknown"

**How to reproduce the problem:**
View Bottlerocket node group in EKS console, or use kubelet to pull runtime version directly

**Comment by gregdek** [comment]
Thanks @mikestef9. We'll take a look.
