### ISSUE TITLE
pubsys repo checks are performed on wrong path if updating repo

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1243]
Let's say you have an Infra.toml file with a "default" repo stored under a `bottlerocket-1.0.4-cef8dbd2` directory, because you want to update that existing repo.  If you then build a 1.0.5 image, with the intent to add it into that existing 1.0.4 repo, pubsys still checks whether a 1.0.5 directory exists, and hard-fails if it does, even though the 1.0.5 directory isn't going to be used.  It also updates the `latest` symlink to point to the 1.0.5 directory, even though it wasn't used, and the repo that was just updated was in the 1.0.4 directory.

**Comment by stmcginnis** [comment]
Don't believe this is an issue anymore. If so a new issue will be filed with current data.
