### ISSUE TITLE
Is it too heavy to update total image with one little point update ?

### ISSUE THREAD

**Issue by xuchunmei000** [bottlerocket-os/bottlerocket#1252]
About the update scheme, I wonder is it too heavy to update total image, while I just want to do a little update, such as update a binary or config file.
Since the bottlerocket rootfs is readonly and with dm-verity to check its hash, we could only update rootfs by update the total image of rootfs, there will be many many versions of update images, and this will cause complecated version management of images.
Is there any way to do with little update or any other good suggestion for version mangement of images ?

**Comment by caoruidong** [comment]
It is tenet of atomic update. You can update some config if bottlerocket supports in control container, but no binary files.

**Comment by jhaynes** [comment]
Hi @xuchunmei000 Did @caoruidong answer your question? If not, what extra information can we add to help?

**Comment by xuchunmei000** [comment]
> Hi @xuchunmei000 Did @caoruidong answer your question? If not, what extra information can we add to help?

ok, no other information needed, thanks.
