### ISSUE TITLE
Time to build

### ISSUE THREAD

**Issue by mojoa** [bottlerocket-os/bottlerocket#1253]
**Platform I'm building on:**
Fresh Fedora 33 VM 8g 2 cpu
Host - Windows 10 12 core Xeon 96gb mem dedicated ssd for VM.

**What I expected to happen:**
Did not know how long cargo make command would take to build. 
13668 sec or 3.8 hours seems long. - Don't know.
Maybe mention approximate expected time in build doc?

**What actually happened:**

Compiling kubernetes-1_18 v0.1.0 (/root/aws/bottlerocket/packages/kubernetes-1.18)
Compiling docker-engine v0.1.0 (/root/aws/bottlerocket/packages/docker-engine)
    Finished dev [optimized] target(s) in 199m 13s
[cargo-make] INFO - Running Task: build-variant
   Compiling aws-k8s-1_17 v0.1.0 (/root/aws/bottlerocket/variants/aws-k8s-1.17)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 56s
[cargo-make] INFO - Running Task: link-variant
[cargo-make] INFO - Build Done in 13668 seconds.

**How to reproduce the problem:**
Build fresh fedora 33 VM and follow build instructions:
[BUILDING.md](https://github.com/bottlerocket-os/bottlerocket/blob/develop/BUILDING.md)

**Comment by gregdek** [comment]
Yep, I ran into this as well when I was first building -- I tried on a much smaller host, and it never built at all because of OOM issues. Definitely something to be clarified in the docs. Thanks for bringing it up!
