### ISSUE TITLE
Please make it available in cn-north-1 and cn-northwest-1

### ISSUE THREAD

**Issue by terryares** [bottlerocket-os/bottlerocket#1255]
Hi team,

Do you have a plan about when bottlerocket is supported in China region?

**Comment by jhaynes** [comment]
Thanks for asking about the China region. We're excited to bring Bottlerocket into the other AWS partitions, but I can't commit to a timeline right now.

**Comment by walkley** [comment]
Hey, any updates to make Bottlerocket available in AWS China regions?

**Comment by zmrow** [comment]
This is still on our radar, but we don't have any dates to share at this time!

**Comment by jpculp** [comment]
@arestuzi & @walkley, I'm happy to announce that with the release of [**1.9.0**](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.9.0), AMIs are available in `cn-north-1` and `cn-northwest-1`!

**Comment by kdaula** [comment]
Closing issue now that Bottlerocket AMIs are available in cn-north-1 and cn-northwest-1
