### ISSUE TITLE
update to tough v0.11.0, tokio 1.0, rusoto 0.46, reqwest v0.11.

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#1269]
The rust packages listed in the title are intertwined in various ways.

Multiple major-versions of tokio can not be in use at a given time. rusoto 0.46, hyper 14 and reqwest v0.11 all bump to tokio v1.0.  Meanwhile, we cannot have multiple versions of reqwest in the sources workspace because of the way webpki-root-shim works. So, basically what needs to happen is this https://github.com/awslabs/tough/issues/269 needs to land and get published (I'm calling it v0.11.0 since v0.10.0 is already a huge diff), and then all the Bottlerocket stuff can update.

Edit: remember to remove the https-proxy workarounds in metricdog and updog, see #1332

**Comment by tjkirch** [comment]
inotify is another dependency that updated because of tokio.

**Comment by tjkirch** [comment]
Also httptest.

**Comment by tjkirch** [comment]
Also coldsnap, which needs to do a new release that includes the change it made to use tokio 1.

**Comment by webern** [comment]
> Also coldsnap, which needs to do a new release that includes the change it made to use tokio 1.

Good catch, opened this PR to get it done https://github.com/awslabs/coldsnap/pull/46

**Comment by webern** [comment]
OK, `coldsnap` and `tough` dependencies are published so this should be unblocked.

**Comment by webern** [comment]
`tools` has been updated to use tokio v1. Bottlerocket (i.e. `sources`) has not because we need `actix-web 4.0`.

**Comment by webern** [comment]
Here are a few useful tracking links
https://github.com/actix/actix-web/milestone/6
https://github.com/actix/actix-web/blob/web-v3.3.2/actix-http/Cargo.toml#L47
https://github.com/actix/actix-net/blob/1.0/actix-rt/Cargo.toml#L23
