### ISSUE TITLE
Mount bpffs at /sys/fs/bpf

### ISSUE THREAD

**Issue by fasaxc** [bottlerocket-os/bottlerocket#1283]
**What I'd like:**

Please can you ensure that the bpffs is mounted at its "standard" mount point: `/sys/fs/bpf` (at present, it seems to be mounted at `/.bottlerocket/rootfs/sys/fs/bpf`.

I work on Project Calico, a popular Kubernetes networking/security plugin.  We've been enabling our eBPF mode on EKS and we noticed that the bpffs isn't mounted at the expected location when using bottlerocket.  This is a fairly big problem for us because our per-host agent runs inside a Kubernetes pod and relies on mounting the bpffs into the pod as a volume.

**Any alternatives you've considered:**

If the bpffs isn't mounted then we mount it at the expected location inside our pod. Unfortunately, once the pod is torn down, the bpffs is usually torn down with it, which breaks our dataplane.  The exception is if bidirectional mount propagation is enabled but that feature is disabled in many clusters for security reasons.

We could provide bottlerocket-specific manifests with changes to mount the bottlerocket specific directory into the pod.  This adds friction and confusion for our users at install time.  If they use the wrong manifest then it will partially work but break when they restart our pod, for example.

**Comment by fasaxc** [comment]
On further investigation, looks like we are sharing that mount with the host _somehow_, maybe I just don't understand how bottlerocket is supposed to work here

**Comment by bcressey** [comment]
It looks like you've checked the mount list from the admin container, which has the root filesystem and other mounts bound into it at the `/.bottlerocket/rootfs` mount point.

If you run `sudo sheltie` you'll be in a shell on the host and can observe the mounts from there. You should see bpffs mounted at `/sys/fs/bpf`.

**Comment by fasaxc** [comment]
Yep, that looks like the problem :+1:
