### ISSUE TITLE
ECS - Custom Attributes not updated after version update

### ISSUE THREAD

**Issue by umairishaq** [bottlerocket-os/bottlerocket#1293]
**Image I'm using:**
Tried with a couple of versions; 1.0.2 and 1.0.3 with the following names:
bottlerocket-aws-ecs-1-x86_64-v1.0.2-ddeb03c8
bottlerocket-aws-ecs-1-x86_64-v1.0.3-0c93e9a6

**What I expected to happen:**
After the instance was updated, the ECS custom attribute, bottlerocket.version, should have reflected the new version, 1.0.5 in my case.

**What actually happened:**
The attribute was not updated.

**How to reproduce the problem:**
1. Add Bottlelrocket (1.0.2 instances) to a new or existing ECS cluster.
2. Validate the custom attribute reflects the version in ECS console.
3. Drain the instance.
4. Update the instance using "System Manager - Run Command".
5. Verify the update was successful in CW Logs.
6. Reboot the instance
7. Validate the custom attribute was not updated.

**Comment by zmrow** [comment]
Thanks for opening this!  We'll look into it.

**Comment by jpculp** [comment]
Thanks @umairishaq for pointing this out. Due to some limitations in the ECS API we've decided to remove this attribute. We'll leave the issue open for now so that we can explore other options at a later date.

**Comment by stmcginnis** [comment]
The origin issue has been addressed (by removing it), and there hasn't been any new ideas for doing things differently. Therefore going to close, but feel free to file a new issue if you have an idea for improvement.
