### ISSUE TITLE
EKS - Support kube-bench CIS scan

### ISSUE THREAD

**Issue by felipeac** [bottlerocket-os/bottlerocket#1294]
## Expected Behavior

kube-bench report should return valid results when scanning Bottlerocket OS nodes.
```
== Summary total ==
14 checks PASS
0 checks FAIL
1 checks WARN
0 checks INFO
```
## Actual Behavior

The kube-bench scan is throwing invalid results because Bottlerocket OS places the kubelet config files in a different location and Bottlerocket doesn't have some missing properties.

**Report before applying any change to either kube-bench or Bottlerocket:**

```
== Summary node ==
1 checks PASS
13 checks FAIL
1 checks WARN
0 checks INFO

== Summary total ==
1 checks PASS
13 checks FAIL
1 checks WARN
0 checks INFO
```

**Report after applying configs changes (add right kubelet path) to kube-bench:**
**Issue on kube-bench: https://github.com/aquasecurity/kube-bench/issues/808**

```
== Summary node ==
12 checks PASS
2 checks FAIL
1 checks WARN
0 checks INFO

== Summary total ==
12 checks PASS
2 checks FAIL
1 checks WARN
0 checks INFO
```

**Report after applying the requested changes to Bottlerocket:**

```
== Summary node ==
14 checks PASS
0 checks FAIL
1 checks WARN
0 checks INFO

== Summary total ==
14 checks PASS
0 checks FAIL
1 checks WARN
0 checks INFO
```

## Steps to Reproduce the Problem

  1. Deploy an EKS cluster on AWS with a node group using Bottlerocket OS
  2. Deploy kube-bench Docker image to a container registry 
  3. Deploy job-eks.yaml to the EKS Cluster

## Specifications

  - Version: k8s 1.18
  - Platform: AWS EKS

**Comment by bcressey** [comment]
Done.
