### ISSUE TITLE
Support a separate ENI/Instance-Type Map list for Custom Networking modes

### ISSUE THREAD

**Issue by diranged** [bottlerocket-os/bottlerocket#1307]
**What I'd like:**
For users running the EKS AWS VPC CNI in "[Custom Networking](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html)" mode, the supplied [packages/os/eni-max-pods](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/os/eni-max-pods) file does not work. The mappings are incorrect because you have to remove an ENI from the math.

Ideally either BottleRocket would be smart enough to do that math for us (unlikely), or at a minimum it could include a second ENI-to-InstanceType map file and give us the option to select that file instead.

**Comment by bcressey** [comment]
I suppose the way I'd approach this is by having one ASG or managed node group per instance type, and then just overriding `settings.kubernetes.max-pods` via user-data with the right value for that instance type within the launch template.

Is that unworkable for some reason?

**Comment by diranged** [comment]
@bcressey,
  So - if you operate with the Kubernetes cluster-autoscaler, they specifically encourage you to use ASGs exactly as you described. However, if you operate with a third party management tool like Spot.io, you are encouraged to have a wide range of instance types in your mix so that Spot.io's Ocean product can scale up the "right" sized hosts for the workloads. We operate in both - we use ASGs for our "core system" pods, but we use Ocean to scale out our developers workloads.

  I sort of feel like if we're already willing to bake in a "max pods" list into the EKS and BottlerocketEKS AMIs, baking in a second "max pods in custom networking mode" list is very reasonable to do. I've prototyped it locally by building our own image with the new list (generated in https://github.com/bottlerocket-os/bottlerocket/pull/1309) and it works.

  I would like to build a better PR where I create a flag that lets you define the "eni pod list" source.. (even optionally allowing you to curl it or something) .. but I am finding the rust templating system really tough to understand for some reason, so I got a bit lost. I would happily help finish up the PR though with a bit of guidance on how to add in options?

  By the way.. here's the bash-code we implemented on our non-bottlerocket EKS AMIs so that we would dynamically generate the calculation on-bootup:
```
# https://github.com/awslabs/amazon-eks-ami/pull/494/files#diff-049390d14bc3ea2d7882ff0f108e2802ad9b043336c5fa637e93581d9a7fdfc2
# * First IP on each ENI is not used for pods
# * 2 additional host-networking pods (AWS ENI and kube-proxy) are accounted for
MAX_PODS=$(cat $ENI_DATA_FILE | awk "/^$INSTANCE_TYPE/"' { print $2 * ($3 - 1) + 2 }')

# Handle cases where using custom ENIConfig
if [ "$USING_CUSTOM_ENICONFIG" == "true" ]; then
    MAX_PODS=$(cat $ENI_DATA_FILE | awk "/^$INSTANCE_TYPE/"' { print ($2 - 1) * ($3 - 1) + 2 }')
fi

# Now, simply export the MAX_PODS variable
if [ ! -z "${MAX_PODS}" ]; then
  echo "Setting MAX_PODS to ${MAX_PODS}"
  test -f /etc/eks/eni-max-pods.txt && sed -i "s/${INSTANCE_TYPE} .*/${INSTANCE_TYPE} ${MAX_PODS}/g" /etc/eks/eni-max-pods.txt || true
fi
```

where the source list is actually a list of instance types, their ENI count, and then the max IPs per ENI:

```
c3.8xlarge 8 30
c4.large 3 10
c4.xlarge 4 15
c4.2xlarge 4 15
c4.4xlarge 8 30
c4.8xlarge 8 30
c5.large 3 10
c5.xlarge 4 15
c5.2xlarge 4 15
c5.4xlarge 8 30
```

**Comment by bcressey** [comment]
> I sort of feel like if we're already willing to bake in a "max pods" list into the EKS and BottlerocketEKS AMIs, baking in a second "max pods in custom networking mode" list is very reasonable to do.

Yeah, I agree. There's not really an argument for purity of implementation if we're already tying a default value so closely to a specific setup - running as a worker node under EKS using the VPC CNI plugin in its default configuration. In a perfect world there'd be a feedback mechanism from the CNI plugin itself that could put an upper bound on max pods, so all of this logic could be moved closer to where the constraints actually come from.

> I would like to build a better PR where I create a flag that lets you define the "eni pod list" source.. (even optionally allowing you to curl it or something).

We have a forthcoming "host files" feature that's a sort of spiritual counterpart to #1208, which will offer a limited mechanism to generate data files on the host at startup.

However, I'm reluctant to allow the rest of the system to depend on these files - it raises other questions like "what if we're told to use <X> for max pods, but the file doesn't exist or is in the wrong format?" "what if our expected format changes on upgrade?"

I wonder if instead we're missing an abstraction, like:
```
[settings.kubernetes]
max-pods-heuristic = [ vpc-cni | vpc-cni-custom | ... ]
```

Where we could default to "vpc-cni" but allow another pre-defined heuristic to be selected. That would let `max-pods` be generated in a slightly different way, and give us a clean way to select one data source or the other.

**Comment by stmcginnis** [comment]
Ben has provided a workaround that seems to work. There is also a desire to maintain consistency with other EKS AMIs, so there are no plans to change this, so going to close this for now since it has been out here for a while.
