### ISSUE TITLE
Can we customize the "OS Image" name for our images?

### ISSUE THREAD

**Issue by diranged** [bottlerocket-os/bottlerocket#1314]
If we bake our own Bottlerocket images, it would be nice to be able to identify them in Kubernetes with the "OS Image" field. Is there a way for us to customize that string from the build process today?

**Comment by bcressey** [comment]
Looks like the OS Image field is coming from the `PRETTY_NAME` field in `/etc/os-release`, which is generated in `rpm2img`, which hard-codes "Bottlerocket OS" - a similar problem to #1311.

I could imagine a couple different approaches:
* something clever, where we split "my-bottlerocket" on hyphens, uppercase the first letter, and turn it into "My Bottlerocket"
* full control over the fixed "Bottlerocket OS" string, where we have a dedicated variable that can be overridden.

The first approach conserves a variable - one fewer thing that needs to be overridden for a given remix - but seems unlikely to produce aesthetically pleasing results for a wide sample size.

Another factor is our [trademark policy](../blob/develop/TRADEMARKS.md). Ideally we'd want remixes to have an easy way of conforming to the policy.

That inclines me toward the second approach, e.g. a `BUILDSYS_PRETTY_NAME` variable that defaults to "Bottlerocket OS", with a comment suggesting "Bottlerocket Remix by ${CORP}" or "${CORP}'s Bottlerocket Remix" as possible customizations.
