### ISSUE TITLE
Update tokio-related dependencies

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1345]
In `sources/` and `tools/` we have a number of crates that need updates to tokio-related dependencies, now that tokio 1.0 is out and other crates have updated to use it.  This includes updating tokio itself, plus hyper, hyper-unix-connector, and reqwest.

**Comment by webern** [comment]
This is the same as #1269

**Comment by webern** [comment]
Basically tough is the blocker, we should release to ensure we're unblocked: https://github.com/awslabs/tough/pull/350
