### ISSUE TITLE
Way to install kubelet plugins?

### ISSUE THREAD

**Issue by fasaxc** [bottlerocket-os/bottlerocket#1354]
**What I'd like:**

I'm trying to get Calico to install onto an EKS Bottlerocket system.  By default, Calico tries to install a flexvol driver by mounting `/usr/libexec/kubernetes` in from the host and dropping the binary in there.  However, on Bottlerocket systems, that directory is read-only.  I was wondering if the path is different on Bottlerocket or if kubelet plugins simply are not supported.

**Any alternatives you've considered:**

* Add workarounds to our docs "remove this part of the YAML"; not a great UX.
* Provide yet-another axis of manifests; so the user has to select "calico-with-vxlan-for-bottlerocket.yaml".  Again, this gives a poor UX where the user has to make lots of decisions.
* Replace our flexvol driver with something else, maybe installing a CSI driver is supported?
* Don't support bottlerocket.

**Comment by bcressey** [comment]
CSI drivers would be supported.

I'll check whether it will be sufficient to add a compatibility symlink from `/usr/libexec/kubernetes/kubelet-plugins` to `/var/lib/kubelet/plugins`, which is where our `kubelet` is configured to look.
