### ISSUE TITLE
Cilium Cluster Scope Support

### ISSUE THREAD

**Issue by domgoodwin** [bottlerocket-os/bottlerocket#1367]
**Image I'm using:**
ami-059c8b27104178e42

**What I expected to happen:**
Deploying Cilium onto Bottlerocket nodes in an EKS cluster should allow Cluster Pool networking where it's in an overlay node and outbound requests go via SNAT.

**What actually happened:**
Egress from pods did not work with no errors found in selinux audit logs or otherwise

**How to reproduce the problem:**
1. Have unmanaged Bottlerocket nodes provisioned as part of EKS cluster
2. Following the guide [here](https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-eks/) install Cilium not using ENI mode
```
helm install cilium cilium/cilium --version 1.9.4 \
  --namespace kube-system \
  --set egressMasqueradeInterfaces=eth0
```
3. Cilium pods and operator will come up fine however any other pods won't be able to egress, including Coredns

**Comment by jhaynes** [comment]
Thanks for the report @domgoodwin. We've run Cilium on Bottlerocket successfully, but haven't tried to run in this configuration. We'll dive in soon, but do you know if this configuration works on the AL2 based EKS optimized AMI?

**Comment by domgoodwin** [comment]
Yes, so the exact configuration and networking setup works with AL2.

One thing suggested was this note around a systemd flag:

```
Systemd 245 and above (systemctl --version) overrides rp_filter setting of Cilium network interfaces. This introduces connectivity issues (see GH-10645 for details). To avoid that, configure rp_filter in systemd using the following commands:

echo 'net.ipv4.conf.lxc*.rp_filter = 0' > /etc/sysctl.d/99-override_cilium_rp_filter.conf
systemctl restart systemd-sysctl
```

I wasn't able to see how I'd change that from my initial look but did see systemd is above version 245

I'm going to test out again setting this:
```
[settings.kernel.sysctl]
"net.ipv4.conf.lxc*.rp_filter" = "0"
```

**Comment by domgoodwin** [comment]
Setting this in the config file didn't seem to fix it
```
[settings.kernel.sysctl]
"net.ipv4.conf.all.rp_filter" = "0"
```

Unsure what else I can try, the reccomended value `net.ipv4.conf.lxc*.rp_filter = 0` didn't work due to the * not being accepted as valid

**Comment by izaakschroeder** [comment]
This may be related: https://github.com/cilium/cilium/issues/14459 😄

**Comment by jpculp** [comment]
@domgoodwin, thank you for your patience in all of this. We've done some testing on our end and confirmed that you were on the right track with `rp_filter`. At the moment it is not possible to remedy this via userdata, but there are two manual approaches you can take:

**Approach 1: Patch nodes directly**
- Enable and connect to a node's admin container.
- Run `sudo sheltie`.
- Patch sysctl config:
```
echo 'net.ipv4.conf.lxc*.rp_filter = 0' > /etc/sysctl.d/99-override_cilium_rp_filter.conf
systemctl restart systemd-sysctl
```
- Redeploy `coredns`: `kubectl rollout restart -n kube-system deployment/coredns`

**Approach 2: Build a custom Bottlerocket AMI with patched sysctl config**
- Add the following lines to `packages/release/release-sysctl.conf`:
```
# Disable rp_filter by default
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.*.rp_filter = 0
```
- Build the custom AMI by following our [build guide](https://github.com/bottlerocket-os/bottlerocket/blob/develop/BUILDING.md).

Either of those should be able to get you going until we can release a more built-in approach.
We'll keep this issue open until then! :rocket:
