### ISSUE TITLE
Pods stuck in creating state due to mount failure

### ISSUE THREAD

**Issue by PenguinToast** [bottlerocket-os/bottlerocket#1379]
**Image I'm using:**
amazon/bottlerocket-aws-k8s-1.18-x86_64-v1.0.6-ee56d1fc

**What I expected to happen:**
Pods should not fail to start

**What actually happened:**
On some nodes, after some point in time, all pods start failing to start with error messages similar to the following:
```
MountVolume.SetUp failed for volume "aws-iam-token" : mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/575d1107-f6bf-4549-86c2-a84ebdaf5bfc/volumes/kubernetes.io~projected/aws-iam-token --scope -- mount -t tmpfs tmpfs /var/lib/kubelet/pods/575d1107-f6bf-4549-86c2-a84ebdaf5bfc/volumes/kubernetes.io~projected/aws-iam-token
Output:
```
Most of our nodes still operate fine, and there do appear to be pods that started before the node reached this state that are running without a problem. Running `df -h` on a pod w/ a root shell shows only `75%` disk usage on the data partition.

**How to reproduce the problem:**
We haven't found any consistent way to put a node in this failure state; but it's been observed on 3 independent nodes in the past week.

**Comment by bcressey** [comment]
Might also be worth checking `df -hi` to verify that the `/local` filesystem is not out of inodes.

**Comment by PenguinToast** [comment]
Good point, just checked but unfortunately I also see ~75% inode usage there

**Comment by bcressey** [comment]
Is there anything following "Output" or it's actually empty?

**Comment by bcressey** [comment]
We suspected this might be the known issue upstream where systemd can get bogged down when managing a large number of mounts, exacerbated by a [Bottlerocket-specific patch](https://github.com/bottlerocket-os/bottlerocket/commit/4781e3a5) that lowers default timeouts, resulting in `systemd-run` taking too long to complete.

However it seems like it's systemd becoming unresponsive at much lower numbers - 20 pods with only 2 mounts per pod.

**Comment by bcressey** [comment]
We're pretty sure this is the end state after systemd segfaults and ends up frozen, per https://github.com/systemd/systemd/issues/17768.

**Comment by jhaynes** [comment]
@PenguinToast we expect that our [1.0.7 release](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.0.7) has fixed this bug. I'm going resolve this issue for now, but if you're still running into this, please re-open and we'll keep digging!

**Comment by PenguinToast** [comment]
Yep, I haven't seen this behavior re-occur since 1.0.7 was deployed -- thanks for the help here!
