### ISSUE TITLE
Add tests to imdsclient

### ISSUE THREAD

**Issue by jpculp** [bottlerocket-os/bottlerocket#1398]
**What I'd like:**
#1372 adds a shared IMDS client to be used by several critical processes in Bottlerocket. @webern and I would like to add testing to `imdsclient`. Tests could potentially be written with a mock server and a constructor, while the real clients would use an implemented `Default`.

**Any alternatives you've considered:**

`imdsclient` could simply not have automated testing, but then we risk introducing a bug that would prevent Bottlerocket from booting.

**Comment by jpculp** [comment]
Added @webern so we can work together on an optimal solution.

**Comment by webern** [comment]
This was done in #1372
