### ISSUE TITLE
Trim VMWare kernel config

### ISSUE THREAD

**Issue by gregdek** [bottlerocket-os/bottlerocket#1410]
"Need to restrict support to just NVME for storage and VMXNET3 for network"

**Comment by bcressey** [comment]
Here are the VMware modules we have enabled:
```
CONFIG_VMXNET3=m
CONFIG_VMWARE_PVSCSI=m
CONFIG_VMWARE_VMCI_VSOCKETS=m
CONFIG_VMWARE_VMCI=m
```

vmci and vmsock are used for the guestinfo mechanism. vmxnet3 is used for networking, and the PVSCSI driver is used by the vSphere CSI provider.
