### ISSUE TITLE
Wire up Control container and SSM to register off of AWS via token from userdata/api

### ISSUE THREAD

**Issue by gregdek** [bottlerocket-os/bottlerocket#1411]
* init token sent through user data  
* have control container see that data and set up as self-registered

**Comment by jpculp** [comment]
Primary PR:
- [x] https://github.com/bottlerocket-os/bottlerocket-control-container/pull/12

Associated PRs:
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/1416
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/1441

**Comment by jpculp** [comment]
Additional PR to set as default.
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/1466
