### ISSUE TITLE
include grep in the host OS

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#1414]
**What I'd like:**
I'd like to have `grep` available in the host OS to help inspect logs.

**Any alternatives you've considered:**
Either running `grep` from the admin container or using other tools to find output. This can be inconvenient, especially if interrupts a troubleshooting session inside a host shell.

**Comment by swade1987** [comment]
This would've been extremely useful when needing to run the following command to remove old calico IP tables rules

```
iptables-save | grep -v cali- | iptables-restore
```

**Comment by arnaldo2792** [comment]
I already built it in my branch, I'm working in the PR :+1:
