### ISSUE TITLE
cargo make test

### ISSUE THREAD

**Issue by gregdek** [bottlerocket-os/bottlerocket#1419]
@webern wrote in April 2022:

We have created a system for testing Bottlerocket images over at https://github.com/bottlerocket-os/bottlerocket-test-system/
We want to integrate that system here. The ultimate goal is to run `cargo make test` after `cargo make build`, `cargo make ami`, and `cargo make repo` (and I guess we need something for pushing the repo), end then the `bottlerocket-test-system` will run integration tests (e.g. sonobuoy for k8s, upgrade/downgrade, etc).

- [x] #2147
- [x] #2148
- [x] #2149
- [x] #2150
- [x] #2151
- [x] #2152

@gregdek wrote in March 2021: Currently we use an internal testing system for validating Bottlerocket instances. We would like to run more publicly, and need to design a suitable replacement.  This is a large effort and may spawn several related issues.

**Comment by ecpullen** [comment]
All listed testing workflows are now supported. Closing this issue!
