### ISSUE TITLE
Create capsys for launching Bottlerocket test instances

### ISSUE THREAD

**Issue by gregdek** [bottlerocket-os/bottlerocket#1420]
As a companion to testsys (https://github.com/bottlerocket-os/bottlerocket/issues/1419), we imagine a system named capsys for launching Bottlerocket instances to be used by testsys tests. Capsys would be responsible for launching the Bottlerocket instance with appropriate userdata to facilitate the tests. Remaining neutral with respect to platform and container orchestrator will be among the challenges for capsys to solve.

This issue represents the larger capsys concept and project. Smaller issues will be used to represent tactical progress on the project.

**Comment by tjkirch** [comment]
Closing this as it was based on an earlier design for testing that we're moving on from.  (Not to say that we won't need something similar, but it will, at a minimum, fit in differently.)
