### ISSUE TITLE
`settings.kubernetes.cluster-dns-ip` should be optional

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#1453]
Outside of EKS, we cannot compute a value for this, and there's not a reasonable default.  We also need to account for it being optional for kubelet in standalone mode.

We will need to:
* Make it an `Option<>` in the model
* Add an `{{#if ... }}` statement to the `kubelet-config` files for that setting

**Comment by tjkirch** [comment]
> Make in an `Option<>` in the model

Everything in the model is made `Option` by `#[model]`, so we should just need the conditional.

**Comment by zmrow** [comment]
Fixed via #1482
