### ISSUE TITLE
All variants: update `cloud-provider` argument for `kubelet`

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#1459]
### Problem
For our existing AWS Kubernetes variants we hard-code `--cloud-provider "aws"` in the `kubelet` args.

Clusters provisioned by ClusterAPI Provider for vSphere must use `--cloud-provider "external"`.  At the time of writing, clusters provisioned by Cluster API Provider for AWS don't default to `--cloud-provider "external"` yet, [but might later](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/964).

Upstream Kubernetes [is in the process](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers/README.md) of removing all in-tree cloud provider code.  This is slated to be GA in 1.25, at which point `--cloud-provider "external"` will be mandatory.

### Recommended solution
We should add a new setting: `settings.kubernetes.cloud-provider` that will only accept the values "aws" and "external".  When `--cloud-provider "external"` becomes mandatory in the future, and all providers are removed from in-tree upstream, we can remove the setting for the Kubernetes variants that are on at least that version.  Unfortunately, this means we'll need to carry the setting until older Kubernetes versions "age out".

### Alternatives
* We could conditionalize the `--cloud-provider` argument in the `kubelet-exec-start-conf` template based on some other factor, for example `settings.aws.region`.  This would be unreliable in DIY Kubernetes installs, or when using Cluster API Provider for AWS.

**Comment by tjkirch** [comment]
Something like `{{#if settings.aws}}aws{{else}}external{{/if}}`, perhaps, to remove the need for a setting?

>  This would be unreliable in DIY Kubernetes installs, or when using Cluster API Provider for AWS.

Can you expand on this a bit?  Is the issue that it would be detected as AWS because of IMDS, but we _wouldn't_ want to use `--cloud-provider aws`?  (Why?)

**Comment by bcressey** [comment]
Some people will want to use the [external AWS cloud provider](https://github.com/kubernetes/cloud-provider-aws) - I'd expect more interest here as the date for deleting the in-tree provider code looms closer.
