### ISSUE TITLE
early-boot-config: handle empty user data

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1470]
We started with k8s variants that required user data to be able to connect to a cluster.  Later variants don't necessarily require user data - for example, the ECS variant can use the default cluster.  The -dev variants may not need any settings in some use cases.

Today, empty user data is considered an error, for example with an aws-k8s variant you can see early-boot-config fail like this, followed by a number of services failing due to a dependency on early-boot-config, or from missing settings.  (Since settings-committer can't run, there are no default settings available, either.)

```
[    8.869121] early-boot-config[2935]: Provider error: TOML data did not contain 'settings' section
```

**Comment by stmcginnis** [comment]
Need to test to see if this is still an issue.

**Comment by stmcginnis** [comment]
Probably actually not going to be able to get to this soon, so unassigning in case someone else wants to pick it up.

Easiest test would probably be to use something like a metal-dev or vmware-dev instance and boot it (can use QEMU) without providing any user-data.
