### ISSUE TITLE
logdog should collect all available log files for ECS CNI plugins

### ISSUE THREAD

**Issue by samuelkarp** [bottlerocket-os/bottlerocket#1481]
**What I'd like:**
As part of enabling the ECS `awsvpc` networking mode for Bottlerocket (https://github.com/bottlerocket-os/bottlerocket/pull/1246), several new ECS-related components (CNI plugins) are added to Bottlerocket.  As independent components, they do not share the log file that is used by the ECS agent itself.  These components do their own log file rotation by writing files with hourly timestamp suffixes (and one of them even uses the hourly timestamp suffixed file name for the current log file), with file names like `vpc-branch-eni.log.2021-04-09-00`.  Today, there is no mechanism to specify a non-static log file name with logdog, so logdog cannot collect any log files with hourly timestamp suffixes.

**Any alternatives you've considered:**
Here are some potential approaches

1. Enable logdog to specify file paths with *wildcards*.  Wildcards would enable us to specify a pattern of files to collect and is very flexible.  However, the flexibility makes wildcards somewhat complicated (we'd need to define the exact rules we want to use for expansion) and we may not really need that level of flexibility.
3. Enable file *prefixes* with logdog.  Rather than an arbitrary pattern, prefixes are less complicated and easier to reason about.  Prefixes adequately cover all of the ECS-related use-cases; none of the log files ever change the beginning of their names.
4. Collect whole *directories* rather than just files.  We could add a new directory directive to logdog’s configuration file.  When a directory is specified, logdog includes the contents of the whole directory.  For ECS, all of the log files are contained in /var/log/ecs, even rotated ones.

**Comment by tjkirch** [comment]
>  However, the flexibility makes wildcards somewhat complicated (we'd need to define the exact rules we want to use for expansion)

I think we can use the glob crate and get a syntax that's widely understood, since it mimics shell wildcards.  It's strictly more powerful, and easier to implement, too.

**Comment by srgothi92** [comment]
Fixed in [PR-1509](https://github.com/bottlerocket-os/bottlerocket/pull/1509)
