### ISSUE TITLE
vmware-dev: No systemd output to console

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#1489]
**Image I'm using:**
`vmware-dev`

**What I expected to happen:**
Using the vSphere web console to view boot output, I expected to see all kernel and systemd messages.

**What actually happened:**
I see all kernel output, but nothing from systemd and all of the Bottlerocket boot services.  The following is the last message before a login prompt:
```
<ugly time here> vmxnet3 0000:03:00.0 eth0: NIC Link is up 10000Mbps
```

**How to reproduce the problem:**
Boot the `vmware-dev` variant on VMWare and view output using the web console

**Comment by bcressey** [comment]
We'll need to add the ability to specify custom kernel command-line arguments in the variant definition, rather than using a fixed `console=ttyS0` value everywhere.

**Comment by tjkirch** [comment]
> We'll need to add the ability to specify custom kernel command-line arguments in the variant definition, rather than using a fixed `console=ttyS0` value everywhere.

I made #1490 to track this, which I plan to do soon.  Then, this issue would hopefully just be adding the `console` line to the vmware-dev variant definition.

**Comment by zmrow** [comment]
After doing a little research, it seems like once we get the correct `console` device figured out, we should be able to forward all of `systemd`/`journald`'s output to it via:
```
systemd.log_target=console systemd.journald.forward_to_console=1
```

The kernel _should_ output to all console devices present.

Resources:
1.  https://www.kernel.org/doc/html/v4.14/admin-guide/serial-console.html
2. https://freedesktop.org/wiki/Software/systemd/Debugging/

**Comment by tjkirch** [comment]
> systemd.log_target=console systemd.journald.forward_to_console=1

I think we can get away with just fixing `console` since we already get the desired behavior on other platforms that have correct `console`, but it's good to have backup experiments.

**Comment by jpculp** [comment]
Merged.
