### ISSUE TITLE
Allow lock on the current version in `updates.version-lock` setting 

### ISSUE THREAD

**Issue by srgothi92** [bottlerocket-os/bottlerocket#1500]
**What I'd like:**
`settings.updates.version-lock` allows users to lock on the Bottlerocket version. It also, supports a label **latest** allowing `updog` to  detect latest version. Similarly, users would like to have a label (**current** maybe ?) allowing them to lock on current version. This new label can be very useful for all the update coordinators (ECS Updater, Bottlerocket Update Operator) where the stay-in-place behavior is desirable and necessary for exact control by customers over their hosts. 

**Any alternatives you've considered:**
1. Query the current Bottlerocket and set the version lock on it.
2.  Set dummy version that won’t match anything: v0.0.0 (because it must parse as valid semver). This means that no updates will report as available and, because it is a semver value, it doesn't produce errors in the code paths that it travels. 
3. Support a new label "current" to lock on current OS version.

**Comment by etungsten** [comment]
`current` as a term for versions is quite vague and can lead to misinterpretations by users or external system if they ever depend on it. 
In essence, this would be akin to having a settings flag that disables update all together for a host. If customers wishes to do so, the recommended way would be to achieve this through configuration of the update operator or labelling/tagging of the hosts.
