### ISSUE TITLE
Cannot resize EBS pvc on bottlerocket nodes - resize2fs not found in $PATH

### ISSUE THREAD

**Issue by samjo-nyang** [bottlerocket-os/bottlerocket#1518]
**Image I'm using:**
v1.0.4, k8s-1.18 variants

**What I expected to happen:**
```
FileSystemResizeSuccessful MountVolume.NodeExpandVolume succeeded for volume "pvc-xxx"
```

**What actually happened:**
```
MountVolume.MountDevice failed while expanding volume for volume "pvc-xxx" : MountVolume.NodeExpandVolume failed : resize of device /dev/nvme5n1 failed: executable file not found in $PATH. resize2fs 
```

**How to reproduce the problem:**
1. provision an ebs volume using ebs csi driver
2. try to extend the volume

I made and tested a simple patch that resolve this issue - just add enable-resizer and resize2fs binary on `packages/e2fsprogs/e2fsprogs.spec`; can I make a PR?

**Comment by bcressey** [comment]
Sure, a PR would be great! Thanks for digging into this.
