### ISSUE TITLE
Some CSI drivers write to /etc/kubernetes/secrets-store-csi-providers 

### ISSUE THREAD

**Issue by joebaro** [bottlerocket-os/bottlerocket#1524]
**Image I'm using:**
EKS 1.17 with Bottlerocket OS 1.0.8 (ami-04f83bfb1bb568e28)

**What I expected to happen:**
Install and run the [Secret Store CSI driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) and the  AWS provider plugin by following the setup instructions in the [secrets-store-csi-driver-provider-aws](https://github.com/aws/secrets-store-csi-driver-provider-aws) README.

**What actually happened:**
The driver plugin fails with "permission denied" when binding to a unix domain socket in /etc/kubernetes/secrets-store-csi-providers/aws.sock (see also [secrets-store-csi-driver-provider-aws issue](https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/6)). The Secret Store CSI driver is using /etc/kubernetes/secrets-store-csi-providers as a rendezvous point for unix domain sockets with its various provider plugins.

As directed by Ben Cressey we are opening this issue to ask for a compatibility symlink from ```/etc/kubernetes/secrets-store-csi-providers``` to somewhere under ```/var```

**How to reproduce the problem:**
Install the Secret Store CSI driver, install the AWS plugin, run ```kubctl logs``` on one of secrets-store-csi-driver-provider-aws instances.

**Comment by zmrow** [comment]
Thanks for opening this - we'll look into it!

**Comment by rverma-dev** [comment]
Can we cherry pick this fix in 1.0.8, its a blocker for us.

**Comment by jhaynes** [comment]
@rverma-nsl You're welcome to do the cherry-pick for a custom build if you'd like. However, we're slated to release `1.1.0` [shortly ](https://github.com/bottlerocket-os/bottlerocket/pull/1553) which will have this fix in it. Hopefully you can upgrade to this `1.1.0` release and pick it up that way.
