### ISSUE TITLE
document webpki-roots-shim dependency and version behavior

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#1539]
Ensuring that our webpki-roots-shim package is used requires some special knowledge and handling. In particular, when updating anything that uses webpki-roots (currently I think this is only reqwest), we need to make sure that we update the version of webpki-roots-shim to match. If we do not, then it will be pulled from crates.io.

Maybe here is the best place to document this further?
https://github.com/bottlerocket-os/bottlerocket/blob/66eef8b547796f5fa4a1df70de762197408fafab/sources/Cargo.toml#L84

**Comment by tjkirch** [comment]
sources/Cargo.toml seems like a good spot, but also somewhere in the webpki-roots-shim directory, even if it's a pointer to look at that other file.  That's probably the first place I'd look if I was doing general package updates.

The other tricky bit is that we can (currently) only have one shim, so if we wound up with dependencies that used different versions of webpki-roots, we'd be in trouble - we'd have to build multiple shim packages, I think?

**Comment by webern** [comment]
> we'd have to build multiple shim packages, I think?

Not sure the exact solution we would need to implement, but you're right that it would become tricky. I briefly looked at this one time and got the impression that something a little hacky would be required.
