### ISSUE TITLE
Link or verify settings together

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket#1585]
**What I'd like:**
Originally posted in https://github.com/bottlerocket-os/bottlerocket/issues/1385#issuecomment-797126417:
> Ability to link or verify settings together somehow, though today's serialization/deserialization treats structs as just levels, not groupings, so it'll need some thought.

It'd be nice to be able to specify dependencies between settings. For example, maybe a setting can't be a certain value if another setting has a specific value, or if a setting can only be set if another setting is unset, etc.

**Any alternatives you've considered:**
None

**Comment by stmcginnis** [comment]
@rpkelly is this covered by the settings changes being considered for out of tree builds?

Is it something we still need with that effort, or should we close this issue?

**Comment by webern** [comment]
Closing this as superseded by Settings 2.0 design.
