### ISSUE TITLE
Add kubelet options - topologyManagerPolicy and topologyManagerScope

### ISSUE THREAD

**Issue by samjo-nyang** [bottlerocket-os/bottlerocket#1597]
**What I'd like:**
https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/
I want to use topologyManagerPolicy (default as none) and topologyManagerScope (default as container) options on kubelet.
Since these fields should not be updated without a full reboot, I think it is safe to add these options as their default values.

**Any alternatives you've considered:**
None; I created a patch that adds topologyManagerPolicy and use the custom image internally.

**Comment by jpculp** [comment]
Hi @samjo-nyang! Thank you for opening up this feature request. We are looking into it, but I suspect this is fine.

**Comment by jhaynes** [comment]
This will land in our next release (`v1.2`).
