### ISSUE TITLE
Unable to mount EFS volume with the aws-efs-csi-driver

### ISSUE THREAD

**Issue by bmonteiro** [bottlerocket-os/bottlerocket#1599]
@webern, as requested

Bellow error when mounting EFS in AWS EKS running Bottlerocket OS 1.0.8. 

```
Warning  FailedMount  12s (x6 over 27s)  kubelet, ip-10-80-127-28.eu-central-1.compute.internal  MountVolume.SetUp failed for volume "pvc-8cfab7c8-9269-4586-8ffa-314b76d8d409" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubeletErr/pods/7912b416-c5a4-4be6-98e7-e794b003ddaa/volumes/kubernetes.io~nfs/pvc-8cfab7c8-9269-4586-8ffa-314b76d8d409 --scope -- mount -t nfs -o vers=4.1 10.80.120.174:/persistent-volumes/eks2/tyk/tyk-efs-volume-pvc-8cfab7c8-9269-4586-8ffa-314b76d8d409 /var/lib/kubelet/pods/7912b416-c5a4-4be6-98e7-e794b003ddaa/volumes/kubernetes.io~nfs/pvc-8cfab7c8-9269-4586-8ffa-314b76d8d409
Output: mount: /var/lib/kubelet/pods/7912b416-c5a4-4be6-98e7-e794b003ddaa/volumes/kubernetes.io~nfs/pvc-8cfab7c8-9269-4586-8ffa-314b76d8d409: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```

EFS CSI installed and running
```
**kubectl get pod -n kube-system -l app=efs-csi-node -o wide**
NAME                 READY   STATUS    RESTARTS   AGE     IP              NODE                                             NOMINATED NODE   READINESS GATES
efs-csi-node-kkj8r   3/3     Running   0          7m28s   10.80.127.28    ip-10-80-127-28.eu-central-1.compute.internal    <none>           <none>
```

```
**kubectl get nodes -o wide**
NAME                                             STATUS   ROLES    AGE     VERSION              INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME

ip-10-80-127-28.eu-central-1.compute.internal    Ready    <none>   7m47s   v1.19.9              10.80.127.28    <none>        Bottlerocket OS 1.0.8   5.4.105                       containerd://1.4.4+bottlerocket

```

**Comment by webern** [comment]
I've been trying to deploy an EFS filesystem and mount it with the driver but the setup is very complicated. I haven't had success as of yet but I'm not at all confident that I have done everything correctly. In any event, can you check this?

Find controller pod:

```sh
kubectl get pods -n kube-system | grep efs-csi-controller
```

Check logs

```sh
kubectl logs efs-csi-controller-youruuid-youruuid \
    -n kube-system \
    -c csi-provisioner \
    --tail 10
```

In my case I'm seeing things like "File System does not exist: Resource was not found" which sounds like configuration error rather than a Bottlerocket issue. I'll have to start over and follow the instructions more carefully! They have changed quite a bit since I worked on this last.

**Comment by webern** [comment]
With a little more elbow grease, I was able to show the efs-csi-driver working on Bottlerocket (v1.1.1). I had missed a step regarding the ServiceRole. Once that was fixed I got an EFS volume mounted:

```text
0528 22:49:23.558414       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"efs-claim", UID:"6f6eec3f-a961-4c63-88cb-06f334135eaa", APIVersion:"v1", ResourceVersion:"22109748", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/efs-claim"
I0528 22:49:24.697702       1 controller.go:838] successfully created PV pvc-6f6eec3f-a961-4c63-88cb-06f334135eaa for PVC efs-claim and csi volume name fs-2caca52b::fsap-0d7c1df6766aaef8c
I0528 22:49:24.697735       1 controller.go:1439] provision "default/efs-claim" class "efs-sc": volume "pvc-6f6eec3f-a961-4c63-88cb-06f334135eaa" provisioned
I0528 22:49:24.697754       1 controller.go:1456] provision "default/efs-claim" class "efs-sc": succeeded
I0528 22:49:24.711476       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"efs-claim", UID:"6f6eec3f-a961-4c63-88cb-06f334135eaa", APIVersion:"v1", ResourceVersion:"22109748", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-6f6eec3f-a961-4c63-88cb-06f334135eaa
```

And the example application from [the documentation](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html) was writing to the EFS volume.

**Comment by bmonteiro** [comment]
I was using v1.0.8 maybe I can try v1.1.1 like u did. I will check that.

**Comment by webern** [comment]
> I was using v1.0.8 maybe I can try v1.1.1 like u did. I will check that.

You can try that, but I would recommend looking at the logs of the efs controller first. I find it highly unlikely that the Bottlerocket version made a difference here.  The most likely scenario is that something (permissions, a security group, etc) is not configured correctly. The controller logs should give us something to go on.

```
kubectl get pods -n kube-system | grep efs-csi-controller
```

```
kubectl logs efs-csi-controller-youruuid-youruuid \
    -n kube-system \
    -c csi-provisioner \
    --tail 10
```

**Comment by bmonteiro** [comment]
@webern 

Interesting, I'm tailing -f both pods (efs csi controllers) not even 1 entry in the logs (2 last tabs)

<img width="1792" alt="Screenshot 2021-05-29 at 21 19 11" src="https://user-images.githubusercontent.com/908425/120082462-8d7f0680-c0c3-11eb-974e-f6350be89e22.png">

**Comment by webern** [comment]
It seems like the PV is not being provisioned by the EFS CSI.

Are you using a storage class and dynamic PV provisioning? My storage class looks like this:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-2cbcc52a
  directoryPerms: "700"
```

My pod created a PVC (and thus a dynamically created PV) like this:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
```

These came from the [EFS CSI documentation](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html).

**Comment by bmonteiro** [comment]
@webern 

I have both also, this is indeed interesting. I will need to anyway build a new cluster will keep the issue updated. Let's see. Thx so far ;)

**Comment by webern** [comment]
Hi @bmonteiro, did you manage to get EFS volumes working? I will close this issue but please re-open if you are still having a problem. Thanks!
