### ISSUE TITLE
Update bash to 5.1

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1613]
It's only used in the -dev variants for console login, so it's low priority, but would be nice.

The last time I tried to do this, I ran into a sporadic build failure, so we have to figure out what's changed with builtext and make sure it's reliable: https://github.com/bottlerocket-os/bottlerocket/pull/1460#issuecomment-815105938

**Comment by markusboehme** [comment]
Updated in #2145, this time without being able to reproduce the build failures.
