### ISSUE TITLE
Adding trusted certificate authorities

### ISSUE THREAD

**Issue by netjordan** [bottlerocket-os/bottlerocket#1627]
**What I'd like:**
To be able to add additional certificate authorities to be trusted.  We have two reasons for this:
 - We run our own docker image repository, with a TLS certificate issued by our internal certificate authority.
 - We have an enterprise network TLS proxy which presents certificates issued by it's own internal CA when visiting websites. 

**Any alternatives you've considered:**
I've done some 'googling' but am unable to find any examples of this.

**Comment by webern** [comment]
I think this is a duplicate of #1277.

**Comment by netjordan** [comment]
> I think this is a duplicate of #1277.

Agreed, closing this.
