### ISSUE TITLE
The latest ami '1.20.8' has break the support of gcr repos.

### ISSUE THREAD

**Issue by rverma-dev** [bottlerocket-os/bottlerocket#1633]
Image: ami-090c21e95115589cc

Not able to pull docker images

```
Failed to pull image "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.20.0": rpc error: code = Unknown desc = failed to pull and unpack image "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.20.0": failed to copy: httpReaderSeeker: failed open: failed to do request: Get "https://storage.googleapis.com/asia.artifacts.k8s-artifacts-prod.appspot.com/containers/images/sha256:264383db0b5129f3cf0cb4bb3cad95c604f89128d08713e81b6724883196f007": x509: certificate signed by unknown authority
```

**Comment by jhaynes** [comment]
Hi @rverma-nsl. Sorry you're running into this. We haven't been able to reproduce this error. Can you share more details of your environment and configuration? Specifically, what region was this working on? Did it work on a prior Bottlerocket version (and if so, which)?  

If you'd rather not do that here, feel free to open a support case through AWS Support or email me directly (jushay at amazon dot com) and I can create a private issue.

**Comment by zmrow** [comment]
@rverma-nsl we haven't heard back on this issue in a few weeks so we'll go ahead and close this.  Please feel free to re-open if you continue to see the problem! :)
