### ISSUE TITLE
VMWare: CAPV integration

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#1639]
**What I'd like:**
I'd like to be able to use [Cluster API Provider vSphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere) to provision and manage Bottlerocket nodes.

Currently there are a few issues (potentially more) with CAPV that need to be fixed:
* CAPV only [supports one disk](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1166) per VM (Bottlerocket has 2)
* CAPV uses cloud-init YAML user data when provisioning nodes rather than our TOML user data.

**Any alternatives you've considered:**

**Comment by zmrow** [comment]
Related to the discussion in #1635.

**Comment by etungsten** [comment]
@zmrow do you think this issue can be closed?

**Comment by etungsten** [comment]
EKS-A has a CAPV provider that lets users deploy Bottlerocket cluster nodes:
https://anywhere.eks.amazonaws.com/docs/getting-started/production-environment/vsphere-getstarted/
