### ISSUE TITLE
Allow ssh using EC2InstanceConnect

### ISSUE THREAD

**Issue by willthames** [bottlerocket-os/bottlerocket#1641]
**What I'd like:**

I would like to be able to use EC2InstanceConnect to ssh into the admin container

We use EC2InstanceConnect to connect to our amazon linux instances and it works really well - no need to have a shared key pair that then needs rotating, and no need to include a public key for every possible user of the instance.

I don't know that EC2InstanceConnect will necessarily work with bottlerocket instances, but if somehow the sshd in the admin container could reference the ssh keys added by EC2InstanceConnect, that would be awesome.

**Any alternatives you've considered:**

* Using shared key pairs or per-admin key pairs

**Comment by tjkirch** [comment]
Thanks for your request!  I believe this is a duplicate of https://github.com/bottlerocket-os/bottlerocket-admin-container/issues/38, which has a PR in progress - we created it in the admin container repo because that's where Instance Connect would reach.

**Comment by willthames** [comment]
Thanks @tjkirch - I did search in this repository but hadn't thought to look there - I'll close this one as a duplicate then
