### ISSUE TITLE
bootstrap containers using ECR don't meet regex

### ISSUE THREAD

**Issue by willthames** [bottlerocket-os/bottlerocket#1642]
**Platform I'm building on:**

EKS

```
# cat /etc/os-release 
NAME=Bottlerocket
ID=bottlerocket
PRETTY_NAME="Bottlerocket OS 1.1.2"
VARIANT_ID=aws-k8s-1.20
VERSION_ID=1.1.2
BUILD_ID=e593086f
```

**What I expected to happen:**

If I reference an ECR hosted image for bootstrap container, with a valid container reference, the bootstrap container runs

```
[settings.bootstrap-containers.lifecyclehook]
source = "012345678901.dkr.ecr.us-west-2.amazonaws.com/namespace/bottlerocket-lifecyclehook:v0.1"
```

The source is correct on the host (from /etc/bootstrap-containers/lifecyclehook.env )
```
CTR_SOURCE=012345678901.dkr.ecr.us-west-2.amazonaws.com/namespace/bottlerocket-lifecyclehook:v0.1
```

**What actually happened:**

The conversion to ARN seems to happen before the validation:
```
Jul 01 07:02:26 ip-172-18-12-121.us-west-2.compute.internal host-ctr[1614]: time="2021-07-01T07:02:26Z" level=info msg="pulling with Amazon ECR Resolver" ref="ecr.aws/arn:aws:ecr:us-west-2:012345678901:repository/namespace/bottlerocket-lifecyclehook:v0.1"
Jul 01 07:02:26 ip-172-18-12-121.us-west-2.compute.internal host-ctr[1614]: time="2021-07-01T07:02:26Z" level=warning msg="Failed while calling BatchGetImage" error="InvalidParameterException: Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''" ref="ecr.aws/arn:aws:ecr:us-west-2:012345678901:repository/namespace/bottlerocket-lifecyclehook:v0.1"
Jul 01 07:02:26 ip-172-18-12-121.us-west-2.compute.internal host-ctr[1614]: time="2021-07-01T07:02:26Z" level=warning msg="failed to pull image. waiting 8.735s before retrying..." error="failed to resolve reference \"ecr.aws/arn:aws:ecr:us-west-2:012345678901:repository/namespace/bottlerocket-lifecyclehook:v0.1\": InvalidParameterException: Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''"
```

**How to reproduce the problem:**

Use an ECR image with bootstrap containers, as far as I can tell

**Comment by arnaldo2792** [comment]
Hi @willthames, thanks for bringing this to our attention. It looks like the exception is coming from the [Amazon ECR Containerd Resolver](https://github.com/awslabs/amazon-ecr-containerd-resolver/blob/ec50b15a323d701f8285baf808a18475a4c95404/ecr/resolver.go#L165). Apparently, the repository that you are referencing has a valid name, but it seems like the ECR client in the ECR resolver doesn't like it. 

Could you please share a little more detail about what special characters are present in the repository's name?

**Comment by willthames** [comment]
Oh wait - I accidentally capitalized the repository namespace (which I then redacted while writing the bug report) - sorry about that!

Thanks @arnaldo2792 - probably not really a bug.
