### ISSUE TITLE
resolv.conf search invalid

### ISSUE THREAD

**Issue by hypnoce** [bottlerocket-os/bottlerocket#1645]
**Image I'm using:**
eks-1.20-1.1.2 in AWS

**What I expected to happen:**
I expect the search domains in resolv.conf to be space separated.

**What actually happened:**
The search domains are comma separated which makes them invalid.

In the code that parses the lease file from wicked, each value is being edited to remove spaces.
https://github.com/bottlerocket-os/bottlerocket/blob/036ced8e6a67d7c52b63c35d5193e5fc2e70e777/sources/api/netdog/src/main.rs#L264
The problem is that if the value in LeaseInfo.dns_search is itself a string, it will not be parsed as array by envy but will still be edited to have commas.
For instance, the DNSSEARCH entry in the lease file has valuie
```
DNSSEARCH='domain1 domain2'
```
Before Envy, netdog will make it
```
DNSSEARCH='domain1,domain2'
```

This will result in a resolv.conf file having
```
search domain1,domain2
```
which is invalid
**How to reproduce the problem:**
Add DHCP option set in the vpc used by a bottlerocket ec2 instance

**Comment by tjkirch** [comment]
Thanks for the well-researched issue and PR!  I'm taking a look now so I can review the PR.
