### ISSUE TITLE
Add a primary subnet ID label to the node

### ISSUE THREAD

**Issue by stevehipwell** [bottlerocket-os/bottlerocket#1647]
**What I'd like:**
The Kubernetes node to be given a label containing the primary ENI subnet ID.

When using the aws-vpc-cni in custom networking mode in a VPC with the AWS recommended public/private subnet split there is no suitable default node label to support using a different secondary subnet per public/private split (the docs have a manual action here). If the node is labelled with the primary ENI subnet ID we can use this to make sure that the secondary subnets are separated by public/private subnets. We currently do this with userdata on the official AWS AMI with the following shell script populating a node label.

```shell
ec2_meta_token="$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")"
instance_mac="$(curl -s -H "X-aws-ec2-metadata-token: $${ec2_meta_token}" "http://169.254.169.254/latest/meta-data/mac")"
primary_subnet_id="$(curl -s -H "X-aws-ec2-metadata-token: $${ec2_meta_token}" "http://169.254.169.254/latest/meta-data/network/interfaces/macs/$${instance_mac}/subnet-id")"
```

**Any alternatives you've considered:**
Node labels could support nested metadata queries as dynamic runtime placeholders to achieve this.

**Comment by zmrow** [comment]
:thinking: I'm thinking this could be accomplished via bootstrap container using very similar (if not the same) code you have above, but I haven't been able to try it yet.

If you beat me to it, check out the [bootstrap container docs](https://github.com/bottlerocket-os/bottlerocket/tree/328b50aa489bd6c7d386ea7ad0790ec39d2a9ca9/sources/api/bootstrap-containers) for more info on how to use them.

**Comment by stevehipwell** [comment]
Thanks @zmrow that's good point, can the bootstrap container modify the TOML config or would you be expecting to set an environment variable? I've also opened an [issue](https://github.com/aws/amazon-vpc-cni-k8s/issues/1528) on the aws-vpc-cni as native support for this pattern would be the best solution.

**Comment by zmrow** [comment]
My thought is that the bootstrap container could use `apiclient` directly to set node labels.  See the [settings.kubernetes.node-labels](https://github.com/bottlerocket-os/bottlerocket#kubernetes-settings) section of the docs.

In the bootstrap container, the `apiclient` call would look something like:
```
apiclient set 'kubernetes.node-labels.mylabel=foo'
```

**Comment by zmrow** [comment]
@stevehipwell I had a little bit of extra time to poke at this and I'm able to set a node label with a bootstrap container.

**Disclaimer: this is _very_ scrappy code, it's probably best to just use this as an example :)**

Given a bootstrap container called `node-label` with the following configuration:
```
[settings.bootstrap-containers.node-label]
source = <SOURCE>
mode = "always"
essential = false
```

`SOURCE` is the location (in ECR in my case) of an image with the following definition:
```
FROM alpine
RUN apk add bash curl
ADD set-node-label ./
RUN chmod +x ./set-node-label
ENTRYPOINT ["sh", "set-node-label"]
```

And `set-node-label` is the following script - largely using the code you included above:
```
#!/usr/bin/env bash
set -ex -o pipefail

ec2_meta_token="$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")"

instance_mac="$(curl -s -H "X-aws-ec2-metadata-token: ${ec2_meta_token}" "http://169.254.169.254/latest/meta-data/mac")"

primary_subnet_id="$(curl -s -H "X-aws-ec2-metadata-token: ${ec2_meta_token}" "http://169.254.169.254/latest/meta-data/network/interfaces/macs/${instance_mac}/subnet-id")"

apiclient set kubernetes.node-labels.mylabel="${primary_subnet_id}"
```

A similar request was made in [this discussion](https://github.com/bottlerocket-os/bottlerocket/discussions/1343#discussioncomment-399770), see another example of an `apiclient set` call there.

**Comment by zmrow** [comment]
Since we've come up with a good solution, I'll go ahead and close this.  Let us know if you have any other questions!
