### ISSUE TITLE
Add Cilium to list of excluded nics

### ISSUE THREAD

**Issue by jaxesn** [bottlerocket-os/bottlerocket#1715]
**What I'd like:**
We recently updated CAPI's image-builder to exclude cilium nics from the vsphere UI for Ubuntu and other OSs supported by the imager builder.  Without this exclude it can be confusing to users to see seemingly "random" IPs attached to their VMs.  Adding the exclude ensures users only see actual IPs on their VMs in the UI.

ref: https://github.com/kubernetes-sigs/image-builder/pull/669

**Any alternatives you've considered:**

**Comment by bcressey** [comment]
Let's try to add these excludes to the CAPV [known issues](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/docs/book/known_issues.md) as well.

**Comment by jpculp** [comment]
Code merged and CAPV known issues were updated by the author of the reference commit.
