### ISSUE TITLE
Add new instance types to max pods calculation.

### ISSUE THREAD

**Issue by jhaynes** [bottlerocket-os/bottlerocket#1720]
**What I'd like:**

AWS launched support for m6i instances. They should be added to the max pods calculations [here](https://github.com/bottlerocket-os/bottlerocket/blob/328b50aa489bd6c7d386ea7ad0790ec39d2a9ca9/packages/os/eni-max-pods). More details about m6i can be found [here](https://aws.amazon.com/ec2/instance-types/m6i/) and the corresponding PR for the AL2 based EKS AMI is [here](https://github.com/awslabs/amazon-eks-ami/pull/735/files)

**Any alternatives you've considered:**

None

**Comment by zmrow** [comment]
This was added in #1724
