### ISSUE TITLE
IPVS support

### ISSUE THREAD

**Issue by AhmadMS1988** [bottlerocket-os/bottlerocket#1726]
Hi;
I just wanted to ask if I can use kube-proxy with IPVS mode enabled?
Thanks

**Comment by WilboMo** [comment]
Hello AhmadMS1988. Thank you for reach out. To answer your question, IPVS is not supported at this time. However I will add this issue to our tracking so we can consider adding IPVS support in the future.

**Comment by paulpas** [comment]
Without IPVS support, what mechanisms exist for kube-proxy to support a true round-robin?

**Comment by stevehipwell** [comment]
IPVS is currently being worked on for EKS (https://github.com/aws/containers-roadmap/issues/142), is Bottlerocket going to align with this?

**Comment by zmrow** [comment]
Thanks for reaching out to us! Bottlerocket supports kernel 5.10 in the Kubernetes 1.21 variant (`aws-k8s-1.21`). This includes the required kernel modules to support IPVS. You should be able to leverage this once EKS enables IPVS support.

**Comment by etungsten** [comment]
Closing this issue since we have the kernel modules to support IPVS and we have confirmation that it works in a cluster.

**Comment by diranged** [comment]
@etungsten Not that it's part of this thread specifically - but it would be nice to add a few more of the reecommended IPVS modules like `ip_vs_sh`.
