### ISSUE TITLE
prairiedog build fail caused by updated argh_derive version

### ISSUE THREAD

**Issue by mello7tre** [bottlerocket-os/bottlerocket#1727]
**Platform I'm building on:**

any

**What I expected to happen:**
cargo make should complete successfully

**What actually happened:**
build fail
```
  #17 3.217 warning: build failed, waiting for other jobs to finish...
  #17 3.278 error[E0107]: this type alias takes 1 type argument but 2 type arguments were supplied
  #17 3.278    --> api/netdog/src/main.rs:94:10
  #17 3.278     |
  #17 3.278 94  | #[derive(FromArgs, PartialEq, Debug)]
  #17 3.278     |          ^^^^^^^^- help: remove this type argument
  #17 3.278     |          |
  #17 3.278     |          expected 1 type argument
  #17 3.278     |
  #17 3.278 note: type alias defined here, with 1 type parameter: `T`
  #17 3.278    --> api/netdog/src/main.rs:374:6
  #17 3.278     |
  #17 3.278 374 | type Result<T> = std::result::Result<T, error::Error>;
  #17 3.278     |      ^^^^^^ -

```

**How to reproduce the problem:**

cargo make

**Solution**
To solve problem without changing prairiedog src code just make the following change to prairiedog Cargo.toml:
add `argh_derive = "=0.1.4"` line
```
 [dependencies]
 argh = "0.1.3"
+argh_derive = "=0.1.4"
 log = "0.4"
 nix = "0.22"
 signpost = { path = "../updater/signpost" }
 snafu = "0.6"
```

this way you enforce using previous `argh_derive` version.

**Comment by tjkirch** [comment]
Hi @mello7tre, thanks for the report!

Can I ask how you're building prairiedog?  It's part of the sources workspaces, which has a Cargo.lock enforcing argh 0.1.4.  (We use argh in other places as well, so it wouldn't just be prairiedog failing, but maybe that hit first...)  If you're trying to do a cargo update in the workspace, then you'd definitely run into this issue, but we didn't think others would do that.  :)

We did [report](https://github.com/google/argh/issues/97) the issue to argh, and it's been fixed, but they haven't put out a release yet.  I'd prefer not to have the explicit dependency version listed so we can't forget to update it later, but if you have a use case we haven't thought of and need to build this without our lockfile, we could consider it.

**Comment by mello7tre** [comment]
Hi, i am building bottlerocket to include a new program `cfsignal` for https://github.com/bottlerocket-os/bottlerocket/issues/1581

First time when i built a vanilla bottlerocket i had no problem, but when i updated the Cargo.lock (cargo generate-lockfile) after having included the new program it gave me that error.
(added program do not use argh).

cargo tree showed that prairiedog was using argh = 0.1.3 but argh_derive = 0.1.5.

If you already know all this, please ignore my issue.

**Comment by tjkirch** [comment]
Ah, that makes sense. I think generate-lockfile updates dependencies from crates.io as well. It's silly, but when cargo complains about needing a lockfile update, I usually use cargo check, and just stop it when it starts building. That way it doesn't update the dependencies in the lockfile. We wouldn't want to update other programs' dependencies just to add a new one, so would you mind trying that?

**Comment by mello7tre** [comment]
sure, tomorrow i will try and let you know the result

**Comment by mello7tre** [comment]
I can confirm you that it works.
But i have find out an even simpler method, just use:
`cargo tree`

this way you do not even need to stop it.
