### ISSUE TITLE
Update CNI to 1.0+

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1745]
Update [CNI](https://github.com/containernetworking/cni/releases) and [cni-plugins](https://github.com/containernetworking/plugins/releases) to 1.0+.

A couple spots to be careful about:
* cni-plugins removed [flannel](https://github.com/flannel-io/cni-plugin), which we ship today - should we (a) stop shipping it, (b) build flannel from separate sources in the same cni-plugins package, or (c) build flannel in a new package?
* ~~[amazon-ecs-cni-plugins](https://github.com/aws/amazon-ecs-cni-plugins) and [amazon-vpc-cni-plugins](https://github.com/aws/amazon-vpc-cni-plugins) (as used by [ecs-agent](https://github.com/aws/amazon-ecs-agent)) haven't been updated in a while; are there any compatibility concerns?~~

**Comment by samuelkarp** [comment]
> amazon-ecs-cni-plugins and amazon-vpc-cni-plugins (as used by ecs-agent) haven't been updated in a while; are there any compatibility concerns?

These don't use the `cni` and `cni-plugins` packages in our packages folder.  The plugins used by the ECS agent consume the related CNI bits as libraries (and vendored Go dependencies).
