### ISSUE TITLE
Support for Graceful Node Shutdown in the Kubelet Configuration

### ISSUE THREAD

**Issue by throwanexception** [bottlerocket-os/bottlerocket#1792]
**What I'd like:**
Graceful Node Shutdown is enabled by default in Kubernetes 1.21, but it requires that you configure ShutdownGracePeriod and ShutdownGracePeriodCriticalPods within the Kubelet configuration.

It'd be excellent if we could get support for configuring it via user-data settings.

Relevant KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2000-graceful-node-shutdown
Docs: https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown

**Comment by WilboMo** [comment]
Thank you for this issue @throwanexception, we'll take a look at this.
