### ISSUE TITLE
Set rotate-server-certificates to true for kubelet

### ISSUE THREAD

**Issue by szucsitg** [bottlerocket-os/bottlerocket#1842]
**What I'd like:**
I'd like to run metrics-server with secure settings, and that would require to issue certificate signed by cluster CA for kubelet. This is triggered by the `rotate-server-certificates=true` argument passed. As Bottlerocket do not support setting such flags, currently this is impossible as far as I understand.

**Any alternatives you've considered:**
Metrics server can be run in insecure mode.

**Comment by tjkirch** [comment]
Thanks for the request!  We'll look into this feature.

**Comment by szucsitg** [comment]
thanks, @tjkirch for looking into this. testing this further I can close this, as it's already implemented, my bad for erroneously opening the issue.
Ref: https://github.com/bottlerocket-os/bottlerocket/blob/63f7ac69dc7036a1536e8e0d349f7e6a83250c78/packages/kubernetes-1.21/kubelet-config#L96

What I did not expect is that EKS control plane automatically approves the CSR to issue them.
