### ISSUE TITLE
Update docs for enter-admin-container

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1844]
When control container v0.5.3 ships (https://github.com/bottlerocket-os/bottlerocket-control-container/pull/17), we should update the Bottlerocket docs to refer to enter-admin-container (https://github.com/bottlerocket-os/bottlerocket-control-container/pull/18) where appropriate, since you won't need to separately enable the container before accessing it.

**Comment by jpculp** [comment]
Merged.
