### ISSUE TITLE
Schnauzer templates instead of pluto

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1845]
We [migrated](https://github.com/bottlerocket-os/bottlerocket/blob/47640f7b9088f7bbe9161c1d1b66eda6dbcd87e5/sources/api/migration/migrations/archived/v1.1.0/schnauzer-paws/src/main.rs) from pluto to schnauzer to generate pod-infra-container-image:
```
/// We moved from using pluto to schnauzer for generating the pause container image URL, since it
/// lets us reuse the existing region and arch settings, improving reliability and allowing for
/// testing new regions through settings overrides.
```
The same may well be true of other uses of pluto.  In addition, it would be nice to have one less tool and to standardize on templated settings through schnauzer helpers.

This could help out-of-tree build efforts since we wouldn't need a tool like pluto to be specialized or understand any variant specifics; using schnauzer helpers instead means their use is determined by included settings and their templates.

**Comment by tjkirch** [comment]
Note: this may benefit from #1585 (dependencies between settings).

**Comment by zmrow** [comment]
I'm wondering about the "debug-ability" of having these types of things in template helpers.  A service like pluto has the advantage of its output going directly to the journal.  Template helpers don't have this luxury.

**Comment by tjkirch** [comment]
> I'm wondering about the "debug-ability" of having these types of things in template helpers. A service like pluto has the advantage of its output going directly to the journal. Template helpers don't have this luxury.

If we fix: https://github.com/bottlerocket-os/bottlerocket/blob/452482ad73405b537909732ce170f4f63309ccad/sources/api/apiserver/src/server/controller.rs#L477 we should be able to get their logs.

**Comment by webern** [comment]
Closing as a historical relic that doesn't have a lot of bearing on Settings 2.0
