### ISSUE TITLE
Console access for debugging

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1846]
EC2 [added](https://aws.amazon.com/about-aws/whats-new/2021/03/introducing-ec2-serial-console/) the ability for authorized users to connect to the serial port of an instance, and other platforms could have similar features.

It'd be nice if we could use this as a connection mechanism when SSH/SSM aren't available or have failed.

**Comment by tjkirch** [comment]
Since we don't have a shell in Bottlerocket, the best idea we've had so far is to add a new admin container that would run a getty and have apiclient and the API socket available so you could `apiclient exec` into another host container, like the admin container for debugging.

**Comment by arnaldo2792** [comment]
We added support for this through the admin container.
