### ISSUE TITLE
Could use apiclient apply for default settings

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1856]
(This is more an idea than a bug.)

We added `apiclient apply` in #1391 for applying settings from a file or URL.  We could use this to apply our default settings from files rather than baking them into storewolf with `include_str`.  This would mean a bit more dynamic behavior, but adds flexibility in that we could have multiple files and potentially support different configurations based on some factor.  This might be helpful in out-of-tree builds or in merging variants, for example.

**Comment by stmcginnis** [comment]
FYI @cbgbt re: updates to settings handling.

**Comment by webern** [comment]
Closing this as a historical relic that probably doesn't fit with settings 2.0
