### ISSUE TITLE
Support cluster service IPV4 (and IPV6) similar to the EKS Optimized AMI

### ISSUE THREAD

**Issue by bryantbiggs** [bottlerocket-os/bottlerocket#1866]
**What I'd like:**
The AWS EKS Optimized AMI allows users to specify the cluster service IPV4 CIDR block which is used to derive the cluster DNS IP (looks like its the .10 address of whatever CIDR is provided) - https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L391-L406

However, currently Bottlerocket is currently using a MAC address check to flip between one of two values https://github.com/bottlerocket-os/bottlerocket/blob/3a2e65fde1f16d56d0d0e681231f7d7f0a8acb05/sources/api/pluto/src/main.rs#L48-L51

If this could be updated to more closely mimic what the EKS AMI is supporting that would be fantastic and provide a more cohesive experience (when comparing across AMI vs Bottlerocket)

**Any alternatives you've considered:**
None that I can think of

**Comment by etungsten** [comment]
Hi @bryantbiggs , Bottlerocket currently tries to discover the cluster's service IP CIDR via an EKS describe cluster call with the provided cluster-name. Then it derives the cluster DNS IP just like the EKS optimized AMI. See here:
https://github.com/bottlerocket-os/bottlerocket/blob/3a2e65fde1f16d56d0d0e681231f7d7f0a8acb05/sources/api/pluto/src/main.rs#L166-L172

If the EKS API is unreachable, then we fallback using the MAC address to determine which default DNS cluster IP to use.

Is there a case where service IPv4 CIDR needs to be separately specified that would be different from what EKS describe-cluster provides?

**Comment by webern** [comment]
For reference #1197 and #1547

**Comment by bryantbiggs** [comment]
ah perfect, thanks so much @etungsten / @webern  - apologies, for overlooking this!
