### ISSUE TITLE
hotdog: Remove need for vendored libcap

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket#1890]
Bottlerocket's hotdog package currently builds using a [vendored `libcap` library](https://github.com/bottlerocket-os/bottlerocket/blob/d2214bd9b25ade557b1417de1c438bbdce41611a/packages/hotdog/hotdog.spec#L32). We should modify our top level [libcap package](https://github.com/bottlerocket-os/bottlerocket/tree/d2214bd9b25ade557b1417de1c438bbdce41611a/packages/libcap) to place its Go modules in a cache which can then be used by hotdog during build.

**Comment by bcressey** [comment]
Hotdog was removed in #3401 which also removed the need for a vendored libcap.
