### ISSUE TITLE
Readiness probes are failing on EKS 1.21

### ISSUE THREAD

**Issue by ArchiFleKs** [bottlerocket-os/bottlerocket#1917]
**Image I'm using:** v1.5.2

**What I expected to happen:**

Readiness probes to work

**What actually happened:**

I'm running latest [`terraform-as-eks`](https://github.com/terraform-aws-modules/terraform-aws-eks) module to run EKS cluster with bottle rocket. Joining cluster works fine, most of my pods also.

Some pods have issues with readiness probes (like thanos and promtail for example):

```
Readiness probe failed: Get "http://10.50.60.178:3101/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

When launching on EKS AMI Amazon Linux 2 I do not have these issue, I'm aware of : https://github.com/bottlerocket-os/bottlerocket/issues/1628

But from my understanding the default CPU manager default to `none` now.

**How to reproduce the problem:**

Use promtail or thanos storage gateway

**Comment by ArchiFleKs** [comment]
Mostly a configuration issue on my part, will reopen if needed

**Comment by thoward27** [comment]
@ArchiFleKs apologies for pinging you so far after you closed this, but I'm facing this issue and could use a nudge in the right direction for a fix. Do you recall what you changed to get these readiness probes to work on bottlerocket?
