### ISSUE TITLE
VPC without ipv6 enabled is slow in sundog

### ISSUE THREAD

**Issue by peteristhegreat** [bottlerocket-os/bottlerocket#1952]
Related to closed issue: https://github.com/bottlerocket-os/bottlerocket/issues/1351

**Image I'm using:**
`/aws/service/bottlerocket/aws-k8s-1.19/x86_64/latest/image_id`

`bottlerocket-aws-k8s-1.19-x86_64-v1.6.0-9749af99`

`ami-0682b74d05a5c1dac`

**What I expected to happen:**
To have sundog complete in < 2 seconds

**What actually happened:**
Sundog waits around for over a minute.
```
	bash-5.0# systemd-analyze blame	
	1min 8.120s sundog.service	         #  THIS IS REALLY LONG
	     2.203s kubelet.service	
	     1.784s wicked.service	
	     1.092s settings-applier.service	
	      928ms metricdog.service	
	      765ms send-boot-success.service	
	      689ms host-containerd.service	
	      470ms dev-dm\x2d0.device	
	      384ms x86_64\x2dbottlerocket\x2dlinux\x2dgnu-sys\x2droot-usr-share-licenses.mount	
	      382ms activate-multi-user.service	
```

If I enable ipv6 on the VPC in subnet, the timing changes to:

```
bash-5.0# systemd-analyze blame
4.410s kubelet.service
2.285s settings-applier.service
2.268s host-containerd.service
2.039s wicked.service
1.922s sundog.service                # THIS IS VERY SHORT
 769ms send-boot-success.service
 441ms x86_64\x2dbottlerocket\x2dlinux\x2dgnu-sys\x2droot-usr-share-licenses.mount
 429ms ldconfig.service
 396ms early-boot-config.service
 373ms apiserver.service
```

It appears to be blocking in `get_dynamic_settings` in https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/api/sundog/src/main.rs#L226

**How to reproduce the problem:**

Run a 1.19 image of bottlerocket in a vpc without ipv6, notice how long it takes to stand up and be ready.

Enable a admin container with sheltie, go into the admin container and run `sudo sheltie` and then `systemd-analyze blame` to see the slow downs.

**Comment by etungsten** [comment]
Thanks for bringing this up. We'll definitely look into this.

**Comment by etungsten** [comment]
Hi @peteristhegreat, I'm having trouble reproducing this. I created a new EKS v1.19 IPv4 cluster in us-east-1 with `eksctl` and used the same AMI you listed for the nodes and sundog was finishing under 2 seconds:
```
bash-5.0# systemd-analyze blame
7.279s kubelet.service                                                            
2.445s host-containerd.service                                                    
1.895s settings-applier.service                                                   
1.531s sundog.service                                                             
1.320s wicked.service                                                             
1.035s send-boot-success.service                                                  
...
```

Can you share little bit about your cluster VPC set up? Or your instance user-data? Another thing that would help us track this down is to try running the following commands via the root shell and see which one is taking the longest. There are what sundog is calling in `get_dynamic_settings` to generate setting values:
```
bash-5.0# pluto node-ip
"192.168.38.127"

bash-5.0# schnauzer settings.kubernetes.pod-infra-container-image
"602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause-amd64:3.1"

bash-5.0# pluto cluster-dns-ip
"10.100.0.10"

bash-5.0# pluto max-pods
29

bash-5.0# netdog generate-hostname
"ip-192-168-38-127.ec2.internal"

bash-5.0# bork seed
738

bash-5.0# shibaken
23:37:42 [INFO] shibaken started
23:37:42 [INFO] Connecting to IMDS
23:37:42 [INFO] Fetching list of available public keys from IMDS
23:37:42 [INFO] Received meta-data/public-keys
23:37:42 [INFO] Generating targets to fetch text of available public keys
23:37:42 [INFO] Fetching public key (1/1)
23:37:42 [INFO] Received meta-data/public-keys/0/openssh-key
23:37:42 [INFO] Generating user-data
23:37:42 [INFO] Encoding user-data
23:37:42 [INFO] Outputting base64-encoded user-data
...

```

**Comment by peteristhegreat** [comment]
Well, apparently this is not as reproducible as we thought at first...  We tried to reproduce again this morning 2 or 3 ways and could not.

As far as we can tell from our end, it must have been some other config error that’s not reproducible for us now.

😕 

Thank you for looking at.  Thank you for the additional insights in how `sundog.service` does some of its internals.  If we see this in the wild again, I'll capture more of our setup.  

The test may have been complicated with it being our first node that we were exposing a public ip and enabling the admin container on it.
