### ISSUE TITLE
Does this project deregister nodes from load balancers?

### ISSUE THREAD

**Issue by tjs-intel** [bottlerocket-os/bottlerocket#1954]
**What I'd like:**
I'm considering adding this to my EKS deployment, but I found a flaw in another project that drains nodes before termination (`aws-node-termination-handler`) where nodes weren't properly detached from load balancers before being terminated which resulted in failed requests. Does this project cover LB deregistration? I cant find the label `node.kubernetes.io/exclude-from-external-load-balancers` anywhere in this project.

**Any alternatives you've considered:**
I use a Cloudformation Stack for my ASGs, with a daemonset in the cluster that signals the stack. I might be able to get away with updating the Bottlerocket AMI every week and just let the `aws-node-termination-handler` deregister nodes (a recently added feature).

**Comment by etungsten** [comment]
Hi @tjs-intel , Bottlerocket does not cover load balancer deregistration. It is however possible to apply the `node.kubernetes.io/exclude-from-external-load-balancers` label to your Bottlerocket nodes via configuring [the `settings.kubernetes.node-labels` setting](https://github.com/bottlerocket-os/bottlerocket#kubernetes-settings). You can do this to multiple instances at once via [SSM RunCommand](https://docs.aws.amazon.com/systems-manager/latest/userguide/run-command.html) by invoking [`apiclient set`](https://github.com/bottlerocket-os/bottlerocket#using-the-api-client) to configure the setting. In the future, we plan to make this easier by creating a [Bottlerocket settings K8s operator](https://github.com/bottlerocket-os/bottlerocket/issues/873) that applies settings across Bottlerocket nodes in your K8s cluster.

**Comment by tjs-intel** [comment]
@etungsten I'm sorry, this issue is meant for https://github.com/bottlerocket-os/bottlerocket-update-operator. I will move it over to there. That project links to documentation here which is how I ended up opening this issue.
