### ISSUE TITLE
Update host containers for 1.7.0

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket#1967]
We should at minimum build the host containers against the latest version of Amazon Linux 2:
* https://github.com/bottlerocket-os/bottlerocket-admin-container
* https://github.com/bottlerocket-os/bottlerocket-control-container

It is probably a good idea to check that we have the latest versions of `bash`, `musl`, and `ssm` built within those containers.

**Comment by jpculp** [comment]
Merged.
