### ISSUE TITLE
replace rusoto with aws rust sdk

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#1968]
Issue #1960 might be blocked by our use of rusoto in pubsys. See my comment in that issue for the specifics. Regardless, we should move to the AWS SDK.

**Comment by kdaula** [comment]
Moving to 1.10.0 for addressing Pubsys

**Comment by markusboehme** [comment]
One more thing that this migration will be helpful for: Running Pubsys on EC2 instances with IMDS v1 disabled. Unfortunately, Rusoto doesn't support the two-step process (fetch token, query IMDS) of IMDS v2.
