### ISSUE TITLE
slow image pulls when pulling same image multiple times

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#2018]
Some Bottlerocket users have seen very slow image pulls when the same image pull is being used in many containers. For example, if many pods are created using the same container, it seems like containerd is pulling that container many times in parallel instead of deduplicating the request.

It sounds like the same behavior described in this issue: https://github.com/containerd/containerd/issues/4937
There is an active PR: https://github.com/containerd/containerd/pull/6702

We should make this fix available to Bottlerocket users.

**Comment by cbgbt** [comment]
This is resolved in the latest Bottlerocket release, [v1.8.0](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.8.0).
