### ISSUE TITLE
EKS - unable to inject values for [settings.kubernetes] with managed node group

### ISSUE THREAD

**Issue by travisnburton** [bottlerocket-os/bottlerocket#2024]
When attempting to inject values for [settings.kubernetes] into user-data for a managed node group (MNG), the values injected by the EKS managed service are invalidated and the nodes are unable to join the MNG.

This is because EKS needs to write values in the [settings.kubernetes] table in order to attach nodes to the cluster, and TOML does not support merging tables - https://github.com/toml-lang/toml/issues/697 

An example of settings that need to be modified are:
```txt
[settings.kubernetes]
container-log-max-size = "20Mi"
container-log-max-files = "2"
```

**Comment by webern** [comment]
Thank you for bringing this issue to our attention. We will take a look at this.

**Comment by mmerkes** [comment]
Hi from the EKS MNG team!

From what I can tell, EKS MNG does support your scenario. Can you provide some more information on why you believe the duplicate keys are causing your failure? We have custom logic that merges the TOML that handles merging tables, and I've unit tested the exact scenario that you mention. It could be that something else is going on.

A few questions:

1. Are you able to create the nodegroup and you're getting a node creation failure or are you getting an error that we weren't able to merge your table?
2. Can you share the resultant launch template userdata that terraform generates?
3. If you can nab the userdata for the launch template that EKS MNG generates, that would be helpful too.

When I have a chance, I'll see if I can reproduce your case in the API or not.

**Comment by travisnburton** [comment]
The nodegroup and and launch template are created successfully.  The node fails to join the node group.

Below are different examples of userdata which prevent a node from joining the node group (pulled from launch template):
```txt
# extra args added
[settings.kubernetes]
"container-log-max-size" = "20Mi"
"container-log-max-files" = "2"
```
```txt
# extra args added
settings.kubernetes.container-log-max-size = "20Mi"
settings.kubernetes.container-log-max-files = "2"
```

When adding either of the 2 examples above to userdata of a working launch template, the template is modified successfully but the following error is returned:
`* : NodeCreationFailure: Couldn't proceed with upgrade process as new nodes are not joining node group default-2022032416591876530000000e`

**Comment by mmerkes** [comment]
Looks like the issue is that you're using [a string rather than an integer for container-log-max-files](https://github.com/bottlerocket-os/bottlerocket/blob/319bd8f9a155f3e5a2290cbc35ab1c5866cc3efa/sources/models/src/lib.rs#L198). If you remove the parentheses, it should work as expected.

We should consider updating the README and any place where we document the settings available to include the types.

**Comment by travisnburton** [comment]
Confirmed - thank you!  

2 questions remain:

1. TOML merging logic - is there a preferred format? `[settings.kubernetes]` or `settings.kubernetes.foo = `

2. Is this a definitive list of settings applied when using EKS MNG?  https://github.com/bottlerocket-os/bottlerocket/tree/develop/sources/models/src/aws-k8s-1.22

**Comment by mmerkes** [comment]
There is no preference on format. If it's valid TOML, it should work.

```
[settings.kubernetes]
foo = "bar"
```
Is equivalent to:
```
settings.kubernetes.foo = "bar"
```

We also make no promises on how we'll format the final document. Currently, we use the former, but we have a change rolling out that will use the latter, and there's no guarantee that won't change, but it shouldn't matter.

As for the list of settings, EKS MNG tries to know as little about Bottlerocket as possible. We'll add enough data to let the nodes join the cluster and anything else that's configured via the API (like taints and labels), and nothing else. We don't validate the userdata for you. We just take your userdata and merge it with our userdata. From there, it's in Bottlerocket's hands.

**Comment by mmerkes** [comment]
This issue can be resolved.

**Comment by riupie** [comment]
> There is no preference on format. If it's valid TOML, it should work.
> 
> ```
> [settings.kubernetes]
> foo = "bar"
> ```
> 
> Is equivalent to:
> 
> ```
> settings.kubernetes.foo = "bar"
> ```
> 
> We also make no promises on how we'll format the final document. Currently, we use the former, but we have a change rolling out that will use the latter, and there's no guarantee that won't change, but it shouldn't matter.
> 
> As for the list of settings, EKS MNG tries to know as little about Bottlerocket as possible. We'll add enough data to let the nodes join the cluster and anything else that's configured via the API (like taints and labels), and nothing else. We don't validate the userdata for you. We just take your userdata and merge it with our userdata. From there, it's in Bottlerocket's hands.

Hi,
I have similiar issue and already try both approach:

With this approach, I got error when creating node group since it has 2 `[settings.kubernetes]`, seems like bottlerocket/MNG not merge it.

```
[settings.kubernetes]
container-log-max-size = "100Mi"

```


Using 2nd approach, I able to create the MNG but it is not reflected on the kubelet configuration
```
"settings.kubernetes.container-log-max-size" = "100Mi"
```

**Comment by piyush-jena** [comment]
Hi @riupie!

I am able to copy paste this toml in the launch template and I can see the node joining the cluster and it is creating the correct settings.

```
[settings.kubernetes]
api-server = "xxxxx"
cluster-name = "yyyyy"
cluster-certificate = "zzzzz"
container-log-max-size = "100Mi"
container-log-max-files = 2
```

Can you please elaborate your process?

**Comment by riupie** [comment]
Hi @piyush-jena ,
So, I use terraform EKS module to manage the EKS. When I execute terraform plan, on `user_data` value generate this:

```
[settings.kubernetes]
"cluster-name" = "xxxx"
"api-server" = "xx"
"cluster-certificate" ="xxx"
[settings]
motd = "Bottlerocket CIS"

[settings.bootstrap-containers.bootstrap]
     
source = "xxxx"
mode = "always"

[settings.kernel]
lockdown = "integrity"

[settings.kernel.modules.udf]
allowed = false
      
[settings.kernel.modules.sctp]
allowed = false

[settings.kernel.sysctl]
some valye

[settings.kubernetes]
"container-log-max-size" = "100Mi"
"container-log-max-files" = 5
```

There are 2 [settings.kubernetes] instead of merge the table, actually im not sure if this is issue on bottlerocket or terraform module and who should handle the merging part. On my EKS module, define this value:

```
      enable_bootstrap_user_data = true
      bootstrap_extra_args       = <<-EOT
        [settings.kubernetes]
        "container-log-max-size" = "100Mi"
        "container-log-max-files" = 5
        EOT
```

when i apply the terraform I got this error:

```
Error: waiting for EKS Node Group (xxxxx) create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: : Ec2LaunchTemplateInvalidConfiguration: User data was not a TOML format that could be processed.
```

**Comment by arnaldo2792** [comment]
Hey @riupie, sorry for the late reply. If you see that user data in your launch template the problem is in the terraform module and how it merges the configs. I tried that config in a toml validator and I got this error:

```
Cannot redefine existing key 'settings,kubernetes'.
```

So that's technically not valid TOML.
