### ISSUE TITLE
Populate /etc/hosts with custom DNS mapping entries

### ISSUE THREAD

**Issue by johnsonjnpan** [bottlerocket-os/bottlerocket#2045]
**What I'd like:**
Add custom static DNS mapping entries for `/etc/hosts` through settings.

Our project requires us to support resolving certain DNS domain(s) to IP(s) even when the host is disconnected from the internet.
I wonder if BottleRocket can provide some way to set/add such DNS mappings reliably (can sustain a reboot).

E.g. By running `apiclient set settings.dns.mappings=["10.0.0.2 somehost.com"]`  to set it into `/etc/hosts`

**Any alternatives you've considered:**
* We tried adding some DNS mappings inside `/etc/hosts` through admin container. However, we found those changes are lost after we reboot the host. (Due to /etc mapped as tmpfs mount)

**Comment by jpculp** [comment]
Hi @johnsonjnpan! Thanks for bringing this to our attention. We'll take a look at what our options are.

**Comment by cbgbt** [comment]
As an update, I'm currently working on integration of this feature.

**Comment by cbgbt** [comment]
This feature has been merged, and should be released with Bottlerocket 1.8.0.

**Comment by cbgbt** [comment]
This is resolved in the latest Bottlerocket release, [v1.8.0](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.8.0).

[Check out the documentation](https://github.com/bottlerocket-os/bottlerocket#network-settings) for more details on how to use the new setting, `settings.network.hosts`. Let us know if you have any questions!
