### ISSUE TITLE
How to override default max-pods settings in bootstrap params ?

### ISSUE THREAD

**Issue by mprzygrodzki** [bottlerocket-os/bottlerocket#2057]
I need to override default max-pods setting while using Bottlerocket K8s AMI. After adding max-pods params into custom user-data nodes are unable to join EKS cluster. Not pretty sure if i'm doing it in correct way, tried a different values but without luck. Can someone point me what i'm doing wrong ?

```
      bootstrap_extra_args = <<-EOT
      [settings.kubernetes.max-pods]
      max-pods = 65
      EOT
```      

```
      bootstrap_extra_args = <<-EOT
      [settings.kubernetes]
      max-pods = 65
      EOT
```

**Comment by jpculp** [comment]
Hi @mprzygrodzki, thanks for reaching out. Are you trying to do this with a managed node group and eksctl? If so, can you provide me the version of eksctl you're using?

**Comment by mprzygrodzki** [comment]
Hey @jpculp - I was trying with managed node groups module for EKS. To be more precise --> https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest

Part of MNG node group config. Without adding max pods node groups is created correctly and nodes can join cluster without any issues.

```
    "monitoring" = {
      name            = "${var.eks_cluster_name}-app-mng"
      ami_id          = data.aws_ami.eks_default_bottlerocket.image_id
      ami_type        = "BOTTLEROCKET_x86_64"
      platform        = "bottlerocket"
      instance_types  = ["r5.large", "r5a.large", "r5ad.large", "r5n.large", "r5b.large", "r5dn.large"]
      subnet_ids      = [data.aws_subnet.private_per_az["${var.region}a"].id]
      iam_role_name   = "${var.eks_cluster_name}-app-mng"
      bootstrap_extra_args = <<-EOT
      [settings.kernel]
      lockdown = "integrity"
      [settings.kubernetes]
      max-pods = 65  
      EOT
      min_size     = 1
      max_size     = 2
      desired_size = 1     
    }
```

**Comment by etungsten** [comment]
Hi @mprzygrodzki, can you provide the system log for the Bottlerocket instance that gets launched? You can fetch them with the AWS-CLI like this: `aws ec2 get-console-output --instance-id <INSTANCE_ID> --latest  --output text` or through the EC2 console.

If possible, can you also show what the merged TOML instance userdata look like for one of these nodes? You can get that via the AWS-CLI like this: `aws ec2 describe-instance-attribute --instance-id <INSTANCE_ID>  --attribute userData --query 'UserData.Value' --output text | base64 -d`. You can also find it in the instance settings via the EC2 console. Please remove any sensitive information before sharing.

**Comment by arnaldo2792** [comment]
Hey @mprzygrodzki , along with ^, could you please provide the Bottlerocket version that you are trying to use? Thanks! :+1:

**Comment by cbgbt** [comment]
Hey @mprzygrodzki, any chance you have a moment to provide some additional information here? Thanks!

**Comment by bcressey** [comment]
My guess is that this is because the user-data ends up with two `[settings.kubernetes]` tables, and the second one (with `max-pods`) clobbers the first, which would have `apiserver` and other critical values.

**Comment by bcressey** [comment]
If [this](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/be86c0b898c34943e898e2ecd4994bb7904663ff/examples/user_data/templates/bottlerocket_custom.tpl) is the template that's being extended, you could potentially avoid the problem by using a snippet like this for `bootstrap_extra_args`:
```
# relies on still being inside [settings.kubernetes] as the last open table,
# so the setting is at the right place when the files are concatenated
max-pods = 65

# OK to start a new table now
[settings.kernel]
lockdown = "integrity"
```

**Comment by kdaula** [comment]
Please reopen if this is still an issue.
