### ISSUE TITLE
Add support for docker registry using TLS client certificates

### ISSUE THREAD

**Issue by marinator86** [bottlerocket-os/bottlerocket#2072]
**What I'd like:**
We need to connect to a private docker registry, and that forces any client to present a certificate during TLS handshake.

Docker supports these client certificates by configuration. You need to copy cert + key to `/etc/docker/certs.d/...`. In non-bottlerocket instances, we copy those certs using user data:
````
    write_files:
      - path:         "/etc/docker/certs.d/my-private-registry.com/client.cert"
        permissions:  "0644"
        owner:        "root:root"
        encoding:     "b64"
        content:      ${filebase64("/path/to/clcerts.crt")}
      - path:         "/etc/docker/certs.d/my-private-registry.com/client.key"
        permissions:  "0644"
        owner:        "root:root"
        encoding:     "b64"
        content:      ${filebase64("/path/to/my.key")}
````

We also need to provision credentials for the registry, we're currently doing this with a secret and a k8s imagePullSecret reference in the kubernetes deployment resource. Is this approach also supported by bottlerocket?

**Any alternatives you've considered:**

- Bootstrap containers: We can hand over user-data (i.e. a write_files directive in our case) in the settings of the BC, but I'm not sure if cloud init executions inside that  BC have a permanent effect on the system..

**Comment by zmrow** [comment]
Hi there!  Regarding client certificates, you can provision custom certs via API settings.  This is described in the [Custom CA certificates](https://github.com/bottlerocket-os/bottlerocket#custom-ca-certificates-settings) docs.  If you don't want to use user data for this - you can use a bootstrap container (also described in the linked section).

In terms of registry credentials, you can set these via settings as well.  Check out the [Container image registry settings](https://github.com/bottlerocket-os/bottlerocket#container-image-registry-settings) docs.

**Comment by somnusfish** [comment]
We haven't heard back from you for a while so I would assume this issue could be resolved. Please feel free to open this issue or reopen a new issue if you still have any questions/concerns.
