### ISSUE TITLE
Mounting "prepared" /dev/xvdb disk on 1.7.2 results in "exec format error"

### ISSUE THREAD

**Issue by awoimbee** [bottlerocket-os/bottlerocket#2115]
I understand that the procedure I'm using is far from standard, but I don't see why it would not work and more specifically, what made it stop working in there: https://github.com/bottlerocket-os/bottlerocket/compare/v1.7.1...v1.7.2.

**Image I'm using:**

I'm using `Bottlerocket OS 1.7.2 (aws-k8s-1.22-nvidia)`.
`Bottlerocket OS 1.7.1 (aws-k8s-1.22-nvidia)` is not impacted by this issue.

**What I expected to happen:**

Follow [this procedure](https://github.com/bottlerocket-os/bottlerocket/discussions/2023) and get a running system with container images already present.

**What actually happened:**

`exec format error`.

1. I tried my usual script: it starts an instance, then uses the admin container to pull some images, and finally it snapshots `/dev/xvdb`.
When booting a new instance with this snapshot, everything works but the efs-csi driver:
    | container | error log |
    | -- | -- |
    | `csi-driver-registrar` | `exec /csi-node-driver-registrar: exec format error` |
    | `liveness-probe` | `exec /livenessprobe: exec format error` |

2. I then tried something simpler: start an instance, snapshot `/dev/xvdb`, boot a new instance with this snapshot.
    This new instance cannot even boot, the EC2 system log shows:
    ```
    [...]
    [  OK  ] Finished Send boot success.
    [   13.642455] cgroup: cgroup: disabling cgroup2 socket matching due to net_prio or net_cls activation
    [   12.884318] host-ctr[2151]: exec /bin/bash: exec format error
    [   12.902112] host-ctr[2152]: exec /usr/sbin/start_control_ssm.sh: exec format error
    [   13.080797] host-ctr[2151]: time="2022-04-29T09:18:33Z" level=fatal msg="Container admin exited with non-zero status"
    [   13.082483] host-ctr[2152]: time="2022-04-29T09:18:33Z" level=fatal msg="Container control exited with non-zero status"
    [  OK  ] Started Kubernetes systemd probe.
    [  OK  ] Started Kubelet.
    [  OK  ] Started Start NVIDIA kubernetes device plugin.
    [  OK  ] Reached target Multi-User System.
    [   15.300321] nvidia-device-plugin[2370]: 2022/04/29 09:18:35 Loading NVML
    [   16.083454] nvidia-device-plugin[2370]: 2022/04/29 09:18:36 Starting FS watcher.
    [   16.084865] nvidia-device-plugin[2370]: 2022/04/29 09:18:36 Starting OS watcher.
    [   16.086306] nvidia-device-plugin[2370]: 2022/04/29 09:18:36 Retreiving plugins.
    [   16.096281] nvidia-device-plugin[2370]: 2022/04/29 09:18:36 Starting GRPC server for 'nvidia.com/gpu'
    [   16.100935] nvidia-device-plugin[2370]: 2022/04/29 09:18:36 Starting to serve 'nvidia.com/gpu' on /var/lib/kubelet/device-plugins/nvidia-gpu.sock
    [   16.103851] nvidia-device-plugin[2370]: 2022/04/29 09:18:36 Registered device plugin for 'nvidia.com/gpu' with Kubelet
    [   58.463398] host-ctr[14183]: exec /bin/bash: exec format error
    [   58.484168] host-ctr[14184]: exec /usr/sbin/start_control_ssm.sh: exec format error
    [   58.514348] host-ctr[14183]: time="2022-04-29T09:19:18Z" level=fatal msg="Container admin exited with non-zero status"
    [   58.516574] host-ctr[14184]: time="2022-04-29T09:19:18Z" level=fatal msg="Container control exited with non-zero status"
    [...]
    ```

**How to reproduce the problem:**

As specified above, start an instance, snapshot /dev/xvdb, boot another instance using this snapshot. Bottlerocket 1.7.1 works perfectly while 1.7.2 will return `exec format error`.

**Comment by bcressey** [comment]
The "exec format" error is something I've only seen when there's an architecture mismatch.

Any chance you're pulling the images and populating xvdb on an x86_64 instance, and using the snapshot on an arm64 instance? Or vice versa.

**Comment by awoimbee** [comment]
I know right, it's a weird error to have. I'm building and running these images on g5 or g4dn instances (both x64) (not using g5g). I would like to add more context to this issue but I can't ATM.

**Comment by bcressey** [comment]
Are you using EBS encryption for the resulting snapshot? There can be problems when going from an unencrypted volume to an encrypted snapshot, in the specific case of all zero blocks.

While trying to repro this with the global EBS encryption setting turned on, I managed to create a snapshot with a zero length copy of `start_admin_sshd.sh` which (predictably) caused the admin container to fail to start.

That's likely the result of not running `sync` or taking other steps to force the writes to disk before taking the EBS snapshot. To rule this out, you could also try taking a snapshot of the volume while the instance is stopped.

**Comment by awoimbee** [comment]
> That's likely the result of not running sync or taking other steps to force the writes to disk before taking the EBS snapshot. To rule this out, you could also try taking a snapshot of the volume while the instance is stopped.

This was it, thanks ! I hope you didn't loose too much time on this one. I still don't understand why this wasn't an issue on v1.7.1 but whatever.

In my script it translates to:
```bash
  print_status "Get volume ID we need to snapshot"
  VOL_ID=$(my_aws ec2 describe-instances \
    --instance-ids "$EC2_INSTANCE" \
    --query 'Reservations[*].Instances[*].BlockDeviceMappings' \
    | jq -r '.[][][] | select(.DeviceName == "/dev/xvdb") | .Ebs.VolumeId' \
  )

  my_aws ec2 stop-instances --instance-ids "$EC2_INSTANCE" | cat
  printf "Waiting for instance to stop"
  until my_aws ec2 describe-instances --instance-ids "$EC2_INSTANCE" --query 'Reservations[0].Instances[0].State.Name' | grep 'stopped'; do
    printf "."
    sleep 2s
  done
  printf "\n"

  print_status "Snapshot volume $VOL_ID..."
  SNAP_ID=$(my_aws ec2 create-snapshot \
    --volume-id "$VOL_ID" \
    --description "Baked bottlerocket data volume for GPU  instances" \
    --tag-specifications="ResourceType=snapshot,Tags=[{Key=uid,Value=lol}]" \
    --output json \
    | jq -r '.SnapshotId' \
  )
```
