### ISSUE TITLE
Support for PodPidsLimit Kubelet option

### ISSUE THREAD

**Issue by scoof** [bottlerocket-os/bottlerocket#2130]
**What I'd like:** Kubelet support for PID limits
Please support PodPidsLimit option in Kubelet config

**Any alternatives you've considered:** None

**Comment by gthao313** [comment]
Hi @scoof Thanks for opening this issue. Bottlerocket team will research on this and reach back to you soon. Thanks.

**Comment by gthao313** [comment]
Hi @scoof  We will support it on our next release. Thanks : )
