### ISSUE TITLE
pubsys: cargo make ami should "just work"

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#2135]
**What I'd like:**

I have a aws profile with a default region, but when I use `cargo make ami` I get `Failed to build AMI: Infra.toml is missing aws.regions`. For the simple workflow `cargo make build && cargo make ami`, pubsys should be savvy and use my default region without needing me to create this file:

```toml
[aws]
regions = ["us-west-2"]
```

**Comment by ecpullen** [comment]
You can use `-e PUBLISH_REGIONS="us-west-2"` as a workaround.

**Comment by webern** [comment]
I didn't realize that, but I wonder if it would be possible to use my default region in the absence of that environment variable argument.

**Comment by mchaker** [comment]
Closing this issue as per https://github.com/bottlerocket-os/bottlerocket/pull/2287#issuecomment-1197039705
