### ISSUE TITLE
Add smartpqi driver to Linux kernel

### ISSUE THREAD

**Issue by craigerl** [bottlerocket-os/bottlerocket#2160]
I see the broadcom megaraid driver was recently added.  Since we're looking at booting on real hardware
could we also add "smartpqi" in order to boot on all HPE hardware host bus adapters?

I'm suggesting we append 

**CONFIG_SCSI_SMARTPQI=y**

to

https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kernel-5.10/config-bottlerocket

(@etungsten)

thanks,
-craig

**Comment by webern** [comment]
Thank you, our kernel/hardware folks will take a look at this request.
