### ISSUE TITLE
Many packages require newer build tools in the SDK

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket#2175]
**What I'd like:** To update dbus-broker to v31 or greater.

dbus-broker requires a newer build of meson to be included in our SDK. Currently, the SDK [uses F35 as a base](https://github.com/bottlerocket-os/bottlerocket-sdk/blob/c726347768074d39d499c8e5b235a174756c1438/Dockerfile#L1), which doesn't include a recent enough build, so we would need to update that.

Note that when we do update dbus-broker, we also need to change our systemd unit to account for the following changes:
* https://github.com/bus1/dbus-broker/commit/28af5ac996c94922fc49660e0efa955f57575187
* https://github.com/bus1/dbus-broker/commit/fa19773b27775ffa81c248de1ce4b8febb526adf

**Any alternatives you've considered:** N/A.

**Comment by jpculp** [comment]
I think another benefit of jumping to F36 is openssl 3.0.x is the default.

**Comment by cbgbt** [comment]
It turns out that we similarly need a newer meson for the newest libglib (2.73), which would also necessitate this move.
