### ISSUE TITLE
use `bottlerocket-variant` crate to set up logdog conf for variants

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket#2193]
> we could potentially use our new `bottlerocket-variant` crate to set up a ladder of different configs, ordered from most to least specific, and pick the first one that existed.
>
> That would let us avoid at least this one symlink chore.
>
_Originally posted by @bcressey in https://github.com/bottlerocket-os/bottlerocket/pull/2140#discussion_r891316822_

**Comment by webern** [comment]
I'm going to close this in favor of #3784
