### ISSUE TITLE
Support static addressing via `net.toml`

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#2204]
- Depends on #2214 

**What I'd like:**
I would like the ability to set up a static IP for a network interface.

This means we will need to be able to set the following at the least

- IPv4/6 IP
- gateway
- nameservers
- destination IP

**Comment by rickymulder** [comment]
Is there an opportunity to backport to the `1.9.x` branch?
I can file a new bug if needed, but to explain the short version is:

Attempting to spin up a version `1.21` eks cluster using bottlerocket without the ENI config using tunneling mode.  When creating pods on the host network, they inherit the hosts `/etc/resolv.conf` and therefore cannot do cluster dns resolution.  The routes already exist as when attempting to dig @ the `kube-dns` service IP resolution completes, but not all applications provide options to override the hosts `/etc/resolv.conf` or set custom NS.  Theoretically setting the hosts nameservers to the VPC DNS resolver with a backup as the `kube-dns` service IP would resolve that, at least for fully qualified DNS lookups.

#2353 would solve this specific use case.

Another option would be to expose the kubelet's `--resolv-conf` flag per [official docs](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/), though that would also require a manner to write said file.
> If you don't want this, or if you want a different DNS config for pods, you can use the kubelet's --resolv-conf flag. Set this flag to "" to prevent Pods from inheriting DNS. Set it to a valid file path to specify a file other than /etc/resolv.conf for DNS inheritance.

EDIT: The route to the service network does _not_ exist.  I'm barking up the wrong tree at the moment it would seem.

**Comment by zmrow** [comment]
Hi @rickymulder !  We won't be backporting the static addressing feature, but when it's ready we'll release new versions of Bottlerocket that include the feature.

Your example seems to reference DNS settings, which should be released at the same time as the static addressing feature!

> EDIT: The route to the service network does not exist. I'm barking up the wrong tree at the moment it would seem.

^ Does this comment mean that the DNS settings _will not_ solve your issue?
