### ISSUE TITLE
Non-1.23 K8s: Deprecate dockershim.sock and use `containerd.sock` for container runtime

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket#2212]
**What I'd like:**
More K8s deployments are now containerd-aware so customers are having to do K8s manifest edits for solutions that assume containerd as the underlying runtime.

In the containerd systemd service, we will create a symlink for the containerd socket at `/run/dockershim.sock` just so other deployments that assume docker as underlying runtime can still work.

We've already done this for 1.23 variants, this issue for tracking this change for other variants.

We tried implementing this change in https://github.com/bottlerocket-os/bottlerocket/pull/2173, but decided to delay the push-out until we can give sufficient notice to existing users.

**Any alternatives you've considered:**

**Comment by stmcginnis** [comment]
Resolved by #2173.
