### ISSUE TITLE
Investigate whether or not services enter a degraded state when dbus is restarted

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket#2253]
We're tracking `runc` re-registering itself as a service in dbus automatically if dbus is restarted in #2172. 

This issue is cut to track whether or not other services enter a degraded state on dbus restarts (wicked is the most likely offender).

We can close this ticket when we are satisfied that we are aware of any other problems that arise on the system when dbus is restarted.

**Comment by stmcginnis** [comment]
@cbgbt do you know if this is still an issue after the resolution of #2172 ?
