### ISSUE TITLE
Reduce the log level of wickedd-dhcp6

### ISSUE THREAD

**Issue by MiLk** [bottlerocket-os/bottlerocket#2254]
All our bottlerocket nodes seem to be generating 34k~56k log entries per day for `wickedd-dhcp6`.
This is quite a sizable proportion of our total log volume.
I can't see what is wrong with our setup, so I was wondering if it would be possible to reduce the log level or at least make it configurable.
The current log level is configured with [`--log-level debug --debug most`](https://github.com/bottlerocket-os/bottlerocket/blob/b539d40dc9fe20257a6867723643dce152a64645/packages/wicked/wickedd-dhcp6.service#L11).

**What I'd like:**
Be able to reduce the log level of `wickedd-dhcp6`.

**Any alternatives you've considered:**

* Using a bootstrap container, update the systemd service file, and restart the service. 
  But I couldn't figure out how to interact with `systemctl` from the bootstrap container.

* Fix whatever is wrong with our setup, but I don't have any idea of how to proceed.
  One thing I can think of is that our VPC has IPv6 enabled and our nodes are starting in a subnet with `assignIpv6AddressOnCreation` enabled.
  I believe that even if the nodes have an IPv6, as the cluster uses IPv4, there is no point assigning IPv6 addresses, and it could be disabled, but I don't know if it would help.
  I'm attaching log files of 2 nodes, let me know if you have other ideas.
  
[extract-2022-06-28T23_55_01.965Z.csv](https://github.com/bottlerocket-os/bottlerocket/files/9006220/extract-2022-06-28T23_55_01.965Z.csv)
 
[extract-2022-06-28T23_47_48.393Z.csv](https://github.com/bottlerocket-os/bottlerocket/files/9006221/extract-2022-06-28T23_47_48.393Z.csv)

**Comment by bcressey** [comment]
Agreed - the IPv6 logs in particular are very chatty because the lease is renewed so often.

The intent was to provide at least enough of a marker in the host logs to correlate a DHCP event with a hypothetical application level issue happening at the same time, but it's definitely excessive right now.
