### ISSUE TITLE
Add disk_used_percent metric

### ISSUE THREAD

**Issue by mattgresham** [bottlerocket-os/bottlerocket#2256]
By default the metrics that are reported to CloudWatch from an instance running Bottlerocket don't include `disk_used_percent`. Installing the CloudWatch Agent would normally be my course of action to do this outside of an instance running Bottlerocket, but that doesn't appear to be an option here.

For my specific use case it would be to setup a CloudWatch alarm that triggers when the data volume, disk used percentage reaches 90% so that my team can investigate adding more storage or look at application optimisations.

Is `disk-used-percent` a CloudWatch metric that can be added alongside the CPU and memory metrics, please?

**Comment by cbgbt** [comment]
Thanks for opening this issue, and sorry for the delayed response. I wonder if there are alternative solutions here?

I think generically I would suggest folks solve this by containerizing a metrics export solution. My first thoughts would be to use something like [Prometheus node exporter](https://github.com/prometheus/node_exporter). I think you could configure that to be shipped to Cloudwatch via [something like this](https://aws.amazon.com/blogs/containers/amazon-cloudwatch-prometheus-metrics-ga/).

There may be other alternatives here as well... The [Cloudwatch agent](https://gallery.ecr.aws/cloudwatch-agent/cloudwatch-agent) may be able to be deployed as a daemonset or Bottlerocket host container. Most docs surrounding this containerized agent pertain to [Container insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html), so I'm not sure just yet if there's some additional configuration required to get it to export the host-level metrics as well. I'm interested to know if this would be a quick Bottlerocket analogue to installing the Cloudwatch agent -- I'll give it a shot.

**Comment by cbgbt** [comment]
I've done a bit more looking into this and mostly found that I'm not yet sure if I'm misconfiguring the containerized Cloudwatch agent or if it isn't working as I hoped it would :sweat_smile:.

I'm going to set aside some more time to look into this. Let me know if you happen to make any headway otherwise.

I'm realizing as well that I didn't say this in my initial response: The data currently presented by Cloudwatch isn't explicitly reported by Bottlerocket, but is instead collected by EC2 outside of the host. That's why it isn't a simple matter of adding an additional metric to be reported on our end.

**Comment by cbgbt** [comment]
I was indeed misconfiguring the Cloudwatch agent :smile:.

I've just experimented with deploying the Cloudwatch agent as a daemonset to a Bottlerocket k8s cluster, and it seems that the metrics are being appropriately reported back to the Cloudwatch dashboard.

Here's a gist which shows the sample configuration I used to extract `disk_used_percent`: https://gist.github.com/cbgbt/8b49d898ab0a3c6540992c70b4113aac (You'll want to make sure to create or use an appropriate namespace)

I believe that using a Daemonset in Kubernetes or a Daemon task for ECS would be the best way to extract these Cloudwatch metrics, so I'll close this issue. But please do let me know if you have any questions or suggestions. Thanks!

**Comment by mattgresham** [comment]
Amazing, thanks for your help! I'll give this a go.
