### ISSUE TITLE
Cisco UCS server support in baremetal variants

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket#2265]
**What I'd like:**
Bottlerocket baremetal variants to support Cisco UCS servers by having the necessary drivers to boot properly.

Specifically, we should be looking at enabling:
[CONFIG_NET_VENDOR_CISCO](https://cateee.net/lkddb/web-lkddb/NET_VENDOR_CISCO.html)
[Cisco VIC Ethernet NIC Support](https://cateee.net/lkddb/web-lkddb/ENIC.html)

**Comment by foersleo** [comment]
Checked current config status and that those two are the only Cisco networking settings that are interesting (in fact these two seem to be the only cisco specific options for wired networking).

Will add them to the metal specific config once we have merged the PR for that (https://github.com/bottlerocket-os/bottlerocket/pull/2264)

**Comment by foersleo** [comment]
Looking at this some more there might be additional things we might need on the storage front for these boxes.

There is what Cisco calls `fNIC` which they use for virtual HBA via Fibre channel over ethernet (as far as I understand):

[FCOE_FNIC](https://cateee.net/lkddb/web-lkddb/FCOE_FNIC.html)
 -> (depends on [LIBFCOE](https://cateee.net/lkddb/web-lkddb/LIBFCOE.html) which we have as Module)  
     -> (depends on [LIBFC](https://cateee.net/lkddb/web-lkddb/LIBFC.html) which we have as Module)

Then there is what Cisco calls `sNIC` which is their SCSI HBA driver:

[SCSI_SNIC](https://cateee.net/lkddb/web-lkddb/FCOE_FNIC.html)

Finally, there is infiniband support for Cisco VIC:

[INFINIBAND_USNIC](https://cateee.net/lkddb/web-lkddb/INFINIBAND_USNIC.html)

**Comment by foersleo** [comment]
With merge of https://github.com/bottlerocket-os/bottlerocket/pull/2271 this is done.
