### ISSUE TITLE
Make the EC2 `instance-id` available via a file

### ISSUE THREAD

**Issue by L3n41c** [bottlerocket-os/bottlerocket#2288]
Hello,

In order to correlate data coming from the AWS EC2 APIs, we need some of our EKS pods to know the EC2 `instance-id` of the VM they are running on.
The most natural way to get the `instance-id` is to use the IMDS (`http://169.254.169.254/1.0/meta-data/instance-id`).
However, for security purpose, we’d like to keep the IMDSv2 hop limit set to 1 so that the metadata server is reachable from EKS nodes but not from the pods running on it. We would also like to avoid running our pods with host network only to make them able to reach the IMDS.

Fortunately, on both Ubuntu and Amazon Linux 2 EKS nodes, [`cloud-init` is putting the `instance-id` in the `/var/lib/cloud/data/instance-id` file](https://cloudinit.readthedocs.io/en/latest/topics/dir_layout.html) so that our pods can get the `instance-id` thanks to a `hostPath` volume.

Unfortunately, on Bottlerocket, we couldn’t find `/var/lib/cloud/data/instance-id`.

Would it be possible to have the EC2 `instance-id` available on a file on Bottlerocket so that EKS pods can read it via a `hostPath` volume ?

**Comment by rpkelly** [comment]
Hello @L3n41c, thanks for the feedback!

Unfortunately, Bottlerocket does not run `cloud-init`, so `/var/lib/cloud/` not being populated is to be expected. A more Bottlerocket style approach would probably see us put this in [`settings`](https://github.com/bottlerocket-os/bottlerocket#settings), although the only AWS specific setting we currently populate is `settings.aws.region`.  More immediately, a [bootstrap container](https://github.com/bottlerocket-os/bottlerocket/blob/372d8978e7e841e6f61314b4968b288a8f2a7258/sources/api/bootstrap-containers/README.md) could probably either set a node label setting, or even populate the file for you. I'll try it out and let you know.

**Comment by zmrow** [comment]
A bootstrap container could for sure set a node label!  There's an example here: https://github.com/bottlerocket-os/bottlerocket/issues/1647#issuecomment-887664346

(Note:  that is _very_ scrappy code for demonstration purposes :) )

**Comment by L3n41c** [comment]
Thank you both for your advice and your suggestion to look at bootstrap containers.

I managed to achieve exactly what I needed with a bootstrap container with the following configuration:
```yaml
      settings:
        bootstrap-containers:
          instance-id:
            source: <SOURCE>
            mode: always
            essential: true
```

where `<SOURCE>` is the location of an image with the following definition:
```Dockerfile
FROM alpine
RUN apk add curl
ADD bootstrap-script /
ENTRYPOINT ["sh", "/bootstrap-script"]
```

and `bootstrap-script` is the following script:
```shell
#!/usr/bin/env sh
set -eu

mkdir -p /.bottlerocket/rootfs/var/lib/cloud/data

TOKEN="$(curl --max-time 10 --retry 5 --silent -X PUT 'http://169.254.169.254/latest/api/token' -H 'X-aws-ec2-metadata-token-ttl-seconds: 21600')"
curl --max-time 10 --retry 5 --silent -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id > /.bottlerocket/rootfs/var/lib/cloud/data/instance-id
```

**Comment by rpkelly** [comment]
Awesome! Thanks for sharing this. If you run into any more problems please feel free to re-open this issue.

**Comment by yaroslav-nakonechnikov** [comment]
@L3n41c am i understand correct, that after `bootstrap container` collect data, you are able to get its content from another `host container` via `/.bottlerocket/rootfs/var/lib/cloud/data/instance-id`?
or path should be `/var/lib/cloud/data/instance-id`?

**Comment by L3n41c** [comment]
Hello,
After the bootstrap container has run, there is a `/var/lib/cloud/data/instance-id` file on the host. So, it is accessible to any container thanks to a `hostPath`.

**Comment by yaroslav-nakonechnikov** [comment]
aha, i see. in that case it is clear, thanks.

**Comment by qlikcoe** [comment]
`mkdir -p /.bottlerocket/rootfs/var/lib/cloud/data` doesn't work for me, it says Permission Denied 🤔 

@yaroslav-nakonechnikov  did it work for you?

**Comment by yaroslav-nakonechnikov** [comment]
@qlikcoe no, there is no need to create anything on root partition.

**Comment by qlikcoe** [comment]
@yaroslav-nakonechnikov  I'm unable to write anything to /var/lib/cloud/data/instance-id, the bootstrap script that's running from the bootstrap container fails at `mkdir` step.

**Comment by larvacea** [comment]
From the documentation for bootstrap containers at bottlerocket.dev:
> They have access to the underlying host filesystem at /.bottlerocket/ which contains the root filesystem (/.bottlerocket/rootfs). Additionally, bootstrap containers run with the [CAP_SYS_ADMIN capability](https://bottlerocket.dev/en/os/1.21.x/api/settings/oci-defaults/#capabilities_sys-admin), allowing for the creation of files, directories, and mounts accessible to the host (however the root filesystem remains [immutable](https://bottlerocket.dev/en/os/1.21.x/concepts/restricted-filesystem/#immutable-filesystem)).

This is why you won't be able to `mkdir -p` anything under `/.bottlerocket/rootfs`. If you examine the host mounts after Bottlerocket boots, you can see that `/run` is mounted as a `tmpfs` (i.e., memory-based ephemeral) file system. That directory (once it is mounted) is mutable, though `/` itself is not. Hope this helps.

**Comment by qlikcoe** [comment]
Thank you @larvacea! I'm wondering how did the described solution work for people in the comments above where mkdir is trying to write to `/.bottlerocket/rootfs/var/lib/cloud/data`
