### ISSUE TITLE
`kmod-5.10-nvidia` rpm spec can't be parsed without SDK

### ISSUE THREAD

**Issue by stockholmux** [bottlerocket-os/bottlerocket#2294]
**Platform I'm building on:**
n/a (macos, but I'm not _really_ building, but it's build adjacent)

**What I expected to happen:**
I should be able to use [`rpmspec`](https://man7.org/linux/man-pages/man8/rpmspec.8.html) to parse any `.spec` file in `/packages` on any platform. 

**What actually happened:**
When trying to parse the `kmod-5.10-nvidia` with `rpmspec` I get the following error:
```
sh: bottlerocket-license-tool: command not found
sh: bottlerocket-license-tool: command not found
error: line 39: Empty tag: License:
error: query of specfile /bottlerocket/packages/kmod-5.10-nvidia/kmod-5.10-nvidia.spec failed, can't parse
```

While the `bottlerocket-license-tool` is in the [SDK](https://github.com/bottlerocket-os/bottlerocket-sdk), this dependency isn't documented and it seems rational that someone wouldn't have the SDK just to try to inspect the rpm spec

**How to reproduce the problem:**
```
rpmspec -q --qf "%{Version}:" /bottlerocket/packages/kmod-5.10-nvidia/kmod-5.10-nvidia.spec  --define="_cross_os _" --nodebuginfo
```

**Note:** Could you solve this by adding an or (`||`) operator? Something like  `... || echo "could not determine license."` at the [end of line 4](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kmod-5.10-nvidia/kmod-5.10-nvidia.spec#L4)? In my testing adding the or operator allowed the spec to parse.

**Comment by stmcginnis** [comment]
The rpm files are not meant to be standalone packages. They really are tailored for the Bottlerocket build process, and therefore have some unique things in them that require using the Bottlerocket SDK to be of any use.

Going to close this since it's not really in scope for how we use rpms.
