### ISSUE TITLE
testsys: convert error from anyhow to snafu

### ISSUE THREAD

**Issue by ecpullen** [bottlerocket-os/bottlerocket#2297]
A little late to comment on this, but I just realized that in all the Bottlerocket repo, we don't use `anyhow` and instead we use `snafu`. I think we should be consistent and move at least this part of `testsys` to `snafu`. I'm not blocking on this though but an issue should be good.

_Originally posted by @arnaldo2792 in https://github.com/bottlerocket-os/bottlerocket/pull/2273#discussion_r924744267_

**Comment by webern** [comment]
I think you did this, right @ecpullen ?
