### ISSUE TITLE
Bottlerocket settings: Add data type / example for all configuration settings in Bottlerocket documentation (README)

### ISSUE THREAD

**Issue by RobertNorthard** [bottlerocket-os/bottlerocket#2324]
**What I'd like:**

Not all Bottlerocket settings in the readme provide examples. For example, for the following settings image-gc-low-threshold-percent, image-gc-high-threshold-percent it is not clear if the expected value is a string or integer, which can cause confusion during Bottlerocket configuration and result in time spent debugging. Please can this be made clearer for all settings values?

**Any alternatives you've considered:**
N/A

**Comment by zmrow** [comment]
Thanks @RobertNorthard !  This is a good idea - we'll look into making that happen.

**Comment by stmcginnis** [comment]
I think the original concern has been addressed with the odd data types for some values with #2939, but it would be nice to have some clearer documentation around settings and their expected values.

@stockholmux do you think this would be good for the project-website?

**Comment by stockholmux** [comment]
@stmcginnis That's fine although API documentation didn't make it into the first round of documentation. It will probably remain on the README for a while yet.

**Comment by webern** [comment]
I believe the current status is: "scalar values are strings unless otherwise noted" and the k8s-gc-threshold settings are the only ones otherwise noted.

**Comment by stmcginnis** [comment]
I think this is now addressed with all the work done in https://bottlerocket.dev/en/os/1.16.x/api/settings/ so closing this issue. If there is anything further missing there, please file an issue in the https://github.com/bottlerocket-os/bottlerocket-project-website repo.
