### ISSUE TITLE
Limit `pluto`'s EKS API request retries/timeout when describing the cluster

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket#2370]
**What I'd like:**
`pluto` to not block settings generation for 30 minutes when retrying requests to the EKS API when retrieving the cluster's network configuration.

Currently, a Bottlerocket host running in a network-isolated environment will hang during boot if `settings.kubernetes.cluster-dns-ip` is not already set in user-data on first boot. `sundog` will kick-off `pluto` to try and generate that setting. If there is no network access to the EKS API, `pluto` (via AWS Rust SDK) will retry requests for 30 minutes before giving up and falling back to a default value. See https://github.com/bottlerocket-os/bottlerocket/blob/037d0e2798a7e8d4a12d0fb35d3c266db3d74f25/sources/api/pluto/src/main.rs#L166-L172.

What we want is to limit the retry timeout somehow via https://docs.rs/aws-sdk-eks/latest/aws_sdk_eks/struct.RetryConfig.html.

Ideally we will match the timeout for our IMDS request retries, which is currently around 5 minutes.

**Any alternatives you've considered:**
N/A

**Comment by webern** [comment]
It might also be possible to wrap in tokio timeout (if the SDK mechanisms don't work out), e.g. how it was done here: https://github.com/bottlerocket-os/bottlerocket-test-system/blob/49ae24b59cb4a245352fe5e7078b859a83b76c5b/selftest/src/cluster.rs#L133
