### ISSUE TITLE
Makefile: provide a unified `check` target that performs all `check-*` tasks

### ISSUE THREAD

**Issue by jpmcb** [bottlerocket-os/bottlerocket#2381]
### What I'd like:

Currently, as a developer of Bottlerocket, checking formatting and linters requires both `cargo make check-fmt` and `cargo make check-lints` which is a bit annoying and easy to miss one or the other.

To facilitate easier development and have fewer GitHub action failures, we should provide a `cargo make check` target that performs _all_ dev related checks.

### Any alternatives you've considered:

- Alias my own local script that performs the check tasks and use that for a pre-commit hook

Would love feedback on this idea or if others would find it useful!

**Comment by bcressey** [comment]
Sounds good!
