### ISSUE TITLE
Fail `cargo make build` if clippy / linter checks fail

### ISSUE THREAD

**Issue by jpmcb** [bottlerocket-os/bottlerocket#2401]
### What I'd like:

From a discussion in a previous community meeting, it would be nice to have builds fail if the lint checks fail - in theory, anything that is on the tip of `develop` should be a fully passing build and pass linters. Any changes that are being made which don't conform with the checks would fail, indicating it's not ready for review.

However, we don't want to make the buildtimes extra long - since we'd be invoking `cargo` several times, we run into the problem of essentially doing _multiple_ builds (may be good to get @bcressey's ideas on this). One idea is to somehow link builds across jobs to prevent multiple builds.

### Any alternatives you've considered:

* **_Don't_** fail on clippy / lint / formatting problems. Contributors can have an easier time going from a change they're trying to make to and actual build. Further, simple formatting changes may not indicate that a build is unable to work. I.e., not doing this enables people making changes to keep making changes fast.
* Add an extra make target. Maybe something like `cargo make safe-build` or `cargo make check-build` which invokes checking _and_ building.

**Comment by webern** [comment]
Related to this #1776 which is marked as done.

**Comment by stmcginnis** [comment]
We think this is working as expected now, so closing.
