### ISSUE TITLE
Allow overrides to the default OCI spec capabilities for k8s pods

### ISSUE THREAD

**Issue by arnaldo2792** [bottlerocket-os/bottlerocket#2404]
**What I'd like:**
With #1703, Bottlerocket will support overrides to RLIMITS in the OCI spec. A follow up feature will be to allow overrides to the OCI spec capabilities through the API.

**Any alternatives you've considered:**
Use k8s directives to override the default capabilities per pod, but this method requires the user to override the capabilities for each pod instead of all of them at once.

**Comment by mchaker** [comment]
Closed in #2697
