### ISSUE TITLE
Setting containerd configurations using userdata

### ISSUE THREAD

**Issue by ozahavi** [bottlerocket-os/bottlerocket#2408]
**What I'd like:**
To be able to set containerd configurations using userdata.
For example - 
```
[proxy_plugins]
  [proxy_plugins.stargz]
    type = "snapshot"
    address = "/run/containerd-stargz-grpc/containerd-stargz-grpc.sock"

[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "stargz"
  disable_snapshot_annotations = false
```

**Comment by etungsten** [comment]
Hi @ozahavi, thanks for the bringing this up. Is there a specific set of containerd configuration items you're most interested in? Inferring from your example, I'm guessing you'd like to use the stargz plugin with bottlerocket. We can take a closer look at supporting additional containerd plugins.

**Comment by ozahavi** [comment]
> Hi @ozahavi, thanks for the bringing this up. Is there a specific set of containerd configuration items you're most interested in? Inferring from your example, I'm guessing you'd like to use the stargz plugin with bottlerocket. We can take a closer look at supporting additional containerd plugins.

The settings that I was looking for are the ones I stated above, specifically for configuring the stargz plugins.
ATM I am reconsidering stargz after learning about SOCI. Closing this issue until I have a clearer picture of the path I am going to choose.

**Comment by tuananh** [comment]
how about customizing bottlerocket in general. passing TOML file with user-data is kinda limited.

we cannot add additional binaries, configuration for containerd plugins, etc.. for example

**Comment by tuananh** [comment]
@etungsten what's the general advise for those use cases with bottlerocket?

**Comment by etungsten** [comment]
Hi @tuananh, the container runtime configuration is controlled via Bottlerocket API settings. We currently do not expose custom containerd plugin configuration in Bottlerocket's API. You can put in a feature request for this. It seems like the discussion has shifted to https://github.com/bottlerocket-os/bottlerocket/issues/2788 so let's focus our conversation there.

**Comment by tuananh** [comment]
> Hi @tuananh, the container runtime configuration is controlled via Bottlerocket API settings. We currently do not expose custom containerd plugin configuration in Bottlerocket's API. You can put in a feature request for this. It seems like the discussion has shifted to https://github.com/bottlerocket-os/bottlerocket/issues/2788 so let's focus our conversation there.

Say i want to do a quick test, i can just edit containerd package directly right?

**Comment by etungsten** [comment]
Hi @tuananh , that is correct. You can theoretically just bake in your plugin configuration directly into the templates, e.g. https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/containerd/containerd-config-toml_k8s_containerd_sock
