### ISSUE TITLE
Bottlerocket is not working with vsphere vvols

### ISSUE THREAD

**Issue by t0ffel** [bottlerocket-os/bottlerocket#2433]
**Image I'm using:**
Using bottlerocket-vmware-k8s-1.23-x86_64-v1.9.2.ova

**What I expected to happen:**

I expect the provisioned VM (disk not resized) to come up without any ext4 errors.

**What actually happened:**

VM comes up, but then it starts spamming ext4 errors.
![Screenshot (14)](https://user-images.githubusercontent.com/13840987/190708019-94640252-07fa-4993-a989-508015089c2a.png)
![Screenshot (13)](https://user-images.githubusercontent.com/13840987/190708034-3e640c9b-8c5d-42dd-8abd-520a90ce0943.png)
![Screenshot (12)](https://user-images.githubusercontent.com/13840987/190708046-700cb214-7aba-460c-a8a1-df05b0be261a.png)
![Screenshot (11)](https://user-images.githubusercontent.com/13840987/190708060-c823cfe4-f30a-4e0e-8a96-6cdb5de3901f.png)
![Screenshot (10)](https://user-images.githubusercontent.com/13840987/190708076-5b9b793e-f198-4c5b-acd8-6cfdad7d8922.png)

**How to reproduce the problem:**

Working on vSphere 7.0.2. The datastore is vvols.
The template is on vvol and I'm provisioning vm to vvol.
vvol is backed by Purity Flash Array 6.1.14.

When I switched to VMFS, the VM comes up without any issues

**Comment by zmrow** [comment]
Thank for letting us know!  

Just to confirm - you _do not_ see the issue when using VMFS?

**Comment by t0ffel** [comment]
@zmrow correct. VMFS works as expected.

**Comment by esiebert7625** [comment]
It looks like you are using NVMe storage, vVols does not currently support that. NVMe will be supported starting in vSphere 8.0.

**Comment by zmrow** [comment]
Thanks @esiebert7625 !

**Comment by stmcginnis** [comment]
Great information attached, and it doesn't appear there is anything we can do from the Bottlerocket side at this point. Going to close the issue if that is the case, but feel free to reopen or file a new issue if this is still the case with vSphere 8.0.
