### ISSUE TITLE
Switch to `systemd-networkd` as a replacement for `wicked`

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#2449]
**What I'd like:**
I'd like to move to `systemd-networkd` to streamline dependencies and provide a more familiar networking stack for users.

Bottlerocket [switched to `wicked`](https://github.com/bottlerocket-os/bottlerocket/pull/150) in the early stages of the project.  A few things have changed since then and some aspects of that PR aren't applicable anymore.

**Any alternatives you've considered:**
Continue using wicked and keep the status quo

**Comment by zmrow** [comment]
Our main goal for this change is to make the switch as invisible as possible to the user.  Ideally, no one should even notice the switch happened.  This means there can be no functionality loss.  It also means we will continue to support all current network config versions.

While the change to `systemd-networkd` opens the door for more networking-related features, we won't be adding any new features as part of this switch.  We will make the switch to `systemd-networkd` first, and add features later.

Tasks list (subject to update and change):

- [x] Add `systemd-networkd` to the tree.
  - [x] Add `networkd` as a subpackage of `systemd`
  - [x] Add a build flag to enable the use of `systemd-networkd` in any variant.
  - [x] Evaluate `networkd`-related packages from the above PR to determine if they are still necessary
- [x] Implement `networkd` config file generation in netdog 
- [x] Implement the "optional lease" behavior `wicked` provides.  (interface config for `systemd-networkd-wait-online.service`?) 
~~- [ ] Implement a helper to run on interface initialization and DHCP lease renewal (DBUS listener?)  This rewrites `current_ip` and `resolv.conf` (WIP: @yeazelm )~~
~~- [ ] Handle DNS settings - read from networkd lease (WIP: @yeazelm)~~
- [x] Integrate systemd-resolved
- [x] Handle sysctls for primary interface (if necessary)
- [x] Evaluate any new SELinux rules that might be necessary
- [x] Analyze and lock down the DBUS policy (via DBUS policy rules and/or SELinux rules). Figure out polkit's permissions and lock them down if necessary.  Additional resources: [One](https://dbus.freedesktop.org/doc/dbus-daemon.1.html), [Two](https://subscription.packtpub.com/book/networking-and-servers/9781783989669/10/ch10lvl1sec88/controlling-d-bus-message-flows), [Three](https://chromium.googlesource.com/chromiumos/docs/+/master/dbus_best_practices.md), [Four](https://chromium.googlesource.com/chromiumos/docs/+/master/dbus_in_chrome.md)
- [x] Patch out references to unused components or dbus services like hostnamed

**Comment by zmrow** [comment]
> Handle sysctls for primary interface (if necessary)

Mostly likely we'll end up handling these in the DBUS helper @yeazelm is working on.  This is identical to the current behavior where the sysctls for the primary interface are set in the wicked `install` helper.

I had hopes we could handle it in networkd config, but we set the `rp_filter` sysctl for our primary interface and networkd [doesn't currently allow setting this via config](https://github.com/systemd/systemd/issues/26241).

**Comment by zmrow** [comment]
As referenced in #3366 , the team made the decision to integrate `systemd-resolved` instead of writing our own DBUS listener to respond to DHCP events and write a simple resolve.conf.

#3394 is open to flip the (not yet released) Kubernetes 1.28 and `aws-ecs-2` variants to `systemd-networkd`.  The `*-dev` variants are also being flipped in the same PR.

No user-facing changes related to networking will be necessary to use those variants!

**Comment by yeazelm** [comment]
We have completed the work to move to systemd-networkd for new variants (#3394). I'll close this issue and we can track any future work as bug or features since the migration is done and we don't plan to move existing variants to networkd.
