### ISSUE TITLE
`cargo make ami` should scream at me if it didn't create an ami due to the name already existing

### ISSUE THREAD

**Issue by stmcginnis** [bottlerocket-os/bottlerocket#2459]
Edit: I changed the title to reflect the discussion that happened below. We don't EVER want to overwrite an AMI, but we want the tool to make it extremely apparent when it hasn't written an AMI. Currently the warning is too subtle.

**What I expected to happen:**

While doing local development I need to test the changes I am making. That is made very easy now by running something like:

```
cargo make && cargo make ami && cargo make setup-test && cargo make test
```

Under normal situations, this compiles local changes, creates and registers an AMI, then runs testsys to get a cluster running using the local changes in the node image to validate.

**What actually happened:**

The problem is during a development cycle the git SHA-based identifier doesn't change. So if you are not paying close attention, the `cargo make ami` from above may print out the following:

```
[2022-09-26T22:20:39Z WARN  pubsys::aws::ami] Found 'bottlerocket-aws-k8s-1.22-x86_64-v1.10.0-8d731056-dirty' already registered in us-east-2: ami-06dd1bdaa7e4f351c
```

But then carry on. This can result in a cluster running without the recent changes, making it confusing why a change is not being reflected in the test deployment.

`cargo make ami` should probably overwrite any existing AMI, or error out. Alternatively, we could use some sort of timestamp based identifier rather than, or in addition to, the `-[sha]-dirty` identifier.

**How to reproduce the problem:**

Make local changes, deploy, make more local changes, try to deploy again.

**Comment by bcressey** [comment]
There are a few elements at work here:
* I have a deep and abiding terror at the idea of accidentally deregistering a production AMI.
* `cargo make ami` is meant to be idempotent and safe to retry in the face of transient errors.
* `cargo make ami` will also implicitly copy the AMI to multiple regions, which can be a source of errors.

Which is to say that I'm not very excited about adding a deregister step. It would complicate the intended use case of a general purpose publishing tool, and introduce a significant hazard for production deployments. I could maybe see my way to a `cargo make deregister-ami` but that still feels pretty dangerous.

> Alternatively, we could use some sort of timestamp based identifier rather than, or in addition to, the -[sha]-dirty identifier.

That said, I like your idea of appending a timestamp to `BUILDSYS_VERSION_BUILD` in the specific case of a "dirty" tag. That feels like a happy medium: a developer that's iterating on changes but not committing them will get a succession of AMIs, while a developer that commits them will get the current dedupe behavior of `cargo make ami`.

There's a small problem of what timestamp to use; `date +%s` would not be consistent between `cargo make ami` and `cargo make test`; we would need to tie the timestamp to something that only changed when the "dirty" files changed in some way.

**Comment by webern** [comment]
Another possibility would be for pubsys to error out instead of overwriting and have an `--overwrite-ami` flag.

I have lost days of development time before because I couldn't figure out why my changes were not affecting Bottlerocket behavior because I didn't notice `already registered in us-east-2: ami-06dd1bdaa7e4f351c`
Now all of my scripts use uuidgen for the name of the ami

**Comment by webern** [comment]
I think the status of this is "won't fix", @bcressey and @stmcginnis should we close this?

**Comment by stmcginnis** [comment]
I suppose so. It would be great if we could at least make this glaringly obvious in the output that nothing actually changed to help avoid the mistake of change>build>test>change>build>test>etc, wondering the whole time why the changes you're making aren't actually visible.

**Comment by webern** [comment]
I'll leave it open and rename it to reflect that ask.

**Comment by jpmcb** [comment]
Also ran into this recently and burned some cycles on not seeing this warning surfaced.

I would personally like some kind of `--force` flag that overwrites an AMI.

Or if that's unacceptable, what about a `--force-dirty` flag? That would be useful during development:
```
if ami already found:
    if build is "dirty":
       if "force-dirty" flag is set:
           overwrite existing dirty dev ami
       else:
           print warning that ami is already found
```
