### ISSUE TITLE
Injecting dynamic labels to userdata

### ISSUE THREAD

**Issue by avifreege** [bottlerocket-os/bottlerocket#2462]
we are evaluating bottlerocket for our EKS clusters, the first thing we noticed since bottlerocket expects TOML format user-data we cannot run dynamic commands as EKS official ami's and was wondering if you have a solution for that, i.e:
injecting the lable of the node lifecycle:
```node.kubernetes.io/instance-life-cycle=$(curl http://169.254.169.254/latest/meta-data/instance-life-cycle```

**Comment by zmrow** [comment]
Hi there!  This can be accomplished with bootstrap containers!  There's a good example of setting a node label here: https://github.com/bottlerocket-os/bottlerocket/issues/1647#issuecomment-887664346

(Note: that is very scrappy code for demonstration purposes :) )

**Comment by zmrow** [comment]
I'll close this for now - feel free to re-open the issue if the above solution doesn't solve the issue.
