### ISSUE TITLE
Add validation for `settings.kubernetes.log-level` value

### ISSUE THREAD

**Issue by stmcginnis** [bottlerocket-os/bottlerocket#2463]
**What I'd like:**

The `log-level` setting controls logging verbosity for kubelet. The only real valid values for this setting are 0 through 8, but since we can currently only use an unsigned integer type we aren't able to validate settings are within an expected range.

If/when we are able to implement a custom type (see https://github.com/bottlerocket-os/bottlerocket/issues/2257) for numeric settings, we should take advantage of that for this setting to make sure we restrict things to the valid range.

**Any alternatives you've considered:**

Alternative is to keep it as is with an unsigned value. These "work", just are not as correct.

**Comment by webern** [comment]
This is pseudo-blocked by #2257, I can take this one after 2257.

**Comment by webern** [comment]
Closing because kubelet accepts values out of this range: see https://github.com/bottlerocket-os/bottlerocket/pull/2595#issuecomment-1331445809
