### ISSUE TITLE
Update nvidia driver to latest

### ISSUE THREAD

**Issue by blackliner** [bottlerocket-os/bottlerocket#2468]
**What I'd like:**

Update bottlerocket to version 515 of the nvidia driver. Currently used version 470 is outdated and does not support newer features like CC detection via nvidia-smi

See https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kmod-5.10-nvidia/kmod-5.10-nvidia.spec#L1

**Any alternatives you've considered:**

No

**Comment by arnaldo2792** [comment]
This is on its way! Should be ready as part of the newer k8s-1.24-nvidia variant! See #2455 and #2437

**Comment by blackliner** [comment]
Amazing, thanks!

**Comment by arnaldo2792** [comment]
@blackliner, we added support for the newer drivers in the latest [Bottlerocket release] in the AWS k8s 1.24 images :tada: ! Please refer to the release notes and [this section] of the documentation for details.

[Bottlerocket release]: https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.10.0
[this section]: https://github.com/bottlerocket-os/bottlerocket#nvidia-gpus-support

I'll close this issue, but let us know if you find any problems!

**Comment by blackliner** [comment]
Amazing, we already use it, thanks a lot!

**Comment by gmykhailiuta** [comment]
AWS EKS still has only 1.23 to offer. Would it be possible to add 1.23 support to Bottlerocket as well?
