### ISSUE TITLE
x509: certificate signed by unknown authority error while building image

### ISSUE THREAD

**Issue by bludhemn** [bottlerocket-os/bottlerocket#2475]
I'm trying to build the Bottlerocket AMI on a RHEL 7.9 EC2 instance. When I run `cargo make` it errors out at the `fetch-vendored` task. 

```
[ec2-user@ip- bottlerocket-1.9.2]$ cargo make
[cargo-make] INFO - cargo make 0.36.1
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: setup
[cargo-make] INFO - Running Task: setup-build
[cargo-make] INFO - Running Task: fetch-sdk
[cargo-make] INFO - Running Task: fetch-toolchain
[cargo-make] INFO - Running Task: fetch-sources
[cargo-make] INFO - Running Task: fetch-vendored
go: github.com/NVIDIA/go-nvml@v0.11.6-0: Get "https://proxy.golang.org/github.com/%21n%21v%21i%21d%21i%21a/go-nvml/@v/v0.11.6-0.mod": x509: certificate signed by unknown authority
go: downloading github.com/NVIDIA/go-nvml v0.11.6-0
go: github.com/NVIDIA/go-nvml@v0.11.6-0: Get "https://proxy.golang.org/github.com/%21n%21v%21i%21d%21i%21a/go-nvml/@v/v0.11.6-0.mod": x509: certificate signed by unknown authority
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

I can curl the go-nvml URL:
```
[ec2-user@ip- bottlerocket-1.9.2]$ curl https://proxy.golang.org/github.com/%21n%21v%21i%21d%21i%21a/go-nvml/@v/v0.11.6-0.mod

module github.com/NVIDIA/go-nvml

go 1.15
```
We have a corporate proxy in the middle and the certificate for the proxy is issued by a private CA. The private CA root and issuing certs have been added in `/etc/pki/ca-trust/source/anchors` and ran `update-ca-trust`.

-->

**Platform I'm building on:**
AWS, RHEL 7.9 
Linux ip-x.ap-southeast-2.compute.internal 3.10.0-1160.76.1.el7.x86_64 #1 SMP Tue Jul 26 14:15:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mchaker** [comment]
Hi @bludhemn , thanks for pointing this out. It seems like the containerized build system is not using the certificates you have added to your development environment. The build system should have a feature for utilizing the certificates that are installed in the development environment. If you don't mind, I'll close this issue and open a new one to track that feature.
