### ISSUE TITLE
Configure kubelet parameters via BR API

### ISSUE THREAD

**Issue by nkvetsinski** [bottlerocket-os/bottlerocket#2481]
**What I'd like:**

Our team needs to change some of the kubelet parameters (in our case we change `-v --client-ca-file, --tls-cert-file, --tls-key-file`). We would like to have these parameters exposed to the API, ideally all of the [flags](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) can be changed.

**Any alternatives you've considered:**

To unblock our usecase we have created privileged host container that changes KubeletConfig file on the filesystem.

**Comment by stmcginnis** [comment]
Thanks @nkvetsinski - this looks like good functionality to support. I don't have any timeframe yet, but I'll take a look and I should be able to get to this soon(ish!).

^^ That said, if any community members are interested in picking this up, just let me know. :)

**Comment by stmcginnis** [comment]
Small update, the `-v` parameter for adjusting logging level is included in the v1.10.0 release with #2460

**Comment by nkvetsinski** [comment]
Sweet!

**Comment by stmcginnis** [comment]
Here are the equivalent Bottlerocket settings:

## Existing

| Kublet Arg | Bottlerocket Setting |
|------------|----------------------|
| `-v` | `settings.kubernetes.log-level` |
| `--client-ca-file` | `settings.kubernetes.cluster-certificate` |

## New in v1.11.0 (or whichever release after #2536 lands)

| Kublet Arg | Bottlerocket Setting |
|------------|----------------------|
| `--tls-cert-file` | `settings.kubernetes.server-certificate` |
| `--tls-key-file` | `settings.kubernetes.server-key` |

All cert settings take the base64 content of the files that will be decoded and written out on the host and the kubelet configuration will be updated to point to those local files.

**Disclaimer**: New setting names are subject to change based on review feedback. Will try to remember to edit/update this comment with any changes.

**Comment by stmcginnis** [comment]
Updated the previous comment with the final names of the settings. This should be in the v1.11.0 release.
