### ISSUE TITLE
Bottlerocket unable to launch in fully private EKS cluster

### ISSUE THREAD

**Issue by KeenanLawrence** [bottlerocket-os/bottlerocket#2535]
**Image I'm using:**
1.10.0

**What I expected to happen:**
EC2 instance starts up successfully

**What actually happened:**
EC2 instance does not start up successfully

**How to reproduce the problem:**
Hi there  

I have a fully private EKS cluster, i.e the control plane and data plane subnets have no route to the internet. Technically, the default route is to a network firewall which drops internet-bound traffic. I have VPC endpoints for all AWS services needed.

I noticed that when the EC2 instance is starting up, it hangs at `Starting User-specified setting generators...`

```
...
[  OK  ] Reached target Network.
[  OK  ] Reached target Network is Online.
         Starting Bottlerocket userdata configuration system...
[  OK  ] Finished Bottlerocket userdata configuration system.
         Starting User-specified setting generators...
<end of log>
```

I looked at all the available settings and double-checked my config to see if I missed something. I opened the firewall temporarily and logged all internet-bound requests. All the [IPs belonged to AWS](https://ip-ranges.amazonaws.com/ip-ranges.json) so I checked which services it was trying to reach. Turns out that it was `CloudFront` and `EC2`.
I started poking around in the codebase and I believe that the issue is with `schnauzer`, specifically [this line](https://github.com/bottlerocket-os/bottlerocket/blob/v1.10.0/sources/api/schnauzer/src/helpers.rs#L115). It seems that the S3 bucket is fronted by a CloudFront distribution for all regions except `cn-north-1` and `cn-northwest-1`. CloudFront, understandably, doesn’t have a VPC endpoint.
The EC2 call is a bit curious. I think it might be because I'm leaving some things for `pluto` to work out, and perhaps it's calling the EKS API instead of using the IMDS service. I haven't checked this yet, but if it is the case then I'll try to set all the parameters upfront.

So the fix would be allowing the user the option of pulling from the CDN or from the S3 bucket directly. 

A workaround (that I’d much rather want to avoid) would be whitelisting all [CloudFront IPs](https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips) on the firewall.

Is there anything I'm doing wrong or something that I've missed? Is this a relatively easy fix?
Thanks!

**Comment by ecpullen** [comment]
Thanks for reaching out. Bottlerocket should be able to run in a private VPC (without updates). You should be able to either set the cluster-dns-ip or add a PrivateLink for EKS to your VPC for the EKS calls.
```
[settings.kubernetes]
cluster-dns-ip = "<CLUSTER-DNS-IP>"
```
The CloudFront call was likely the metrics endpoint, and disabling metrics ping should fix it.
```
[settings.network]
send-metrics = false
```
Since there is no connection to the tuf repos in place updates will not work, but if you are using EKS MNG, node replacement will be used. 

FYI @dmitmasy

**Comment by KeenanLawrence** [comment]
Thanks for the response, Ethan.
There's no PrivateLink for EKS, so we've set the `cluster-dns-ip` explicitly. This removed the EC2 API calls.
We've also set `settings.metrics.send-metrics = false` and this removed the CloudFront call. Should this be a blocking call though? It seems a bit weird that the instance doesn't start because it can't send metrics. It should fail with messages in the log and continue.

In any case, updates are an absolute must and so we're forced to whitelist the IPs on our firewall (with additional conditions, of course) because we're busy replacing MNG with Karpenter (we need the node TTL feature), so our nodes are self-managed.

I'll close this issue, but I think this (fully private clusters) should be made explicit in the documentation.

Thanks!

**Comment by webern** [comment]
> instance doesn't start because it can't send metrics

**Comment by webern** [comment]
> instance doesn't start because it can't send metrics

Perhaps it could be better documented, but the design is for the instance to start regardless of whether health metrics pings succeed or not. The error is reported, but the program exits zero and the systemd oneshot service succeeds. The code is here:

https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/metricdog/src/main.rs#L124..L126
