### ISSUE TITLE
Bottlerocket v1.10.1  has no file `/usr/bin/stunnel5`  using aws-efs-csi-driver 

### ISSUE THREAD

**Issue by xinfeingxia85** [bottlerocket-os/bottlerocket#2552]
**Image I'm using:**
Bottlerocket: v1.10.1

**What actually happened:**
The EFS works no well using EKS 1.23,  so that some pods can't mount EFS storage and are stuck in the CrontainerCreate phase all the time. 

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/20057242/199936212-943c2f44-fb39-45e9-87a0-9ca48cec493f.png">

**What I expected to happen:**
The EFS works well and pods can mount EFS storage.

**How to reproduce the problem:**
If the Bottlerocket version is less than or equal to 1.9.2, EFS can work fine.

**Comment by bcressey** [comment]
`/usr/bin/stunnel5` (and all other programs that a CSI driver needs) should be coming from the container.

So this is most likely an issue with the EFS CSI driver, though something about Bottlerocket in 1.10 might be triggering new behavior.

Can you confirm that you're using the same EFS CSI driver deployment across the two versions?

**Comment by xinfeingxia85** [comment]
Yes, I used the EFS CSI driver v1.3.8 and Bottlerocket v1.9.2 / v1.10.1.

The EFS CSI driver v1.4.2 and Bottlerocket v1.9.2 are used in the production environment,  but it works fine. If Bottleroket is upgraded to v1.10.1,   it will make an error that the file `/usr/bin/stunnel5` is not found. 

Maybe  one component using the file `/usr/bin/stunnel5` or `/usr/bin/stunnel`  in the EFS CSI driver has to do with the system. 

https://github.com/aws/efs-utils/commit/dd8dc31daa74cd193f5855d218de7cf304143c97

**Comment by etungsten** [comment]
Hi @xinfeingxia85, I found this issue https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/812 that seems relevant and it looks to be a widespread issue not limited to Bottlerocket. Bottlerocket itself does not package `efs-utils`. Reading the issue over there it seems like there was a regression in the `aws-efs-csi-driver` image in 1.4.3 that they're trying to fix. Can you check if your deployment is using that image and if moving that to the previous version fixes it?

**Comment by etungsten** [comment]
It seems like they pushed out a new 1.4.4 release to address this issue. Can you please try that out and see if the issue still comes up? https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-1.x.md#v144

**Comment by xinfeingxia85** [comment]
> It seems like they pushed out a new 1.4.4 release to address this issue. Can you please try that out and see if the issue still comes up? https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-1.x.md#v144

OK, I am going to verify that.

Thank you!

**Comment by xinfeingxia85** [comment]
It works fine while using the latest version。
