### ISSUE TITLE
Cannot restart Kubelet when there is no network connection

### ISSUE THREAD

**Issue by vpnda** [bottlerocket-os/bottlerocket#2567]
**Image I'm using:**
bottlerocket-aws-k8s-1.21-x86_64-v1.8.0-a6233c22

**What I expected to happen:**
When I reboot my machine when there is no network connection, I am expecting `kubelet` to come back online or to at least see the process failing to start. If there is no network connection, I should see the `kubelet` running on the cached container. 

**What actually happened:**
The container in which the `kubelet` is executed is not able to start because BR [instructs containerd](https://github.com/bottlerocket-os/bottlerocket/blob/e8a5391ac70829ad8c259671676a0e131ddd6673/sources/host-ctr/cmd/host-ctr/main.go#L983-L991) to call ECR to fetch the image rather than use the cached version.

```
Nov 08 20:18:19 ip-10-0-3-98.us-west-2.compute.internal host-ctr[1102632]: time="2022-11-08T20:18:19Z" level=info msg="pulling with Amazon ECR Resolver" ref="ecr.aws/arn:aws:ecr:us-west-2:193646904820:repository/eks/eks-distro/kubernetes/pause:v1.21.14-eks-1-21-19"
Nov 08 20:19:49 ip-10-0-3-98.us-west-2.compute.internal systemd[1]: kubelet.service: start-pre operation timed out. Terminating.
Nov 08 20:19:49 ip-10-0-3-98.us-west-2.compute.internal systemd[1]: kubelet.service: Control process exited, code=killed, status=15/TERM
Nov 08 20:19:49 ip-10-0-3-98.us-west-2.compute.internal systemd[1]: kubelet.service: Failed with result 'timeout'.
Nov 08 20:19:49 ip-10-0-3-98.us-west-2.compute.internal systemd[1]: Failed to start Kubelet.
```

**How to reproduce the problem:**
1. Create a CPI or worker node with BR in AWS.
2. Start SSM Session
3. Remove network access to machine by removing all egress security group traffic. SSM session should continue to work at this point.
4. Restart `kubelet`
5. `kubelet` is never initalized.

**Comment by jpculp** [comment]
Hi @vpineda1996, can you expand a bit on your use case? Network access is required to pull ECR credentials, but also pulling a fresh container on reboot resets you back to an unmodified state (excluding the files under the persistent storage locations).

**Comment by bcressey** [comment]
@jpculp the attempt to pull the pause container via `host-ctr` doesn't complete before `systemd` gives up, which means that `kubelet` never gets started:
https://github.com/bottlerocket-os/bottlerocket/blob/64be2f25684d0c30b8b639f6280f2fbe733ba81c/packages/kubernetes-1.24/prestart-pull-pause-ctr.conf#L2

There should be a better way to deal with this in the detached network case, where there's already a cached copy of the image on disk. Especially for the pause container, reusing the local copy if it exists should be good enough.

**Comment by vpnda** [comment]
Hey @jpculp, I think @bcressey has an idea of what I want to achieve. I think I might have phrased my requirements incorrectly, making you believe that I wanted to use the same instantiation of the `pause` container after `kubelet` is restarted. This in fact NOT what I meant to say.

I want to reuse the cached `pause` image that was pulled and cached inside the host. That means that after the `kubelet` gets restarted, a new fresh container must be created but instead of trying to pull the image every single time, BR should be smart enough to use the "local" image if its present.

**Comment by vpnda** [comment]
I submitted a similar fix for the EKS AMI. https://github.com/awslabs/amazon-eks-ami/pull/1090
