### ISSUE TITLE
testsys: Provide better filtering for `testsys status`

### ISSUE THREAD

**Issue by ecpullen** [bottlerocket-os/bottlerocket#2572]
**What I'd like:**

If many tests are being run, there will be many columns in `testsys status` and not all are visible when using `cargo make watch-test`. A set of filtering methods should be implemented for the `status` command to limit status results.

**Any alternatives you've considered:**

**Comment by webern** [comment]
Looks like this should be linked https://github.com/bottlerocket-os/bottlerocket-test-system/issues/656
