### ISSUE TITLE
Hostname resolution

### ISSUE THREAD

**Issue by nkvetsinski** [bottlerocket-os/bottlerocket#2585]
**What I'd like:**
Have more robust mechanism when BR sets the hostname of the instance. Currently we have:

>Most users don't need to change this setting as the following defaults work for the majority of use cases. If this setting isn't set we attempt to use DNS reverse lookup for the hostname. If the lookup is unsuccessful, the IP of the node is used. 

If the reverse lookup fails then the IP is used as hostname, maybe we can also check EC2 (DescribeInstance or maybe IMDS `http://169.254.169.254/latest/meta-data/hostname`)?

I would also want to know are there any retries to the initial DNS reverse lookup? 

**Any alternatives you've considered:**

The reason why I open this issue is because we had a EKS cluster running on BR, and one our etcd members was not starting up, problem was that the issued cert (issued to the hostname) was not matching the current hostname of the machine (which was IP address, because the reverse DNS failed). We were thinking about adding a bootstrap container that will set the hostname by doing (DescribeInstance or checking with IMDS).

**Comment by cbgbt** [comment]
Thanks for cutting this issue!

> If the reverse lookup fails then the IP is used as hostname, maybe we can also check EC2 (DescribeInstance or maybe IMDS `http://169.254.169.254/latest/meta-data/hostname`)?

Good idea, this seems like a good idea for `aws` variants. I'll do a bit more looking to see if there are any gotchas with that approach.

> I would also want to know are there any retries to the initial DNS reverse lookup?

It seems like there aren't. We [don't perform retries on the Bottlerocket side](https://github.com/bottlerocket-os/bottlerocket/blob/b530f30850d58ad84a8b0ded2e08fa91d554c7a8/sources/api/netdog/src/cli/generate_hostname.rs#L22) and the `dns_lookup` crate does not either. I can take a look at adding retries, though we'll need to find some conservative medium so as to not hang up the boot process unnecessarily for environments where this is never expected to succeed.

**Comment by nkvetsinski** [comment]
Thanks for picking up this!

**Comment by alegermer** [comment]
Hello @cbgbt, thanks for looking at this, just checking if you already have any clearer feasibility and estimate info regarding this improvement to BR. We are seeing this issue manifesting more often than we expected so we are analyzing what are our short-term options.

**Comment by webern** [comment]
related? #2603

**Comment by cbgbt** [comment]
@nkvetsinski and @alegermer could you possibly elaborate on what symptoms you are seeing that prompted this issue?

I'm curious if @webern is correct in that #2603 is related, in which case using IMDS would still get us the hostname based on the private IP address of the instance, rather than a resource-based one.

**Comment by nkvetsinski** [comment]
@cbgbt I'm not sure if the two issues are related but in our setup we use `IP Name` as hostname type and we don't have `Enable resource name DNS A record on launch` enabled. What we observed was that the private DNS name (observed from EC2) was something like: `ip-10-0-4-6.us-west-2.compute.internal` however, the local hostname on the machine was `10.0.4.6` which lead us to believe there was an intermittent reverse DNS resolution failure and the IP address was used instead (as the docs point out).

**Comment by cbgbt** [comment]
I'm planning to include more robust hostname resolution in the next release of Bottlerocket (1.12). In the meantime I believe the workaround mentioned above may be the best way to protect against this issue:

> We were thinking about adding a bootstrap container that will set the hostname by doing (DescribeInstance or checking with IMDS).

**Comment by cbgbt** [comment]
A fix for this has been merged and should be included in Bottlerocket 1.12.
