### ISSUE TITLE
support serialize image pulls kubelet setting 

### ISSUE THREAD

**Issue by dschaaff** [bottlerocket-os/bottlerocket#2598]
**What I'd like:**
We'd like to be able to pass the [serializeImagePulls](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) setting to the kubelet.

**Any alternatives you've considered:**

We could build a custom AMI but that is a lot of overhead for this 1 settings.

**Comment by stmcginnis** [comment]
Hey @dschaaff - thanks for filing this request.

I was wondering if you could share a little more about what your goals are. The default kubelet setting is for this to be `true`, but for historical reasons Bottlerocket has this hardcoded to be `false`. I'll have to see if there is still a strong reason why we override that default, but understanding what you are trying to accomplish might help to justify that change.

Thanks!

**Comment by dschaaff** [comment]
🤦 Setting it to false is what I actually want. I read the setting wrong yesterday apparently. Apologies for the noise.

**Comment by stmcginnis** [comment]
Awesome - no worries. Glad it is actually what you need! 🎉
