### ISSUE TITLE
`sundog` should log stderr even if the generator process returns 0

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#2600]
`sundog` [doesn't log anything](https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/api/sundog/src/main.rs#L350) in the case a setting generator returns 0.

This means that setting generators don't have any way to log errors/warnings to a user, even in the case they can continue and finish properly.  

A good example of this is the generator for hostname: [`netdog generate-hostname`](https://github.com/bottlerocket-os/bottlerocket/blob/b530f30850d58ad84a8b0ded2e08fa91d554c7a8/sources/api/netdog/src/cli/generate_hostname.rs#L25).  The generator logs a message if the reverse DNS request for hostname fails, using the IP instead.  The failure message never gets logged to the journal.

**Comment by cbgbt** [comment]
A fix for this has been merged and should be included in Bottlerocket 1.12.
