### ISSUE TITLE
Updog: Report update jitter to caller

### ISSUE THREAD

**Issue by sam-aws** [bottlerocket-os/bottlerocket#264]
From https://github.com/amazonlinux/PRIVATE-thar/pull/186, Updog should calculate jitter for a given update, but should report the determined update time to the caller/coordinator instead of waiting itself.

**Comment by etungsten** [comment]
updog no longer jitters the update time within the host's wave as of https://github.com/bottlerocket-os/bottlerocket/pull/993.
