### ISSUE TITLE
Pass environment variables to containers

### ISSUE THREAD

**Issue by nkvetsinski** [bottlerocket-os/bottlerocket#2643]
**What I'd like:**
To be able to pass arbitrary environment variables to containers (host and bootstrap) the same why one can pass them in Kubernetes [PODs](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/) or in [Docker](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file).

**Any alternatives you've considered:**
Passing them in user-data.

**Comment by rpkelly** [comment]
Hi @nkvetsinski, thank you for bringing this up. I'm trying to understand the usecase you're trying to cover, and how it's not currently served by user-data. Could you please give me some examples on how that's the case?

**Comment by arnaldo2792** [comment]
Hey @nkvetsinski, could you please share more details about your use case and why isn't it covered by the host/bootstrap containers' user data?

**Comment by nkvetsinski** [comment]
Hey I don't have a specific use case in mind. At the time the issue was opened I was looking into how to pass some data to a host container. I asked a BR developer if env variables are supported and they suggested I open this issue, so that you guys can have look into potentially implementing it. 

In the end I unblocked myself with user data.

**Comment by arnaldo2792** [comment]
Nice! I think for most use cases user data is a good replacement for ENV variables, since a script can just parse the user data. I'll close this for now, and if by any chance there is a use case that user data doesn't cover, we can re-open the issue.
