### ISSUE TITLE
TestSys: Use long lived vSphere clusters

### ISSUE THREAD

**Issue by ecpullen** [bottlerocket-os/bottlerocket#2644]
It seems like we're precluding the use of long-lived test cluster fixtures here.
        For parity with EKS on AWS, I would expect to create a cluster control plane using the "production" builds from EKS-A, and then only use local Bottlerocket builds for the worker nodes.

_Originally posted by @bcressey in https://github.com/bottlerocket-os/bottlerocket/pull/2594#discussion_r1037528351_

**Comment by webern** [comment]
I think we've been doing this already and chosen to stop doing this.  this is outdated.
