### ISSUE TITLE
Document how BR customizations should be versioned/worked with

### ISSUE THREAD

**Issue by grosser** [bottlerocket-os/bottlerocket#2664]
**Problem**

We have a few custom packages and a custom variant in our fork.
Using a fork is not a very clean workflow since:
- it has tons of files that are not ours, including *.md and things like .github that are not ours
- it makes updating to a new version require big git merges/rebases which is not great

**What I'd like:**

Document how customization should be handled so everyone is on the same page and best-practices can be shared.

**Any alternatives you've considered:**

Did not see any docs on this.

**Comment by cbgbt** [comment]
Thanks for raising this issue, it's exciting to read about your use-case for Bottlerocket and it's a use-case that we've been chatting about how to better-support. I've opened #2669 which we want to us as a sort of tracking issue for the overall idea we have for better-enabling custom variants.

It would be really great to engage with you as we work towards a solution to make sure that our work is benefiting you. If you have any specific questions or recommendations regarding your setup today, we can discuss those further in this issue. In the meantime, we'll make sure progress related to the idea is referenced from #2669!

**Comment by grosser** [comment]
closing since that issue captures the problem well
