### ISSUE TITLE
Use the SDK for Linting

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#2704]
If we use the local installs of Go and Cargo/Rust to lint the code, we risk breaking every time the compiler updates and we risk having conflicting lints between GitHub actions and developers' local builds. This is especially true with clippy which aggressively adds lints with each update.

We should use the SDK toolchains to perform these lints so that we control the time at which lints change (i.e. when we update the SDK).

>      This is why we should be linting with the SDK tool chains instead of locally installed tool chains. Linting rules should only change when we update the SDK.

_Originally posted by @webern in https://github.com/bottlerocket-os/bottlerocket/issues/2701#issuecomment-1372344522_

**Comment by bcressey** [comment]
We do use the SDK for Go and ShellCheck lints currently; it's just `cargo` that gets a pass, since we know it's required as a build tool.
