### ISSUE TITLE
v1.13.0 Update and release bottlerocket SDK

### ISSUE THREAD

**Issue by jpmcb** [bottlerocket-os/bottlerocket#2766]
For v1.13.0, if necessary, and as we approach a code freeze date, let's update and release the Bottlerocket SDK to capture any security fixes and upgrades

**Comment by jpculp** [comment]
In-progress:
https://github.com/bottlerocket-os/bottlerocket-sdk/pull/95
https://github.com/bottlerocket-os/bottlerocket-sdk/pull/93
https://github.com/bottlerocket-os/bottlerocket-sdk/pull/92
and more!

**Comment by jpculp** [comment]
Done!
