### ISSUE TITLE
question: how to try SOCI snapshotter with bottlerocket

### ISSUE THREAD

**Issue by tuananh** [bottlerocket-os/bottlerocket#2788]
i see that bottlerocket let you pass a TOML configuration file in as user-data. how about adding additional binaries (soci) into it?

https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-EKS.md#launch

**Comment by tuananh** [comment]
after reading the documentation for a bit, i think what i need to do is

- create a new package in `./packages` folder
- create a new build variant and build it

can someone please correct me if i'm wrong?

**Comment by stmcginnis** [comment]
Hi @tuananh! Yes, to add a binary to the system it would need to be included as a package under the `packages` folder. You wouldn't necessarily need to create a new variant to include it. It could be included in the existing variants.

Can you describe a little bit about what you're trying to do, or what use case you are trying to address with SOCI?

**Comment by tuananh** [comment]
> Hi @tuananh! Yes, to add a binary to the system it would need to be included as a package under the `packages` folder. You wouldn't necessarily need to create a new variant to include it. It could be included in the existing variants.
> 
> Can you describe a little bit about what you're trying to do, or what use case you are trying to address with SOCI?

I want to use soci snapshotter with bottlerocket. Given the status of soci snapshotter are not quite ready yet, i think a new variant will make more sense?

**Comment by webern** [comment]
Currently one would need to make changes to a Bottlerocket fork, adding a package as you described. For just trying it out, it would be easier to alter an existing variant than creating a new one (there is a lot of boilerplate).

We are tracking a project for making these types of customizations easier in the future, the issue can be found here: #2669

**Comment by stmcginnis** [comment]
Hi @tuananh, just wondering if there was anything else needed with this issue or if it should be closed. Thanks!

**Comment by tuananh** [comment]
@stmcginnis I'm good now. Thank you.
