### ISSUE TITLE
`host-ctr`: launched process namespace tracking via json file

### ISSUE THREAD

**Issue by jpmcb** [bottlerocket-os/bottlerocket#2796]
### What I'd like:

I want to be able to read a file on the bottlerocket system that lists the PID namespaces of current host-containers. This way, via my own admin container or host container, I can monitor the currently running host containers and audit kernel events solely based on those PID namespaces.

**Proposal**: When host containers are launched via `host-ctr`, we could update a well known json file on the host with the PID namespaces of running host-containers.

This file could be placed in a well known location:

```
/var/lib/bottlerocket/host-container/container-namespaces.json
```

[similar to how `application.json` is populated in host-ctr for the RPM inventory.](https://github.com/bottlerocket-os/bottlerocket/blob/756f33c8f72bd8a78d9e8f41fb76a53eecc3df3d/sources/host-ctr/cmd/host-ctr/main.go#L731-L736)

This can be made available to running host-containers as a mount and also added as a link to a top level location:

```
/.bottlerocket/container-namespaces.json
```

This way, the file is easily accessible to _both_ host-containers with the mount and as system level packages down the road.

When containers stop, we would also want to update the json file to prevent any "dangling" PID namespaces that no longer have running host-containers.

Something else to keep in mind: when Bottlerocket goes through a reboot, containers are stopped and restarted. This "host container PID namespaces" file should likely _not_ be kept in persistent storage since it is directly tied to the running state of bottlerocket, not necessarily the state of the _image_.

### Any alternatives you've considered:

N/a - would love feedback from the community on this proposal!

I could also use some guidance on how we would anticipate these files to land on the system. Does the above proposed filepaths make sense?

**Comment by bcressey** [comment]
> This file could be placed in a well known location

It would be better to place this in `/etc` where it's ephemeral and where it'll be protected by SELinux labels from unexpected modification.

> This can be made available to running host-containers as a mount

This should be mounted via its parent directory rather than a direct bind-mount of the file; otherwise changes won't be picked up unless the file is modified in place.

**Comment by arnaldo2792** [comment]
> audit kernel events solely based on those namespaces.

Do you mean processes' namespaces or containerd's namespaces? (This is just for my own understanding)

Will this file be mounted to all host containers? (superpowered and non-superpowered)?

Just a heads up: the new json file wouldn't be available to bootstrap containers, since the host containers are started at a later stage in the boot process when all the bootstrap containers are done.

**Comment by jpmcb** [comment]
Good questions!

> Do you mean processes' namespaces or containerd's namespaces? (This is just for my own understanding)

Yes, each individual processes' namespace.

Monitoring only the containerd namespace wouldn't deterministically allow a piece of monitoring software to filter kernel events from individual host-containers. It would only be able to filter kernel events from the host-containerd namespace. 

> Will this file be mounted to all host containers? (superpowered and non-superpowered)?

Hmm, probably only "super" containers since linux kernel event monitoring is typically a super user operation.

> Just a heads up: the new json file wouldn't be available to bootstrap containers, since the host containers are started at a later stage in the boot process when all the bootstrap containers are done.

Gotcha! Thanks for the callout - I think that's fine. If there are no host-containers during the bootstrap container's operation then there wouldn't be anything in that file anyways.

**Comment by arnaldo2792** [comment]
One more question, but why do we need the namespaces? Isn't it sufficient to know the PID of the host container process to figure out its namespaces, and with that information figure out siblings of the process if needed?

**Comment by etungsten** [comment]
> Isn't it sufficient to know the PID of the host container process to figure out its namespaces

I think it can be either or.

@jpmcb earlier mentioned:
> Hmm, probably only "super" containers since linux kernel event monitoring is typically a super user operation.

Which means the monitoring agent running in the host container can access all this information by default since it shares the same host PID namespace.

So maybe this really is only useful for the "system level packages down the road." mentioned in the issue?

**Comment by jpmcb** [comment]
> So maybe this really is only useful for the "system level packages down the road." mentioned in the issue?

Right - we don't want to prevent a future monitoring package that we pull in via `packages/` and build into the OS itself to not be able to access that information.

**Comment by etungsten** [comment]
Closing this issue since we've found a path forward for monitoring agents running in host-containers to determine what processes to monitor.
