### ISSUE TITLE
`aws-iam-authenticator` for baremetal variant

### ISSUE THREAD

**Issue by rpkelly** [bottlerocket-os/bottlerocket#2823]
### Discussed in https://github.com/bottlerocket-os/bottlerocket/discussions/2809

<div type='discussions-op-text'>

<sup>Originally posted by **StefanTheWiz** February 15, 2023</sup>
Hi!

I'm trying to use AWS EKS as the control plane with bottlerocket baremetal nodes.
I was wondering if there was a particular reason why `aws-iam-authenticator` is not included in baremetal variant?

Based on the [README](https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md), I was kinda expecting that it would be included (for instance for using IAM Roles Anywhere).
> To start, we're focusing on the use of Bottlerocket as a host OS in AWS EKS Kubernetes clusters and Amazon ECS clusters.

As an experiment, I've built a version of baremetal that has the `aws-iam-authenticator` (diff [here](https://github.com/StefanTheWiz/bottlerocket/commit/65f1737fd37cbe0d12cb33a59de65a021cc37cc1)).
However, the update process might remove the authenticator, which might mean maintaining our own TUF repo and that would be a tough sell.</div>

**Comment by rpkelly** [comment]
Documentation currently says this concerning authentication:

> settings.kubernetes.authentication-mode: Which authentication method the kubelet should use to connect to the API server, and for incoming requests. Defaults to aws for AWS variants, and tls for other variants.

It does not currently mention if  `aws` is not supported in those other variants, just that it's not the default.

**Comment by bcressey** [comment]
The mechanics of adding the package are straightforward, but I need a better understanding of the security implications of this to form an opinion on whether this is a good idea. I'll reach out to some folks internally.

**Comment by StefanTheWiz** [comment]
> The mechanics of adding the package are straightforward, but I need a better understanding of the security implications of this to form an opinion on whether this is a good idea. I'll reach out to some folks internally.

Hi. Any updates on this? :)

**Comment by StefanTheWiz** [comment]
Still a blocker... 👎

**Comment by stmcginnis** [comment]
Sorry for the delay on updates here. I know there are some possible security concerns with including `aws-iam-authenticator` for metal variants. I know there were some reviews being requested with some AWS security folks to provide more details, but unfortunately I don't have an update on where that process stands. I will reach out to some folks and see if we can get any updates.

**Comment by cbgbt** [comment]
@StefanTheWiz thanks for your patience here. @yeazelm has merged `aws-iam-authenticator` which should be available in Bottlerocket 1.15.0, tracked in https://github.com/bottlerocket-os/bottlerocket/issues/3169

Would you mind giving this a shot and checking that it resolves your issues?

**Comment by yeazelm** [comment]
This was released in the 1.15.0 release

**Comment by StefanTheWiz** [comment]
Thanks! I'll check it out soon and let you know
