### ISSUE TITLE
Install SSM Agent on Amazon EKS BottleRocket

### ISSUE THREAD

**Issue by riqueps** [bottlerocket-os/bottlerocket#2841]
**Image I'm using:**
EKS AMI: bottlerocket-aws-k8s-1.22-x86_64-v1.12.0-6ef1139f

**What I expected to happen:**
I'm trying to setup [SSM Agent ](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/install-ssm-agent-on-amazon-eks-worker-nodes-by-using-kubernetes-daemonset.html) on bottlerocket eks nodes.

**What actually happened:**
The Pods are not able to find the cron.d path

`Warning  FailedMount  10m (x3 over 17m)     kubelet            Unable to attach or mount volumes: unmounted volumes=[cronfile], unattached volumes=[kube-api-access-dgrkg cronfile]: timed out waiting for the condition
  Warning  FailedMount  2m20s (x23 over 32m)  kubelet            MountVolume.SetUp failed for volume "cronfile" : hostPath type check failed: /etc/cron.d is not a directory`

**How to reproduce the problem:**
Create a EKS cluster 1.22 with AMI  bottlerocket-aws-k8s-1.22-x86_64-v1.12.0-6ef1139f then try to install SSM Agent.

**Comment by stmcginnis** [comment]
Hi @riqueps - the SSM agent is already installed on the `aws-k8s-*` variants. Can you tell me what it is you are trying to accomplish?

**Comment by riqueps** [comment]
Hi @stmcginnis 
EKS nodes are not appearing on AWS Systems Manager > Fleet Manager on AWS Console and on Ec2 menu I can't connect via SSM

**Comment by stmcginnis** [comment]
Hmm, I am not able to reproduce this. I have an `aws-k8s-1.24` cluster deployed. My Bottlerocket instance shows up right away in AWS Systems Manager > Fleet Manager:

![image](https://user-images.githubusercontent.com/3922475/222467915-40566cd8-792b-4226-93b6-0418abe85c7c.png)

This is 1.24, and you are using 1.22, but that shouldn't make any difference. Both variants use the same SSM agent package.

Can you tell me a little more about how you are deploying these nodes? Mine were done using `eksctl`. I'm wondering if there might be some difference when deploying another way.

**Comment by riqueps** [comment]
I deployed it with Pulumi, using the [AWS Classic](https://www.pulumi.com/registry/packages/aws/) package, it uses  AWS SDK behind the scenes and I didn't enabled ssh

I created with these parameters:
```
--node_group_name NODEGROUP_NAME
--cluster_name CLUSTER_NAME
--ami_type = 'BOTTLEROCKET_x86_64'
--node_role_arn = MY_NODE_ROLE
--subnet_ids = SUBNET_IDS
--scaling-config  desired_size = 2, max_size = 2,min_size = 1
```

**Comment by stmcginnis** [comment]
Unfortunately I don't know enough about Pulumi. I have a hunch though.

If you look at your instances in the EC2 console, do the nodes that are created in this way have a value that shows up in the Name column? I seem to remember hearing somewhere that SSM inventory may skip nodes that do not have a name set.

**Comment by riqueps** [comment]
Hum, it does not have it. I'll test it
Do you know if there is any specific policy that I must attache on node roles?

**Comment by stmcginnis** [comment]
> Do you know if there is any specific policy that I must attache on node roles?

I don't believe so. For the name, if you select the instance in the EC2 console, then down below click on the Tags tab. Under there you can click on Manage Tags, then add a new one where the Key = "Name" and the Value = whatever the name should be for the node.

I couldn't find any docs on the parameters you gave above. Might be worth checking if there are any name or tag related arguments you can provide so it automatically adds this name tag.

**Comment by riqueps** [comment]
About the parameter I sent to you, is from [aws cli eks create-nodegroup](https://docs.aws.amazon.com/cli/latest/reference/eks/create-nodegroup.html)

Maybe could be the instance profile?  The Ec2 nodes is using Roles instead if Instance profile.

About the Tags, I added the Key="Name" , but still not appearing on Fleet Manager

![image](https://user-images.githubusercontent.com/47371890/222544626-21700ef7-2680-4a0e-b256-dfec05a3533e.png)

**Comment by stmcginnis** [comment]
I believe there is a delay in SSM reporting, so it may not be an immediate result. You may be able to restart the instance to get the service to come up and report right away.

There are also some SSM troubleshooting steps listed here: https://docs.aws.amazon.com/systems-manager/latest/userguide/troubleshooting-managed-instances.html

It does appear there are some IAM instance role requirements, but as far as I know the defaults should work fine. But check out the info from that link above to verify your settings in case this method of creating nodes doesn't do things quite the same way.

Another thing you can try is go to Instances in the EC2 console. Select the node and click on Connect. It should give you the option to connect via Session Manager. If it does not enable the Connect button there, that would be an indication the ssm agent is not running. That typically only happens if there is a boot failure. If you are able to connect, then you can run the commands `enter-admin-container` to connect to the admin container, then `sheltie` to get a system level prompt. From there, you could try something like `journalctl | grep ssm` to see if there are any interesting logs.

**Comment by riqueps** [comment]
humm, I see.
I'll create a cluster using eksctl and then check what is the difference between both, then I share here my findings.

**Comment by riqueps** [comment]
@stmcginnis., finally I got it working
It was necessary 3 things to work:
- Attach AmazonSSMManagedInstanceCore policy to the nodes role
- Tag the node, like you said (Key = "Name" and Value = "Some Value")
- Reboot the node.

**Comment by stmcginnis** [comment]
Awesome, thanks for reporting back @riqueps! Really great to have this detail captured here.

**Comment by KshitijKanse** [comment]
Hi Team,

I am facing this problem after implementing the above steps:
1) Attach AmazonSSMManagedInstanceCore policy to the nodes role
2) Tag the node, like you said (Key = "Name" and Value = "Some Value")
3) Reboot the node.


SSM Agent is not online
The SSM Agent was unable to connect to a Systems Manager endpoint to register itself with the service.

<img width="1860" height="502" alt="Image" src="https://github.com/user-attachments/assets/9e385390-2994-49a2-a540-283471aca41e" />

**Comment by vigh-m** [comment]
Can you tell me a little more about how you are deploying these nodes? Do you see any error logs when checking the console logs(system logs) of the instance on EC2?
