### ISSUE TITLE
support all resource limits in settings.oci-defaults

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#2862]
**What I'd like:**
I'd like to be able to set the default values for all resource limits, not just [max-open-files](https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/models/src/modeled_types/oci_defaults.rs#L91).

**Any alternatives you've considered:**
See past discussion in #1703 - there's just not another good way to adjust these settings right now since they can't be set via pod specs.

**Comment by vyaghras** [comment]
Resolved by [#3206](https://github.com/bottlerocket-os/bottlerocket/pull/3206) pull request.
