### ISSUE TITLE
GItHub workflow step check-clippy stalls occasionally

### ISSUE THREAD

**Issue by markusboehme** [bottlerocket-os/bottlerocket#2870]
I just observed the GitHub workflow doing test builds upon a PR stall on the `check-clippy` step for 2/37 builds on #2864. PR #2850 is another one for which `check-clippy` partially stalled.

For #2864, I cancelled the workflow after more than 1.5 hours had elapsed without visible progress. The last log entries for the step are:

```
+ docker run --rm -v /home/runner/work/bottlerocket/bottlerocket:/tmp public.ecr.aws/bottlerocket/bottlerocket-sdk-x86_64:v0.30.2 cargo clippy --manifest-path /tmp/tools/Cargo.toml --locked -- -D warnings --no-deps
    Updating git repository `[https://github.com/bottlerocket-os/bottlerocket-test-system`](https://github.com/bottlerocket-os/bottlerocket-test-system%60)
    Updating crates.io index
```

This appears to happen randomly, i.e. I know of no reproduction steps.

**Comment by mjsterckx** [comment]
Should be resolved now that https://github.com/bottlerocket-os/bottlerocket/pull/2868 is merged.
