### ISSUE TITLE
containerd with pigz

### ISSUE THREAD

**Issue by ohkinozomu** [bottlerocket-os/bottlerocket#2886]
Hi, I work on improving image pull performance in bottlerocket.

containerd has the ability to speed up decompression with pigz ( https://github.com/containerd/containerd/pull/2640 ).
Is it already enabled in containerd in bottlerocket?
If not, is it possible to enable it?

**Comment by yeazelm** [comment]
Thank you for filing this issue @ohkinozomu! I did a quick check and from what I can tell, it looks like we don't have `pigz` enabled. This could be a great addition to improve container pull times. From that [containerd PR](https://github.com/containerd/containerd/pull/2640) it looks like it should be a matter of adding `pigz` to the OS and in theory containerd should just start using it. This might be a great first package update for anyone that is interested!
