### ISSUE TITLE
broken link on packing link to https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kernel-5.4

### ISSUE THREAD

**Issue by FireballDWF** [bottlerocket-os/bottlerocket#2909]
https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md contains broken link to https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kernel-5.4 from within Linux kernel ([background](https://en.wikipedia.org/wiki/Linux), [packaging](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kernel-5.4))

**Comment by stmcginnis** [comment]
Thanks - good catch! Looks like this was never updated when things moved to the 5.10 and 5.15 kernels.
