### ISSUE TITLE
Add integration test for webpki-roots-shim error cases

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket#293]
...

Writing a small binary that can be used to test this as part of integration tests is probably a good idea.

_Originally posted by @iliana in https://github.com/amazonlinux/PRIVATE-thar/pull/287_

**Comment by stmcginnis** [comment]
Need to investigate if we can get rid of the shim now. Possibly using https://github.com/rustls/rustls-native-certs?
