### ISSUE TITLE
Add in support for the --memory-manager-policy flag?

### ISSUE THREAD

**Issue by diranged** [bottlerocket-os/bottlerocket#2977]
**What I'd like:**

https://github.com/bottlerocket-os/bottlerocket/pull/1659 helps us use the topology manager - but it's real power comes with the 
 [memory manager](https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/) flags. Can we have these added in so that we have parity with the `--cpu-manager-policy` flags?

**Comment by stmcginnis** [comment]
Thanks for bringing this up @diranged. I'm just starting to look in to this, but can you confirm - it looks like the only thing missing right now is (`memoryManagerPolicy` in the KubeletConfiguration)[https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/]. Is that your understand as well? Any other flags that need to be set?

**Comment by stmcginnis** [comment]
Looks like perhaps `reservedMemory` too.

**Comment by diranged** [comment]
I think that you already handled `reservedMemory` in the kubelet config?

**Comment by stmcginnis** [comment]
I don't think so. I'm looking at the example in the docs:

```
--feature-gates=MemoryManager=true
--kube-reserved=cpu=4,memory=4Gi
--system-reserved=cpu=1,memory=1Gi
--memory-manager-policy=Static
--reserved-memory '0:memory=3Gi;1:memory=2148Mi'
```

The feature gate is enabled by default with 1.22 and later, so nothing should need to be done there.

I believe `--kube-reserved` corresponds to the [`kubeReserved` kubelet config](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kubernetes-1.24/kubelet-config#L61-L72).

And `--system-reserved` is covered with the [`systemReserved` settings](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/kubernetes-1.24/kubelet-config#L73-L78).

That would leave `memoryManagerPolicy` (`--memory-manager-policy`) if set to `static` and `reservedMemory` (`--reserved-memory`) with the list of [`MemoryReservation` settings](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-MemoryReservation).

At least that's what I'm interpreting so far. I haven't had to use these settings elsewhere yet, so still trying to parse through the various docs to understand it well enough.

**Comment by diranged** [comment]
Thank you for quickly hopping on this.. it's not super urgent for us, but we'd love to see this feature in an upcoming release. Much appreciated!
