### ISSUE TITLE
v1.14.0 🐬 tracking issue

### ISSUE THREAD

**Issue by stmcginnis** [bottlerocket-os/bottlerocket#2993]
Hello! This is a _"living"_ issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.14.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [**_anything is subject to change_**](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), _**this isn't a guarantee**_ anything will _actually_ land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub `/compare` feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.13.x` branch and `develop` (the latest changes that will eventually land in the `1.14.x` branch).

---

### Release captains 🧑‍✈️ 

@stmcginnis 

### Targeting 🎯 

- [ ] ~https://github.com/bottlerocket-os/bottlerocket/issues/2501~ - deferred to next release
- [ ] ~#2731~ - deferred to next release
- [ ] #3046 

### Maintenance 🔧 

- [x] #2994
- [x] #2995
- [x] #2996
- [x] #2997
- [x] #2998

**Comment by jpmcb** [comment]
Available release here: https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.14.0
