### ISSUE TITLE
:loudspeaker: AWS Bottlerocket Variants on EC2 Instances with 1vCPU may fail to boot

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket#3025]
We’ve discovered an issue where AWS Bottlerocket variants version 1.13.0 or later can fail to boot on EC2 instance types with only a single vCPU. This issue occurs in some cases due to a race condition in data volume management during the boot sequence. This race condition can only occur during the first boot sequence, so any existing instances should not be affected by this issue. The Bottlerocket team has fixed the issue, which was originally reported in #2980, which will be released in an upcoming version of Bottlerocket.

## How do I know if I’m affected?

If you use Bottlerocket version 1.13.0 or higher and are using EC2 instance types with a single vCPU, you may observe that some newly-launched EC2 instances launched with this configuration never become healthy.

The list of affected instance types are as follows:

* a1.medium
* c6g.medium
* c6gd.medium
* c6gn.medium
* c7g.medium
* is4gen.medium
* m1.small
* m1.medium
* m3.medium
* m6g.medium
* m7g.medium
* m6gd.medium
* r6g.medium
* r6gd.medium
* r7g.medium
* t1.micro
* t2.nano
* t2.micro
* t2.small
* x2gd.medium

## How should I remediate this?
In-place updates (for example, using Bottlerocket’s Update Operator or ECS Updater) of Bottlerocket from 1.12.0 to 1.13.0 or later will not be impacted by this issue.

A few options exist to remediate this issue until a new version of Bottlerocket is released:

* If it is compatible with your workloads, you may launch your instances using Bottlerocket 1.12.0. You can do that by using SSM parameters to select the appropriately versioned AMI ID, and then configuring your Bottlerocket nodes to launch with that AMI:

```
$ VARIANT=aws-k8s-1.25
$ REGION=us-west-2
$ ARCH=x86_64  # or aarch64
$ aws ssm get-parameter \
  --region $REGION \
  --name "/aws/service/bottlerocket/$VARIANT/$ARCH/1.12.0/image_id" \
  --query Parameter.Value \
  --output text
```

* You may terminate any unhealthy instances and attempt to re-launch again. Once an instance is healthy, it will not degrade.
* You temporarily can use EC2 instance types with more than one vCPU.

**Comment by jpmcb** [comment]
Resolved in v1.13.3. See release notes:
https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.13.3
