### ISSUE TITLE
br_netfilter kernel module needed for kubeadm - change in bridge kernel module

### ISSUE THREAD

**Issue by tommie** [bottlerocket-os/bottlerocket#3052]
**Image I'm using:** metal-k8s-1.26-v1.13.2

**What I expected to happen:** `kubeadm init` runs happily.

**What actually happened:** The preflight check `bridge-nf-call-iptables` fails with `/proc/sys/net/bridge/bridge-nf-call-iptables does not exist`

**How to reproduce the problem:** Pretty much any invocation of `kubeadm init` should cause this.

The check was added here: https://github.com/kubernetes/kubernetes/commit/fb4ee4debafce916e3b17ac20707e1fa1bb94630

IIRC, kubeadm does this check because Kubelet uses that proc entry, but I'm not sure.

The problem is that the `bridge` module requires `br_netfilter`: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/bridge/br.c#n424

Confirmed the kmod kit says [`CONFIG_BRIDGE_NETFILTER=m`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/Kconfig#n188) for v1.13.3. I can't say if this module should be loaded by default, or simply modified to `y`.

(I'm also surprised no one else has hit this preflight check before me, so I might have missed something elsewhere...)

**Comment by stmcginnis** [comment]
Thanks for filing this @tommie. Typically Bottlerocket is only used as a worker node, so I don't think it is common for someone to be running `kubeadm init`. Just out of curiosity, can you describe a little more how you are using Bottlerocket as the control plane? Are you spinning up your own cluster manually?

**Comment by tommie** [comment]
I should really try to figure out why kubeadm wants this. IIRC, it was actually for Kubelet, but it's possible it's for the control plane. My notes don't say, sadly.

I'm building a script to bootstrap a cluster from scratch on Hetzner Cloud/Robot. K8s is complicated enough that I want to document it in a script, instead of just following someone's how-to. My use-case is a really small cluster with just two nodes or so. Pretty much, I just want to move away from my servers being "precious", and orchestrate everything with K8s, even if it's a small workload. The idea is to create a system that is easy to bootstrap, but also easily extensible.

I recently worked with a client that was running a Windows server with MS SQL and some pretty horrible DevOps practices. It would have been so awesome to just say "here is a cheap two-node K8s cluster, now let's focus on CI/CD instead of petting the Windows server for every release."

And yes, I like bare metal. I'm not a managed-k8s type of person. ;)

**Comment by stmcginnis** [comment]
Awesome, that sounds really interesting @tommie! Great approach.

**Comment by arnaldo2792** [comment]
Hi @tommie, you can use a bootstrap container to load kernel modules, you can use a Dockerfile as follows:

```bash
FROM alpine
ENTRYPOINT ["chroot", "/.bottlerocket/rootfs", "modprobe", "br_netfilter"]
```

**Comment by tommie** [comment]
Hi. Yes, that's the way I'm doing it currently.

Since Bottlerocket OS is about running Kubernetes, I found it odd that I have to build a boot container for it.

https://github.com/bottlerocket-os/bottlerocket/discussions/3050 is related.

**Comment by stmcginnis** [comment]
Arnaldo's answer is the answer for now, so going to close this as any improvement is being tracked in #3050 (and this is now linked to that issue for visibility). Thanks!

**Comment by tommie** [comment]
SG. I forgot to get back to you on why `br_netfilter` is needed.

As said, Kubeadm has a preflight check for `/proc/sys/net/bridge/bridge-nf-call-iptables`: https://github.com/kubernetes/kubernetes/blob/c056c36e237c546690f9a375bd913fe3c4838c34/cmd/kubeadm/app/preflight/checks_linux.go#L65
This is managed by that module since ~2013.

It is used by kube-proxy: https://github.com/kubernetes/kubernetes/blob/6d7b0b527df114483e2d1ccf03d812b0e279e3ac/pkg/proxy/iptables/proxier.go#L260

There's a comment saying

```go
	// Proxy needs br_netfilter and bridge-nf-call-iptables=1 when containers
	// are connected to a Linux bridge (but not SDN bridges).  Until most
	// plugins handle this, log when config is missing
	if val, err := sysctl.GetSysctl(sysctlBridgeCallIPTables); err == nil && val != 1 {
		klog.InfoS("Missing br-netfilter module or unset sysctl br-nf-call-iptables, proxy may not work as intended")
	}
```

And the same for the `ipvs` backend: https://github.com/kubernetes/kubernetes/blob/6d7b0b527df114483e2d1ccf03d812b0e279e3ac/pkg/proxy/ipvs/proxier.go#L336

I think

1. If this module is needed, it's likely needed on all nodes where kube-proxy runs, and
2. depending on the network configuration, kube-proxy doesn't always need it.

So it seems reasonable to not load it by default, and hence that #3050 is the way forward.
