### ISSUE TITLE
Disable IPv6 - how to do this

### ISSUE THREAD

**Issue by Constantin07** [bottlerocket-os/bottlerocket#3058]
**What I'd like:**
I would like to disable IPv6 in Bottlrocket OS (1.13.2) with AWS EKS.
IPv6 is not enabled in VPC or at subnet level but from the pod logs I see that kubelet attempts to run liveness checks against IPv6 loopback which container is not listening to and it fails leading to container restarts.

I couldn't find how to do this in this repo.

**Any alternatives you've considered:**
Instruct kubelet to use ipv4 only ?

**Comment by jbg** [comment]
Setting these sysctls in user data ought to do it, assuming nothing in bottlerocket itself requires IPv6:

```
[settings.kernel.sysctl]
"net.ipv6.conf.all.disable_ipv6" = "1"
"net.ipv6.conf.default.disable_ipv6" = "1"
```

**Comment by stmcginnis** [comment]
Jasper's instructions look correct 🎉 , so I'm going to assume everything is good here and close out this issue. If you run in to any problems with this, please feel free to reopen or file a new one. Thanks!
