### ISSUE TITLE
Set net.unix.max_dgram_qlen for containers from the system-value...

### ISSUE THREAD

**Issue by diranged** [bottlerocket-os/bottlerocket#3059]
**What I'd like:**

Currently we can set `net.unix.max_dgram_qlen` in the Sysctl settings for the bottlerocket node on startup - however, that value is not propagated to the underlying containers when they start. They start up with `net.unix.max_dgram_qlen: 10` no matter what. I'd like to see an ability for us to tune `net.unix.max_dgram_qlen` for our containers.

One simple approach is to set the `net.unix.max_dgram_qlen` value in https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/containerd/containerd-cri-base-json based on whatever the user supplies to the `settings.kubernetes.sysctl` bottlerocket settings.

Another approach is to have a dedicated setting section for `settings.containerd.sysctl`, and allow us to set our settings there (at our own risk).

**Any alternatives you've considered:**

The only other alternative I've found is to try to use the CalicoCNI to modify settings on startup of containers via the `tuning` plugin .. however the Tigera Operator doesn't yet (https://github.com/projectcalico/calico/issues/5886#issuecomment-1098530412) support that.

**Comment by bcressey** [comment]
It'd be nice to template this and expose it as `settings.oci-defaults.sysctl`, possibly as part of the work on #2862 since the same code paths are involved.

**Comment by diranged** [comment]
@bcressey Is there any chance your team can share a target ETA for this feature? We are struggling internally with the default values for sending UDP/UDS packets.

**Comment by vyaghras** [comment]
> Is there any chance your team can share a target ETA for this feature? We are struggling internally with the default values for sending UDP/UDS packets.

@diranged  We are planning to start on this soon.

**Comment by bcressey** [comment]
@diranged tested an early version of this change and ran into trouble with [runc's validation logic](https://github.com/opencontainers/runc/blob/ba58ee9c3b9550c3e32b94802b0fb29761955290/libcontainer/configs/validate/validator.go#L150).

For this to be useful or safe, what we'd like is for runc to either always apply the sysctls, or skip them whenever they'd touch a host namespace while warning about non-namespaced sysctls, but that's not how runc does it:
* IPC related sysctls are only allowed when the container has a new IPC namespace
* network related sysctls are only allowed when the container has a new network namespace
* hostname / domainname sysctls are only allowed when the container has a new UTS namespace
* other sysctls are not allowed at all and cause an error

So I have to retract my above comment - I don't think `settings.oci-defaults.sysctl` is a good idea in the face of these restrictions, and we need to find some other way to let this setting be tuned.

**Comment by diranged** [comment]
@bcressey I agree with your assessment - this doesn’t seem like it fixes the root problem, and introduces significant risk to the operator.

One option would be for Bottlerocket to install and manage the `tuning` CNI plugin itself?
Another option is to just do some tuning of the kernel defaults by patching the kernel at build time.

**Comment by markusboehme** [comment]
> Another option is to just do some tuning of the kernel defaults by patching the kernel at build time.

I posted #3139 doing that. The default value hasn't been touched in ~20 years (or potentially more, Linux' Git history is limited, and I didn't go to the backfilled pre-2005 parts of it), bumping it seems in order.

For the issue at hand, the proposed PR unfortunately falls short of making this configurable. Making new network namespaces inherit the host's value seemed more natural in my opinion, but 1) it's a stronger change from current behavior and 2) there's no unified behavior for per-namespace settings (some get reset, others get inherited). I'll bring up the topic upstream. Would the bumped default value solve your problem?

**Comment by markusboehme** [comment]
The change has been released with [Bottlerocket v1.14.1](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.14.1).
