### ISSUE TITLE
Bottlerocket 1.13.4 runc 1.1.6 excessive logging "Path does not exist"

### ISSUE THREAD

**Issue by hajdukda** [bottlerocket-os/bottlerocket#3063]
After an update to latest bottlerocket os version (automatic using update operator)

We have noticed our clusters suddenly started generating tens of gbs of excessive logs related to ""Path does not exist""

Seems the becaused by missing verbose level that was fixed here: https://github.com/kubernetes/kubernetes/pull/112650

Related issue: https://github.com/kubernetes/kubernetes/issues/112124

When do we expect a fix for that ? or is there a plan to revert to previous version of runc ?

There seem to also be a memory and CPU issue caused by the upgrade also.

**Comment by stmcginnis** [comment]
Hi @hajdukda - this update has already [been reverted](https://github.com/bottlerocket-os/bottlerocket/pull/3054) and a new release is in the works. I can't give an exact timeframe, but it should be "very soon".

**Comment by yeazelm** [comment]
I believe this is the same #3057 and as @stmcginnis stated, we are working on a new release to revert this change.

**Comment by stmcginnis** [comment]
This revert has been released, closing this issue.
