### ISSUE TITLE
NVIDIA char devices deleted after a while or after systemctl reload

### ISSUE THREAD

**Issue by arnaldo2792** [bottlerocket-os/bottlerocket#3072]
**Image I'm using:**
Any NVIDIA variant

**What I expected to happen:**
The NVIDIA char devices shouldn't be deleted after `systemctl reload`. This is related to a known bug in NVIDIA container toolkit (see https://github.com/NVIDIA/nvidia-docker/issues/1671). 

**What actually happened:**
I wasn't able to execute `nvidia-smi` after I ran `systemctl daemon-reload` 

```bash
bash-4.2# nvidia-smi
Failed to initialize NVML: Unknown Error
bash-4.2#
```

**How to reproduce the problem:**
In any NVIDIA variant, deploy a pod that requests NVIDIA GPUs. Run `systemctl daemon-reload`, and then attempt to run `nvidia-smi` from the pod. You will see the error message above.

As mentioned, this is a known issue. The solution is to run `nvidia-ctx`, provided by the `nvidia-container-toolkit`, after boot or with a udev rule. Additionally, the k8s-device-plugin must pass `--pass-device-specs`, as stated [here]

[here]: https://github.com/NVIDIA/nvidia-docker/issues/1671#issuecomment-1532305701

**Comment by kolyshkin** [comment]
AFAIK, using runc => 1.1.7 (with [this fix](https://github.com/opencontainers/runc/pull/3845)) AND systemd >= v240 should fix the issue.
