### ISSUE TITLE
Update Nvidia driver to 525

### ISSUE THREAD

**Issue by ElTestigo** [bottlerocket-os/bottlerocket#3085]
**What I'd like:**
Update bottlerocket to version 525 (or at least make it an option) of the NVIDIA driver.  
Nvidia 525 now includes support for CUDA 12.0+ 

**Any alternatives you've considered:**
I have tried making a variant in Nvidia 525 to update the driver but I am having too many issues to make it work with EKS.

**Please note that the Firmware gsp installation it is now changed for 525.**
"GSP firmware is now distributed as multiple firmware files: this release has gsp_tu10x.bin and gsp_ad10x.bin replacing gsp.bin from previous releases."
Also the libnvidia-egl-wayland.so.1.1.9 was updated to libnvidia-egl-wayland.so.1.1.10

And there is 3 additional libraries in this version:
libcudadebugger.so.1
libcudadebugger.so.525.xx.xx
libnvidia-api.so.1

**Comment by zmrow** [comment]
Thanks for this!  We'll look into it

**Comment by foersleo** [comment]
Hi @ElTestigo, we usually try to keep the nvidia drivers stable in step with the kernel version. As we are currently working towards enabling a new kernel (kernel 6.1) for Bottlerocket, the variants with the new kernel would come with an updated nvidia driver as well.

I am close to publish the PR for initial 6.1 kernel enablement and I will start working on getting a new nvidia driver suitable to 6.1 next. The 6.1 work is tracked in https://github.com/bottlerocket-os/bottlerocket/issues/2855 and indeed already has an action item to create the nvidia kmod for that new kernel as well.
