### ISSUE TITLE
Bottlerocket Managed Node Groups Experiencing Disk Pressure Despite Specified Volume Sizes

### ISSUE THREAD

**Issue by ermiaqasemi** [bottlerocket-os/bottlerocket#3160]
Bottlerocket managed node groups in our Amazon EKS cluster are encountering disk pressure issues, even though we have specified larger volume sizes for both xvdb and xvda volumes. The disk space utilization reported by Prometheus indicates that only a fraction of the allocated space is being utilized, resulting in persistent disk pressure and inadequate storage for our workloads.

Steps to Reproduce:

1. Set up a Bottlerocket managed node group in an Amazon EKS cluster.
2. Specify the desired EBS volume sizes for both xvdb and xvda volumes, e.g., 100GB and 20GB, respectively and encrypted (gp3). 
3. Deploy workloads that require a substantial amount of disk space on the nodes.
4. Monitor the disk space utilization using Prometheus or other monitoring tools.

Actual Behavior:
Despite setting larger volume sizes, only a fraction of the allocated disk space (approximately 1GB) is being utilized on both xvdb and xvda volumes. This limited utilization results in constant disk pressure and insufficient storage for our workloads, leading to application instability and performance degradation.

Steps Taken:
In an attempt to alleviate the disk pressure issue temporarily, we have manually verified the specified volume sizes in the Bottlerocket node group configuration and ensured that they match our requirements. We have also restarted the affected nodes to check if it resolves the issue. However, neither of these actions has resolved the problem, and disk pressure persists.

Any insights, suggestions, or solutions to address this issue would be greatly appreciated.

**Comment by etungsten** [comment]
Hi @ermiaqasemi,

Thanks for bringing this to our attention. Can you please provide some more information to help us dig this further?

- Variant
- Version
- Instance type
- What's the output if you `kubectl describe` a problematic node?
- How much disk space does the workload normally require?
- How are you creating the EKS nodegroup? Any customizations beyond the default configuration?
- Is there anything special about the node set up in terms of Bottlerocket settings?
- How are you modifying the blocking device mapping?

As an aside, `xvda` is where the Bottlerocket root OS volume resides and that space is not used for containers so increasing it's size wouldn't change anything. `xvdb` on the other hand is where all the container's ephemeral storage goes so increasing that volume size should work.

**Comment by ermiaqasemi** [comment]
Hey @etungsten,

Thanks for the reply back quickly! 

- bottlerocket-aws-k8s-1.27-x86_64-v1.14.1-842c7134
- Bottlerocket OS 1.14.1 (aws-k8s-1.27)
- c6a.2xlarge
- workload requires 100GB 
- Via terraform EKS module


```
[settings.host-containers.control]
"enabled" = true

[settings.kubernetes.eviction-hard]
"memory.available" = "5%"
"nodefs.available" = "10%"
"nodefs.inodesFree" = "10%"

[settings.kubernetes.kube-reserved]
cpu = "1"
ephemeral-storage = "3Gi"
memory = "2Gi"

[settings.kubernetes.system-reserved]
cpu = "1"
ephemeral-storage = "2Gi"
memory = "2Gi"
```
kubectl describe command
```
Capacity:
  cpu:                8
  ephemeral-storage:  103189828Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             16000976Ki
  pods:               58
Allocatable:
  cpu:                7910m
  ephemeral-storage:  94026003504
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             14984144Ki
  pods:               58
```

We attached 100GB of EBS volume to our node on startup but when querying the size of storage with Prometheus it only shows 1GB.

```
node_filesystem_size_bytes{mountpoint="/"} / 1024^3
```

Maybe the mount point is wrong? but even if is wrong we observe `disk pressure` conditions on our nodes.

**Comment by yeazelm** [comment]
Hey @ermiaqasemi , Thanks for all the info! 

A 1GB report from Prometheus makes me think this is finding the host's `/` which is on `xvda`, not the larger 100GB disk on `xvdb` which I believe would show up as `/local`. Can you see if Prometheus sees that mountpoint and its space?

**Comment by ermiaqasemi** [comment]
Hey @yeazelm Thank you!

Yeah, I just checked and it seems Prometheus can see it and the space is 100GB.

 ```
{container="node-exporter", device="/dev/nvme1n1p1", endpoint="http-metrics", fstype="ext4", instance="*:9100", job="node-exporter", mountpoint="/local", namespace="monitoring", pod="prometheus-community-prometheus-node-exporter-wjj4q", service="prometheus-community-prometheus-node-exporter"}
 ```

Is that mean for checking node storage ( The data device ) I need to change the mount point?

**Comment by yeazelm** [comment]
That looks to be it! The `/` mount point will always be the same size and usage since Bottlerocket mounts that partition read only, so no need to monitor that one closely 😄 Using `/local` should be the correct one to monitor your disk usage.

**Comment by ermiaqasemi** [comment]
Thank you so much for the explanation @yeazelm! Have a good one :))
