### ISSUE TITLE
Support for NVIDIA Driver 515 series for v1.23 & below AMIs

### ISSUE THREAD

**Issue by kishoreakshat** [bottlerocket-os/bottlerocket#3168]
**What I'd like:**

I am opening this issue on behalf of an AWS customer who needs 515 series NVIDA drivers on their Kubernetes worker nodes running on Bottlerocket AMI with v1.23.

We could see that the support for this series is present for v1.24+ but it is not feasible for the customer to urgently move to 1.24, is it possible to backport this solution to v1.23 and below?

https://github.com/bottlerocket-os/bottlerocket/issues/2468

**Any alternatives you've considered:**

**Comment by stmcginnis** [comment]
The newer drivers may require the 5.15 kernel that is in 1.24 and later. 1.23 still uses the 5.10 kernel.

@arnaldo2792 knows this area more in-depth. Can you confirm?

**Comment by arnaldo2792** [comment]
This is being worked in https://github.com/bottlerocket-os/bottlerocket/pull/3203

**Comment by stmcginnis** [comment]
Looks like this was taken care of with #3203, so closing. Please feel free to reopen if anything is missing yet and call that out. Thanks!
