### ISSUE TITLE
apiclient tool availability

### ISSUE THREAD

**Issue by mbaciu-gpsw** [bottlerocket-os/bottlerocket#3181]
Hello,

i'm trying to follow the documentation for providing credentials for a private repository in bottlerocket. It's clear that one way to do this is to just include them in user-data, however, as mentioned:
```
To avoid storing plaintext credentials in external systems, it is recommended to programmatically apply these settings via apiclient using a [bootstrap container](https://github.com/bottlerocket-os/bottlerocket#bootstrap-containers-settings) or [host container](https://github.com/bottlerocket-os/bottlerocket#host-containers-settings).
```
so right now I'm considering using a bootstrap container for this.
My question is: is there a bootstrap container image specifically built for this (ie with `apiclient` included)? Or, as an alternative, is `apiclient` binary provided separately as part of any given release (so that one may choose to build a custom bootstrap container and incude it)?

Thanks,
--
Mihai

**Comment by yeazelm** [comment]
Hello @mbaciu-gpsw, thanks for cutting the issue! Bottlerocket mounts in `apiclient` to host containers from the underlying host. I believe this should work for bootstrap containers as well. This ensures the version of the `apiclient` the host is expecting will always match what the container ends up using to call the apiserver. You shouldn't need to build it in yourself.

**Comment by mbaciu-gpsw** [comment]
Thanks @yeazelm. Looks straightforward (and obvious, now). I'll give it a try.

**Comment by arnaldo2792** [comment]
FWIW, there are a few additional paths mounted into host/bootstrap containers. The apiclient talks to the API server through a socket, which is also mounted. If you are curious about what else is mounted into these containers, you can have a look at this file:

https://github.com/bottlerocket-os/bottlerocket/blob/058ebf22aba0bce841ff4927d3e5feba779648bf/sources/host-ctr/cmd/host-ctr/main.go#L768
