### ISSUE TITLE
remove macros and bootconfig files

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#3187]
### Description

Once the SDK has macros and bootconfig files added to it, use that SDK to build bottlerocket and remove the macros and SDK files from the monorepo.

### Definition of Done

When the RPM macros and bootconfig files have been removed from the Bottlerocket git repo.

#### Depends on:

- [x] https://github.com/bottlerocket-os/bottlerocket-sdk/issues/108

```
id: br_sdk
epic: twoliter_exec
```

Related to https://github.com/bottlerocket-os/bottlerocket/issues/2669

**Comment by bcressey** [comment]
macros were removed in #3213
