### ISSUE TITLE
Upgrade EKS-D packages - resolve EBS PVC attaching for a long time

### ISSUE THREAD

**Issue by ilia-medvedev** [bottlerocket-os/bottlerocket#3230]
**What I'd like:**
We are currently experiencing an issue on our EKS clusters with PVC provisioning taking a long time. Solution described in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1302#issuecomment-1598428800 and are heavily utilizing Bottlerocket AMI's in our clusters.
The issue originates in Kubelet and is resolved in latest patch versions.
For Bottlerocket to include those patches EKS-D packages need to be updated (Like was done previously in https://github.com/bottlerocket-os/bottlerocket/pull/3119).
Minimal versions of EKS-D containing the fix:
-  EKS-D 1.24-19
-  EKS-D 1.25-13
- EKS-D 1.26-11
- EKS-D 1.27-5

**Comment by gthao313** [comment]
@ilia-medvedev-codefresh Thanks for opening this issue! Bottlerocket team will investigate on it.

**Comment by gthao313** [comment]
Update EKS-D PRs had been merged.
https://github.com/bottlerocket-os/bottlerocket/pull/3234
https://github.com/bottlerocket-os/bottlerocket/pull/3235
https://github.com/bottlerocket-os/bottlerocket/pull/3236
https://github.com/bottlerocket-os/bottlerocket/pull/3237

^ EKS-D bumps are not to the versions listed in the issue description

**Comment by stmcginnis** [comment]
EKS-D bumps are not to the versions listed in the issue description. Reopening until we can get to those releases.

**Comment by stmcginnis** [comment]
Ah, my mistake here. The description actually calls out EKS-D package versions and not K8s point releases. I mixed that up in my head. :D So this is good!

**Comment by diranged** [comment]
When will an updated `1.14.x` release come out with these patches?

**Comment by stmcginnis** [comment]
Hey @diranged! These updates were [included in the 1.14.2 release](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.14.2). A couple weeks ago 1.14.3 also came out, with an update for the EKS-D K8s 1.23 variants.

**Comment by diranged** [comment]
@stmcginnis,
  Indeed you are right - I misread the release notes and thought that 1.26.6-6 was the update. Given that, we are actually rolling our clusters back right now from 1.26-1.14.3 to 1.26-1.14.1. After doing the upgrade from 1.14.1 -> 1.14.3, we began to see significant problems with pod terminations when PVCs (EBS or EFS) were involved. Virtually all of the symptoms discussed in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1302#issuecomment-1598428800 and https://github.com/kubernetes/kubernetes/pull/116138.

  I wonder what is causing our issue… could it be we need to upgrade something else in conjunction with the Bottlerocket AMI update?

**Comment by stmcginnis** [comment]
Yikes! Would you mind opening a new issue on that? Sounds like something that will need to be tracked down, so good if we have a new issue to capture those details and resolution.

**Comment by diranged** [comment]
@stmcginnis Done at https://github.com/bottlerocket-os/bottlerocket/issues/3370

**Comment by shay-ul** [comment]
@diranged we're also on 1.14.3 nodes and still see this issue. Is it possible that something in the ebs-csi-driver needs to be adjusted, such as describe here https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1302#issuecomment-1553503672 ?
Would love to hear any insights so far. thanks

Edit: Our issue was resolved with updating ebs-csi-driver to the latest version.
