### ISSUE TITLE
Bare Metal image: "qed" network driver exists in image but driver firmware file is missing

### ISSUE THREAD

**Issue by max-boehm** [bottlerocket-os/bottlerocket#3246]
**Image I'm using:**
Bare Metal Bottlerocket variant (bottlerocket-metal-k8s-1.27-x86_64-v1.14.0.img.gz)

**What I expected to happen:**
When booting Bottlerocket it shall be possible to use the "qed" network driver which is embedded in the image.

**What actually happened:**
When Bottlerocket boots on a HP DL360 Gen10 the network is not started although the required driver is contained in the image. The required driver (QLogic "qed") is loaded, but the firmware file is missing in the image. See the 2 screenshots below:

![bottlerocket_qede_fw_error1](https://github.com/bottlerocket-os/bottlerocket/assets/7419505/40ae1d03-5e83-4bfc-8c87-bf26a36c4577)

![bottlerocket_qede_fw_error2](https://github.com/bottlerocket-os/bottlerocket/assets/7419505/e76ffeaf-c5b2-4dd5-9885-7e82a2fb6d8b)

The driver firmware file is contained in the Linux kernel tree here: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/qed/qed_init_values_zipped-8.42.2.0.bin. To fix the issue this file must be placed in `/lib/firmware/qed/qed_init_values_zipped-8.42.2.0.bin`.

The network adapter model in the DL360 server is an "HPE Ethernet 10/25Gb 2-port 640FLR-SFP28 Adapter".

**How to reproduce the problem:**
Boot on hardware with a network device which needs the "QLogic Everest FastLinQ Linux Driver" (qed).

**Comment by stmcginnis** [comment]
@markusboehme or @foersleo - is this something one of you can take a look into?

**Comment by foersleo** [comment]
Indeed, we are lacking all firmware blobs for hardware, except for CPU microcode and the nvidia specific ones that come with the nvidia driver on the `*-nvidia` variants. That is an oversight on our end when creating the `metal-*` variants. For environments the  `aws-*` and `vmware-*` variants run in, we do not need any firmware binary blobs.

I will have a look into how we will best add firmware blobs for hardware we supply drivers for. That may either be through the kernel builds with an extra rpm or introducing a separate package like linux-firmware.

**Comment by foersleo** [comment]
@max-boehm - I have opened a PR that hopefully is closing the gap of missing firmware not only for qed devices, but for all the drivers we ship in our metal variants. Would you be able to help with testing? Take the PR branch for a spin and test/validate if that fixes the issue for you? Unfortunately I do not have access to these kind of devices and thus can only reason about the patch being correct, but not show it working.

**Comment by max-boehm** [comment]
@foersleo - Sure, I've tried to build the branch with

`$ cargo make -e BUILDSYS_VARIANT=metal-k8s-1.27 -e BUILDSYS_UPSTREAM_SOURCE_FALLBACK=true 2>&1 | tee make.log`

but the build did not yet succeed. Can you see what I did wrong? Output is attached: [make.log](https://github.com/bottlerocket-os/bottlerocket/files/12189478/make.log)

**Comment by foersleo** [comment]
@max-boehm So if I read the output correctly it did build the linux-firmware package appropriately. However, it seems to miss the `linux-firmware-whence` rpm.

In the first iteration I had that one split out into a separate rpm which was a dependency for the actual `linux-firmware` rpm. I'd assume that building the final package might get thrown off as it is not specified in the packages that shall be added to the variants.

Can you share what the checkout hash is you tried this from?

The current state of the PR would be [17753dadfd15](https://github.com/bottlerocket-os/bottlerocket/commit/17753dadfd15052a4e36f625b7b1c842bcdf1ca1), while the first iteration was [7389e88350cd](https://github.com/bottlerocket-os/bottlerocket/commit/7389e88350cd06d78b6c13d5b3e79c2a16b2c479)

Sorry for the extra inconvenience and thanks a lot for taking the time to validate/test this!

**Comment by max-boehm** [comment]
@foersleo The checkout hash which I have tried yesterday was 17753dadfd15. I'm rerunning the build now and will report back when its done. (I sometimes have transient internet proxy disconnections which then leads to failed builds)

**Comment by max-boehm** [comment]
@foersleo I'd like to confirm that the build https://github.com/bottlerocket-os/bottlerocket/commit/17753dadfd15052a4e36f625b7b1c842bcdf1ca1 has succeeded without any problems and the qed driver finds the firmware and works as expected. Great!

**Comment by foersleo** [comment]
Thank you for helping validate the patch @max-boehm!
