### ISSUE TITLE
admin-container: inform host rootfs path

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket#325]
The admin-container, and `sheltie` specifically, should not need to know the details of the outside mounts. The container supervisor, `host-ctr`, should inform the container to allow for flexibly referencing the correct path as seen from the host instead of having a hard coded path:

https://github.com/bottlerocket-os/bottlerocket/pull/321/files#diff-4464a17fcc54d6ccc36462c084196744R9

**Comment by samuelkarp** [comment]
We've addressed this for the admin container in https://github.com/bottlerocket-os/bottlerocket-admin-container/pull/8 by taking advantage of the `proc` filesystem.  This technique is generally applicable to any container that shares a `pid` namespace with the host and has the ability to transition namespaces (e.g., has `CAP_SYS_ADMIN`).

Closing this issue for now.  If we find other use-cases where it's important for a container that does *not* have these properties to find out the location of its own root filesystem relative to the host, we can take a look again.
