### ISSUE TITLE
Update metadata: unique IDs

### ISSUE THREAD

**Issue by sam-aws** [bottlerocket-os/bottlerocket#326]
https://github.com/amazonlinux/PRIVATE-thar/issues/184 describes a few potential extensions to the update metadata (or at least the metadata that Updog _outputs_), in particular the concept of an update ID.
While not required for anything that Updog does yet this could be more useful if Updog adds the option to "prepare" for an update by pre-downloading update image files or migrations. If it is possible that the associated image or migration targets could change for an existing update version, then a unique ID could help to catch such a change after a prepare action.

Some questions to answer before adding an ID:
  - Should the TUF repo and/or our tooling even allow such modifications to an update without a version change?
  - What is it based on? Some unique number or a hash of an update's fields?
  - Should it be generated by Updog (for orchestrators) or by tuftool/updata (as part of the formal metadata)?
  - Migration targets are listed separately from updates, and the list of migration targets depends on the current image as well as the target - does a migration change invalidate all current IDs?
  - Would a valid alternative be for tough to provide a way to check when the update metadata was last updated, which Updog validates against what it prepared with?

**Comment by etungsten** [comment]
A lot of the concerns here have been remediated by the update API and the `apiclient`.
