### ISSUE TITLE
Website link on repo side nav

### ISSUE THREAD

**Issue by bryantbiggs** [bottlerocket-os/bottlerocket#3293]
**What I'd like:**
Minor nit - it would be great to add the new website to the repository `About` left sidebar. See example below of Karpenter 
<img width="328" alt="image" src="https://github.com/bottlerocket-os/bottlerocket/assets/10913471/fb4dced3-1544-473f-8cb3-db15d094c42d">

**Any alternatives you've considered:**
None - it just tends to be the quick and easy place to jump to the docs

**Comment by stockholmux** [comment]
Great idea @bryantbiggs. Done!

**Comment by bryantbiggs** [comment]
thank you!
