### ISSUE TITLE
Pods unable to do any outbound request with cluster pool mode on Ciliim with EKS

### ISSUE THREAD

**Issue by Kaitou786** [bottlerocket-os/bottlerocket#3297]
**Image I'm using:**

bottlerocket-aws-k8s-1.25-x86_64-v1.13.2-aaf6eeb3

**What I expected to happen:**

Pods scheduled on the node with bottlerocket os node should be able to do inter pod networking

**What actually happened:**

pods are not able to do any outbound requests.

**How to reproduce the problem:**
Hi, I am using an EKS cluster with a mix of self-managed and EKS-managed node pools; we were switching to the bottlerocket-os for our self-managed node pools; for using the cgroupv2.

We are using Cilium CNI with cluster-pool IPAM mode; I saw a similar issue: https://github.com/bottlerocket-os/bottlerocket/issues/1367
But the workaround mentioned their does not work for me.

My cilium config looks like:

```
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-sock: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: default
  cluster-pool-ipv4-cidr: 192.168.0.0/16
  cluster-pool-ipv4-mask-size: "24"
  custom-cni-conf: "false"
  debug: "false"
  debug-verbose: ""
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  egress-masquerade-interfaces: eth0
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-big-tcp: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "false"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-sctp: "false"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  identity-allocation-mode: crd
  identity-gc-interval: 15m0s
  identity-heartbeat-timeout: 30m0s
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: cluster-pool
  kube-proxy-replacement: disabled
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  prometheus-serve-addr: :9962
  proxy-prometheus-port: "9964"
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  skip-cnp-status-startup-clean: "false"
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: vxlan
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
```

**Comment by ecpullen** [comment]
Hi Kaitou786,
Can you please share what you've tried for troubleshooting so far. Do you know if your configuration works with the EKS optimized AMI? Can you verify that the cilium agent is running, if not https://github.com/cilium/cilium/issues/20667 may be relevant. I also noticed you are using v1.13.2 AMIs, have you considered moving to 1.14?

**Comment by bcressey** [comment]
One thing to verify, via a sequence like this, is that all the Cilium interfaces are set to `rp_filter = 0`:
```
<ssh or ssm connect to admin container>
$ sudo sheltie
# head /proc/sys/net/conf/ipv4/*/rp_filter
```

**Comment by Kaitou786** [comment]
Hi @ecpullen 
yeah this network configuration works well with the EKS-optimized AMI;
the cilium agent on the node is running but I do see:
```
level=warning msg="iptables modules could not be initialized. It probably means that iptables is not available on this system" error="could not load module ip_tables: exit status 1" subsys=iptables
```
Which I think could be the issue.

The other thing I noticed is only the inter-pod communication is not working; I am able to reach outside internet using their IPs.

I have also updated the AMI to 1.14.1 but having the same issue.


@bcressey I have also verified that all the cilium interfaces have rp_filter as 0.

**Comment by Kaitou786** [comment]
I also tried to switch the CNI back to the aws-node; but it still doesn't work; I restarted all the pods after switching the CNI.

the userdata that I am using with the ami:

```
[settings.host-containers.admin]
    enabled = true
    [settings.kubernetes]
    api-server =  <API_SERVER>
    cluster-certificate = <CERT>
    cluster-name = <CLUSTER_NAME>
    [settings.boot]
    reboot-to-reconcile = true

    [settings.boot.init]
    "systemd.unified_cgroup_hierarchy" = ["1"]
```

**Comment by Kaitou786** [comment]
Okay so from my testing; it seems if create all nodes with bottlerocket-os the networking works without any problem with cilium or with aws CNI; but when I have a mixture of nodes in my cluster (EKS optimized AMI and bottlerocket-os) the pods on bottlerocket-os doesn't have any networking

**Comment by ecpullen** [comment]
I found this issue - https://github.com/cilium/cilium/issues/20677

What version of cilium are you using?

Have you tried setting `bpf.hostLegacyRouting = true`?

**Comment by Kaitou786** [comment]
Yeah, I tested with that setting too we are not using CNI chaining but I tried with multiple settings;
so I think the actual problem isn't the CNI; because I even tested with a new EKS cluster 1.26 with few managed node groups; As soon as I add the bottlerocket node group the networking on it doesn't work.


It starts working if I remove my other managed node groups and have my eks with only bottlerocket OS instances.

**Comment by ecpullen** [comment]
I am unable to reproduce your error so far. I launched an eks cluster with the following node groups:
```
managedNodeGroups:
  - name: al
    desiredCapacity: 2
    privateNetworking: true
    taints:
     - key: "node.cilium.io/agent-not-ready"
       value: "true"
       effect: "NoExecute"
  - name: br
    amiFamily: Bottlerocket
    desiredCapacity: 2
    privateNetworking: true
    taints:
     - key: "node.cilium.io/agent-not-ready"
       value: "true"
       effect: "NoExecute"
```

I then installed cilium to the cluster and ran the connectivity test. After that test passed, I updated the cilium config to follow the one provided and ran another connectivity test and all tests passed. Do you have any other information about your cluster or node groups that could help us reproduce the error?

**Comment by Kaitou786** [comment]
Oh, I figured it out; this was our problem; we had a separate process for creating the EKS managed node groups and self-managed node groups; and as a result, we were adding different security groups to them; So the nodes were not able to talk to each other due the Security Groups.

Closing as this is something that we mis-configured.

Nevertheless thanks for all the support 🙏🏽

**Comment by ecpullen** [comment]
That's great to hear. I'm glad we were able to help. Please feel free to let us know if you run into any more issues.
