### ISSUE TITLE
Remove K8s 1.23 variants by Oct 2023

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket#3306]
Kubernetes 1.23 went out of upstream support in December, 2023. AWS EKS is maintaining support for 1.23 until [October 11th, 2023](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar). Bottlerocket will end support of our K8s 1.23 variants at that time.

While you’ll still be able to launch *-k8s-1.23 nodes beyond October 11th, 2023, we’ll no longer provide updated *-k8s-1.23 images, and the Bottlerocket repositories will no longer receive new updates for nodes running K8s 1.23 variants.

We recommend you replace existing Bottlerocket K8s 1.23 nodes with [a newer variant](https://github.com/bottlerocket-os/bottlerocket/tree/develop/variants#variants) - ideally the latest your Kubernetes cluster supports.

For instructions on how to migrate your aws-k8s-1.23 nodes to newer supported versions, please consult the [EKS documentation for updating clusters](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) or reach out to us through your AWS support channels for additional questions.

**Comment by stockholmux** [comment]
Bottlerocket follows the [Amazon EKS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) support policy for `aws-k8s-*` variants. With the [recent change in the support policy,](https://aws.amazon.com/es/blogs/containers/amazon-eks-extended-support-for-kubernetes-versions-available-in-preview/) the `aws-k8s-1.23-*`  variants will not be removed by Oct 2023. You may still wish to migrate your aws-k8s-1.23-*  nodes to newer variants for compatibility with a more current version of Kubernetes.

See issue #3511 for removal of `metal-k8s-1.23-* `and `vmware-k8s-1.23-*` during Oct 2023.
