### ISSUE TITLE
using local mounted disk results in error

### ISSUE THREAD

**Issue by pdeva** [bottlerocket-os/bottlerocket#3378]
i am trying to use the following script to format and mount the local storage disk on eks.

```sh
#!/usr/bin/env bash
set -ex

ROOT_PATH="/.bottlerocket/rootfs"

# The name of the disk we want to manage
DISK="${ROOT_PATH}/dev/nvme2n1"

# Mounts from this mount point will propagate accross mount namespaces
MOUNT_POINT=/.bottlerocket/rootfs/mnt/ephemeral

# Format disk to xfs
mkfs.xfs ${DISK}

# We make sure the target mount points exist
mkdir -p $MOUNT_POINT

# Always mount the partitions
mount -t xfs "${DISK}" "${MOUNT_POINT}"
```

However, when i run a pod with this volume path:
```
- /.bottlerocket/rootfs/mnt/ephemeral
```

i get this error:

```
Events:
  Type     Reason       Age                 From     Message
  ----     ------       ----                ----     -------
  Warning  FailedMount  53s (x8 over 116s)  kubelet  MountVolume.SetUp failed for volume "data" : mkdir /.bottlerocket: read-only file system
```

Why is the kubelet  trying to create a directory `/.bottlerocke`t, ? I specified the path `/.bottlerocket/rootfs/mnt/ephemeral` not `/.bottlerocket`

**Comment by bcressey** [comment]
The bootstrap container runs in its own mount namespace, with the container's root at `/` and the Bottlerocket host's root at `/.bottlerocket/rootfs`.

Mounts that pods specify are relative to the host's root, not the (by-then non-existent) bootstrap container's root.

So if you create `/.bottlerocket/rootfs/mnt/ephemeral` in a bootstrap container, you would refer to it in a pod spec as `/mnt/ephemeral`.

Please try that change and see if it helps.

**Comment by bcressey** [comment]
The specific error is happening because the container runtime is trying to create `/.bottlerocket` on the host, but the host's root is read-only, so the directory can't be created.

However, `/mnt/ephemeral` should exist because of your bootstrap container, so referencing that path should work.

**Comment by bcressey** [comment]
Resolving. Please re-open if you still can't get it to work after changing the path.
