### ISSUE TITLE
build a better growpart

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#339]
`growpart` has a number of rough edges at the moment.

If the GPT label is not at the end of the disk, the first run will not fully expand the partition. A second run will correct it, but this is awkward. (See #336 for more discussion.)

It only supports a partition as the input parameter, not the path to the underlying block device or disk image. It would be useful to handle this case as well, to simplify testing.

It only supports disks with a single partition, but it could also be defined to expand the last partition to fill the disk, to make it more generally useful.

**Comment by stmcginnis** [comment]
Growpart is now gone, so I don't believe this is still an issue. Closing this as no longer needed, but feel free to reopen if anything further is needed. (@bcressey please reopen if this is not the case)
