### ISSUE TITLE
Repeated `ndisc_router_discovery failed` messages in the journal when using `systemd-networkd`

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#3411]
**Image I'm using:**
`aws-k8s-1.28` with `systemd-networkd` built from #3394 

**What actually happened:**
While testing for #3394 , I noticed in an IPv6-enabled cluster the nodes join the cluster and run sonobuoy just fine, but the journal is being spammed with the following messages:
```
Sep 01 22:37:25 ... kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
Sep 01 22:37:35 ... kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route
```

The messages start ~10 seconds after the interfaces are brought up, and continue to be logged every 10 seconds forever.

Amazon Linux 2023 has the following in their config, perhaps this is the reason why:
```
[Route]
Gateway=_ipv6ra
```

**How to reproduce the problem:**
Build an image and join it to an IPv6-only cluster

**Comment by zmrow** [comment]
Mostly everything I'm seeing about `ndisc_router_discovery` relates to setting a static gateway and also having IPv6 RA turned on.  We don't set a static gateway anywhere.

Confirmed that the following doesn't make a difference.
```
[Route]
Gateway=_ipv6ra
```

Also tried multiple `Route` sections with `Gateway=_dhcp4` and `Gateway=_ipv6ra`; neither stopped the logs.

Just out of curiosity, I added `LLMNR=false` to the interface's config, since that was the only other meaningful config difference between Bottlerocket and AL2023.  Once again, no change.

The message originates in [this function in the kernel]( https://elixir.bootlin.com/linux/latest/source/net/ipv6/ndisc.c#L1382).  Further [down the call chain](https://elixir.bootlin.com/linux/latest/source/net/ipv6/route.c#L3676) it looks like there's some error messages that _could_ be available via netlink since it calls `NL_SET_ERR_MSG`.  However, I tried to get this using bpftrace from the Admin container but nothing got spit out after "Attaching 1 probe".  (Could absolutely be user error :) )

```
$ sudo bpftrace -e 'tracepoint:netlink:netlink_extack { printf("netlink error: %s\n", str(args->msg)) }'
Attaching 1 probe...
```

I've also tried adding (too much) additional logging around these calls in the kernel but am getting rate limited.  Will try a different tactic not using `ND_PRINTK` (which gets rate limited).

**Comment by zmrow** [comment]
Just for posterity's sake: AL23 has the following `forwarding` and `accept_ra` sysctl's set this way by default:
```
$ sysctl net.ipv6.conf.enX0.forwarding
net.ipv6.conf.enX0.forwarding = 0

$ sysctl net.ipv6.conf.enX0.accept_ra
net.ipv6.conf.enX0.accept_ra = 0
```

Bottlerocket sets the following:
```
bash-5.1# sysctl net.ipv6.conf.eth0.forwarding 
net.ipv6.conf.eth0.forwarding = 1

bash-5.1# sysctl net.ipv6.conf.eth0.accept_ra
net.ipv6.conf.eth0.accept_ra = 2
```

I believe our settings are correct for our use case.  `forwarding` needs to be on for our container/k8s usage.  

`accept_ra` needs to be 2 to turn on RA processing even though forwarding is enabled.  [From the docs](https://sysctl-explorer.net/net/ipv6/accept_ra/):
>Possible values are: 0 Do not accept Router Advertisements. 1 Accept Router Advertisements if forwarding is disabled. 2 Overrule forwarding behaviour. Accept Router Advertisements even if forwarding is enabled.

**Comment by bcressey** [comment]
In a similar setup - using IPv6 for the overlay network with the vpc CNI plugin - I found that creating this file for eth0 and running `networkctl reload` caused the messages to stop:
```
[Route]
Gateway=_dhcp4
[Route]
Gateway=_ipv6ra
```

**Comment by bcressey** [comment]
Reloading a new configuration or restarting `systemd-networkd` is sufficient to resolve the issue, because it resets [the IPv6 accept_ra sysctl](https://github.com/systemd/systemd/blob/7b9da3861a2d27dd31c360674947005a19f3cbe7/src/network/networkd-sysctl.c#L133) back to the expected value of `0`.

The AWS VPC CNI plugin is unconditionally setting that value to `2` in the [init container](https://github.com/aws/amazon-vpc-cni-k8s/blob/f7672495a1d38807d7ce4def052be577ea171d86/cmd/aws-vpc-cni-init/main.go#L128), which activates the kernel's RA client, which then clashes with `systemd-networkd`.
