### ISSUE TITLE
Pods are not terminating after migrating to Bottlerocket os from Amazon Linux on EKS 

### ISSUE THREAD

**Issue by RahulGP14** [bottlerocket-os/bottlerocket#3448]
**We have recently updated EKS cluster form 1.23 to 1.27 and we have all unmanaged NodeGroups. We have migrated all Nodegroup OS from Amazon Linux to Bottlerocket OS version k8s-1.27-x86_64-v1.14.2. Pods are not terminating it is getting stuck in terminating state. Please let me know if any more details required.**

**Comment by stmcginnis** [comment]
Thanks for reporting this @RahulGP14. I see you found https://github.com/bottlerocket-os/bottlerocket/issues/3370. Let's keep the discussion there as it appears to be the same issue.

If you could comment on #3370 with any example pod definitions you've seen that have caused this condition, that would help. I believe @cbgbt had been investigating and trying to reproduce the failure, but was having trouble getting it to happen in his setup. If we can pinpoint what combination of settings can trigger this behavior, that would be great to help track things down.

Thanks!
