### ISSUE TITLE
Add nfs-utils/nfs-common to AMI to support FSxN CSI

### ISSUE THREAD

**Issue by mickeysh** [bottlerocket-os/bottlerocket#3450]
**What I'd like:**
Add nfs-utils/nfs-common to the instance to support NFS mounts by bottlerocket-os instances using FSxN CSI.
 
Users that would like to run stateful applications with FSxN (FSx for NetApp ONTAP) using bottlerocket instances can't mount the volumes using the official FSxN CSI since the AMI doesn't have these libraries as part of the image unlike default EKS AMIs or Ubuntu AMIs.

**Comment by stmcginnis** [comment]
Hi @mickeysh, thanks for raising this. NFS support is being tracked in https://github.com/bottlerocket-os/bottlerocket/issues/2570. This comment will cause this issue to show up in that one, so let's close this and keep activity there.

This is useful to know the level of interest for this support - thanks!
