### ISSUE TITLE
Support for AWS Inferentia

### ISSUE THREAD

**Issue by prashant-prodigal** [bottlerocket-os/bottlerocket#3495]
**What I'd like:**
Support AWS Inferentia with bottlerocket which is currently not supported (EC2 instance types inf1.xlarge, inf1.2xlarge, etc)
https://aws.amazon.com/machine-learning/inferentia/

**Any alternatives you've considered:**

**Comment by stmcginnis** [comment]
Thanks for opening this Prashant. There is an existing [enhancement issue for Inferentia](https://github.com/bottlerocket-os/bottlerocket/issues/1075) (which this is now linked to) so I'm going to close this one to keep everything there. Feel free to add any more comments or details there. Thanks!
