### ISSUE TITLE
Replace 2.amazon.pool.ntp.org by time.aws.com

### ISSUE THREAD

**Issue by laurentdelosieresfact** [bottlerocket-os/bottlerocket#3496]
The current NTP settings are first pointing to [169.254.169.123 and then to 2.amazon.pool.ntp.org](https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/models/shared-defaults/defaults.toml#L109). Would it make more sense to replace `2.amazon.pool.ntp.org` by `time.aws.com`, so we only depend on AWS ?

https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-time-sync-internet-public-ntp-service/

**Comment by stockholmux** [comment]
Looks like it's [already on @bcressey's mind](https://github.com/bottlerocket-os/bottlerocket-project-website/pull/285#discussion_r1341754540). 

The docs already reflect this as well: https://bottlerocket.dev/en/os/1.15.x/api/settings/ntp/#time-servers

**Comment by laurentdelosieresfact** [comment]
Hello @stockholmux ,

That's great news 🚀 Feel free to close this issue.

Best,
L.

**Comment by stmcginnis** [comment]
Looks like this can be closed, but please reopen or file a new issue if there is anything else at all. Thanks!
