### ISSUE TITLE
Not possible for stats exporter (prometheus node exporter) to provide CPU frequency information

### ISSUE THREAD

**Issue by JamesTGrant** [bottlerocket-os/bottlerocket#3534]
Not possible for stats exporter (prometheus node exporter) to provide CPU frequency information

https://www.kernel.org/doc/Documentation/cpu-freq/user-guide.txt documents the expected paths and definitions for various CPU stats including cpu_frequency and cpuinfo_cur_freq. This information is useful to determine the impact of thermal throttling as well as corrolating application throughput with regard to time, with regard to CPU cycles, hence frequency is a major indicator regarding the instantaneous ability of the CPU.
sys/devices/system/cpu/cpu0/ does not include cpufreq, susequently prometheus node exporter does not include node_cpu_frequency or node_cpu_scaling_frequency

**Image I'm using:**
Bottlerocket OS 1.15.1 (aws-k8s-1.27)

**What I expected to happen:**
node exporter (part of kube-prometheus-stack) to access cpu frequency info

path /sys/devices/system/cpu/cpu0/ to include a directory 'cpufreq' containing the cpu_info files documented by 
https://www.kernel.org/doc/Documentation/cpu-freq/user-guide.txt

**What actually happened:**
there is no directory 'cpufreq' at path /sys/devices/system/cpu/cpu0/ and so there are no node cpu_frequency or node_cpu_scaling_frequency metrics

**How to reproduce the problem:**
Create bottlerocket instance via EKS

**Comment by zmrow** [comment]
Thanks for the issue @JamesTGrant !  I quickly looked at this and also do not see a `cpu_freq` directory in sysfs.
```
bash-5.1# ls /sys/devices/system/cpu/cpu0/
cache  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  hotplug  node0  power  subsystem  topology  uevent
```
According to our kernel config we do build in the `CONFIG_CPU_FREQ` kernel module:
```
bash-5.1# grep CPU_FREQ /boot/config 
CONFIG_ACPI_CPU_FREQ_PSS=y
CONFIG_CPU_FREQ=y
CONFIG_CPU_FREQ_GOV_ATTR_SET=y
CONFIG_CPU_FREQ_GOV_COMMON=y
CONFIG_CPU_FREQ_STAT=y
CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y
# CONFIG_CPU_FREQ_DEFAULT_GOV_POWERSAVE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL is not set
CONFIG_CPU_FREQ_GOV_PERFORMANCE=y
CONFIG_CPU_FREQ_GOV_POWERSAVE=m
CONFIG_CPU_FREQ_GOV_USERSPACE=m
CONFIG_CPU_FREQ_GOV_ONDEMAND=m
CONFIG_CPU_FREQ_GOV_CONSERVATIVE=m
CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y
```

I'll dig into this further and update this issue

**Comment by markusboehme** [comment]
Insight into and control over CPU frequency scaling requires access to CPUs' P-states. Bottlerocket does ship with the relevant drivers, but whether Bottlerocket or any other operating system can access P-states depends on the platform (e.g. BIOS/UEFI/firmware settings on bare metal hardware, the hypervisor in virtualized environments). On Amazon EC2, only a subset of instance types pass through control over P-states. Instances that don't allow control over P-states are configured for maximum performance by the hypervisor already.

Please check whether you were running on an EC2 instance type for which the hypervisor exposes P-states to the instance by checking [this list in the EC2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/processor_state_control.html). For instances without access to P-states, you will see a message like `P-states controlled by the platform` in `dmesg` output.

**Comment by JamesTGrant** [comment]
Thank you. It is not in that list. I don't want to control the c or p state, but I would like access to the frequency metric (for the reasons stated)

**Comment by markusboehme** [comment]
Thanks for confirming the used instance type cannot control P-states. On instances without control over P-states the `cpufreq` directories in sysfs will always be missing as no P-state driver will be claiming them. Please note that this is a limitation put in place by the platform and shared by all distributions.

As an option, the Prometheus Node Exporter may be modified to read the `cpu MHz` fields of the `/proc/cpuinfo` file if P-states cannot be managed by the kernel and the `cpufreq` directories don't exist. Older kernels (before Linux 4.13) would show the value used for TSC calibration here, but newer ones use a couple processor registers incrementing at different speeds (APERF, MPERF) to take a guess at the frequency over the last sampling period.

A couple side notes:

* For cloud environments you can assume the provider is monitoring for thermal throttling on the host level already.
* Another, more common cause for reduced CPU performance may be the depletion of the burst bucket on burstable instance types (e.g. the T instance families on Amazon EC2) which would not show itself as a reduced CPU frequency, but can be measured via metrics specific to the cloud provider (see [the docs for Amazon EC2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances-monitoring-cpu-credits.html) for an example).

**Comment by markusboehme** [comment]
We haven't heard back in a while. As explained above, this is nothing that can be fixed in Bottlerocket. I'm closing the issue now, but please feel free to reopen it in case you have more questions on the topic.

**Comment by JamesTGrant** [comment]
Thank you for the advice. I'm aware of the side notes but well worth pointing out. I wasn't aware that the MHz in /proc/cpuinfo was a dynamic status, I thought it was static so I think that is what I shall experiement with. Thank you again.
