### ISSUE TITLE
Build task fetch-vendored failed

### ISSUE THREAD

**Issue by congzhegao** [bottlerocket-os/bottlerocket#3538]
**Platform I'm building on:** aarch64. As I'm using a m2 mac, I ran a ubuntu container using docker and built the AMI within the ubuntu container. 

**What I expected to happen:** The build process passes

**What actually happened:** 
```
[cargo-make][1] INFO - Task: default
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Running Task: setup
[cargo-make][1] INFO - Running Task: setup-build
[cargo-make][1] INFO - Running Task: fetch-sdk
[cargo-make][1] INFO - Running Task: fetch-toolchain
[cargo-make][1] INFO - Running Task: fetch-sources
[cargo-make][1] INFO - Running Task: fetch-vendored
pattern ./...: directory prefix . does not contain main module or its selected dependencies
[cargo-make][1] ERROR - Error while executing command, exit code: 1
[cargo-make][1] WARN - Build Failed.
Error: Command was unsuccessful, exit code 1
```

**How to reproduce the problem:**
I checked out to v1.15.0 and run `cargo make`, and it raised the error above. I don't have much context on twoliter unfortunately

**Comment by zmrow** [comment]
Hi @congzhegao !  I'm not sure any of us have ever tried to build Bottlerocket on a Mac in a container (our build process uses containers extensively though), and I'm not sure if this is something `twoliter` (our new build system) is going to support.

@webern Have you tried this?  Is this something `twoliter` will support?

**Comment by stmcginnis** [comment]
Just to point out - we [don't actually support building on macOS](https://github.com/bottlerocket-os/twoliter/issues/173) right now. This error is a little different than that one, but I believe there are a few things that we would need to work out before that could be done.

**Comment by congzhegao** [comment]
Thank you for the info! I'll try to run it in an ubuntu vm on mac, otherwise have to buy another laptop for this ;)
