### ISSUE TITLE
How do I purge or prune old containerd images from Bottlerocket?

### ISSUE THREAD

**Issue by allen-bmf** [bottlerocket-os/bottlerocket#3568]
The disks on my k8s worker nodes are filling up with docker images,

but, ctr command result empty

```
bottlerocket node ssm connect

$ enable-admin-container

$ apiclient exec admin bash

$ sudo sheltie

$ ctr --address "/run/containerd/containerd.sock" image ls


bash-5.1# ctr -a /run/dockershim.sock c ls
CONTAINER    IMAGE    RUNTIME
bash-5.1# ctr -a /run/dockershim.sock image ls
REF TYPE DIGEST SIZE PLATFORMS LABELS
```

why is the empty?

How to delete old images at once when prune command is not available?

**Comment by gthao313** [comment]
@allen-bmf  Thanks for opening the issue. I'm looking at the issue.

**Comment by gthao313** [comment]
@allen-bmf ctr doesn't include a "prune" command, but you can remove images via ctr --address "/run/dockershim.sock" image rm <image name>. Meanwhile, we had a discuss about this topic before, you can find more information there. https://github.com/bottlerocket-os/bottlerocket/discussions/2131

**Comment by allen-bmf** [comment]
```
ctr --address "/run/dockershim.sock" image ls
```
wy  ctr command result empty?

**Comment by gthao313** [comment]
can you try 
```
ctr --address "/run/dockershim.sock" -n k8s.io image ls
```

**Comment by gthao313** [comment]
Maybe it's about the namespace. Can you try this command to verify? 
```
ctr --address "/run/dockershim.sock" -n k8s.io image ls
```

**Comment by gthao313** [comment]
@allen-bmf  I think you can use `imageGCLowThresholdPercent`, `imageGCHighThresholdPercent`, and `imageMinimumGCAge` those k8s settings to enable the mage garbage collection. Here is the relative document https://bottlerocket.dev/en/os/1.16.x/api/settings/kubernetes/#image-gc-high-threshold-percent. 

Let me know if you have questions. thanks!

**Comment by allen-bmf** [comment]
thank you for help

add namespace command after resolve
