### ISSUE TITLE
OOTB: Port `pki` settings model to settings extensions

### ISSUE THREAD

**Issue by sam-berning** [bottlerocket-os/bottlerocket#3657]
Create a settings extension for `pki`.

### Definition of done
A new `pki` crate is created under `sources/settings-extensions`, and all variants use the model defined in that crate in place of the existing settings. Additionally, a basic `settings-pki` RPM package is created that installs the extension binary.

**Comment by mgsharm** [comment]
PR: https://github.com/bottlerocket-os/bottlerocket/pull/3971
