### ISSUE TITLE
OOTB: Port `oci_hooks` settings model to settings extensions

### ISSUE THREAD

**Issue by sam-berning** [bottlerocket-os/bottlerocket#3659]
Create a settings extension for `oci_hooks`.

### Definition of done
A new `oci_hooks` crate is created under `sources/settings-extensions`, and all variants use the model defined in that crate in place of the existing settings. Additionally, a basic `settings-oci_hooks` RPM package is created that installs the extension binary.

**Comment by mgsharm** [comment]
PR: https://github.com/bottlerocket-os/bottlerocket/pull/3978
