### ISSUE TITLE
OOTB: Port `cloudformation` settings model to settings extensions

### ISSUE THREAD

**Issue by sam-berning** [bottlerocket-os/bottlerocket#3660]
Create a settings extension for `cloudformation`.

### Definition of done
A new `cloudformation` crate is created under `sources/settings-extensions`, and all variants use the model defined in that crate in place of the existing settings. Additionally, a basic `settings-cloudformation` RPM package is created that installs the extension binary.

**Comment by mgsharm** [comment]
PR: https://github.com/bottlerocket-os/bottlerocket/pull/4010

**Comment by webern** [comment]
> PR: #4010

Not necessary to link to the PR from the Issue. When you put the Issue number into the PR, a reverse link is automatically shown in the issue's history. :+1:
