### ISSUE TITLE
OOTB: Port `dns` settings model to settings extensions

### ISSUE THREAD

**Issue by sam-berning** [bottlerocket-os/bottlerocket#3661]
Create a settings extension for `dns`.

### Definition of done
A new `dns` crate is created under `sources/settings-extensions`, and all variants use the model defined in that crate in place of the existing settings. Additionally, a basic `settings-dns` RPM package is created that installs the extension binary.

**Comment by mgsharm** [comment]
PR: https://github.com/bottlerocket-os/bottlerocket/pull/3980
