### ISSUE TITLE
Access between host containers

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#367]
**What I'd like:**

I'd like to be able to get into the admin container more easily and securely.

Currently, you SSM to control, make API calls to enable admin, exit, then SSH to admin, **and** you have to be sure your instance is accessible from the internet via IGW and public IP.

If the control container had an SSH client, you could ssh from it to the admin container directly, without exiting and initiating an SSH session through the Internet, saving half a step and remaining in your VPC.

**Any alternatives you've considered:**

The SSM agent in the control container could do clever things to get us into the admin container, for example discriminate on user ID, or have parameters in a custom SSM document.  These are longer term ideas, though?

**Comment by diranged** [comment]
Perhaps I am missing something - why can't the SSM container be setup to allow the `sudo sheltie` command to run just like the admin container? I find it quite frustrating that we have to enable two different mechanisms for accessing our bottlerocket nodes. The `aws ssm start-session...` command is quite elegant, routes us around network/securitygroup issues, and gives us plenty of audit logging. Yet, we have to use raw SSH to get in and do anything meaningful to troubleshoot issues. Feels odd.

**Comment by tjkirch** [comment]
Hi @diranged.  One big difference between the control container and the admin container is that only the admin container is “superpowered.”  This means that the admin container effectively has “root” access to the system.  (The full differences are listed [here](https://github.com/bottlerocket-os/bottlerocket/blob/b890eca1480c5aaabbeb9edd697285d814f75e75/sources/host-ctr/cmd/host-ctr/main.go#L548).)  It’s intended as an escape hatch when you have to debug in ways that aren’t possible with normal security restrictions.  We keep the admin container off by default to reflect the fact that this shouldn’t be used in production, only when you need to do deep troubleshooting.

This issue reflects the fact that the control container is easier to access, as you mentioned.  If we had a way to get into the admin container from the control container, you wouldn’t have to allow SSH access to the host to use the admin container, you could go through SSM.  I don’t think we’ve hit on the right answer yet, but it would be a nice feature.

If you wanted another way around this restriction, and are OK with reducing the security guarantees, you could enable the superpowered setting for the control container and use it for more “full” debugging, closer to the admin container.

**Comment by diranged** [comment]
@tjkirch thanks for the fast response. I am glad to hear the only difference is the privileged-vs-unprivileged mode, because to me that can easily be a configurable flag. We fundamentally don't believe that SSH is actually "more" secure than using the SSM start-session code. The model in our mind is - whats the easiest thing to do securely every time? For us, that is to not store local credentials on a laptop, or ask developers to go copy-and-paste credentials from SSM somewhere, then store them on the laptop, then delete them later. It's to have them go through their short-lived AWS credential sessions where we have better audit logging capabilities already in place.

To answer your question - I would love to see the control container be privileged as a flag that can be flipped on, because then we simply wouldn't run the admin container at all. Now I think that would also necessitate that the control container would have some of the CLI tools like `sheltie` available, right?

Another option that would at least help us out in the short term is if the control container had read-only access to the root filesystem in the orchestrator, so that we could collect logs from it.

**Comment by diranged** [comment]
On a side note - we're thinking about developing our own custom admin container that uses an SSH Certificate Authority to grant access rather than the EC2 Metadata certificate. We use a custom in-house SSH CA for all of our Github and Bastion access today, so its not a big stretch .. but I would be able to avoid doing this entirely if we could improve the capabilities of the control container.

**Comment by tjkirch** [comment]
> We fundamentally don't believe that SSH is actually "more" secure than using the SSM start-session code. The model in our mind is - whats the easiest thing to do securely every time? For us, that is to not store local credentials on a laptop, or ask developers to go copy-and-paste credentials from SSM somewhere, then store them on the laptop, then delete them later. It's to have them go through their short-lived AWS credential sessions where we have better audit logging capabilities already in place.

I agree about the difference in method and use case for SSH vs. SSM.  I wasn't comparing their security levels or saying SSH is better, I was only comparing the security levels of superpowered vs. non-superpowered containers.  If we can allow access to the admin container through the control container (i.e. SSM) then we enable both use cases, based on user preference.  That's what this issue represents.

> I would love to see the control container be privileged as a flag that can be flipped on

That's possible today; the superpowered flag is a setting like any other.  See this [README section](https://github.com/bottlerocket-os/bottlerocket/#host-containers-settings).  For example, you could add some instance user data like this:

```toml
[settings.host-containers.control]
superpowered = true
```

(Again, please make sure you're comfortable with the security implications, you're not using this in production, etc.)

> Now I think that would also necessitate that the control container would have some of the CLI tools like sheltie available, right?

The control container won't have the same debugging tools as the admin container; that reflects the difference in their intended purposes.  There is some level of debugging you can do from the control container with regard to the kernel, given that it's shared, and with superpowered mode enabled, you can also inspect the Bottlerocket filesystem.  Beyond that, you'd want a container meant for debugging, whether that's the admin container or a custom one.

> Another option that would at least help us out in the short term is if the control container had read-only access to the root filesystem in the orchestrator, so that we could collect logs from it.

I think we'd like to hear more about this use case, probably in a new issue.  We currently only allow access to the Bottlerocket filesystem from the admin container because of the security implications.  Would it be possible to run an orchestrated container that handles monitoring or log collection instead of relying on the host containers?  We've heard good reports about that from other users.  Something to consider in the new issue.

> we're thinking about developing our own custom admin container that uses an SSH Certificate Authority to grant access rather than the EC2 Metadata certificate

We've also heard this request in the admin container's repo - see https://github.com/bottlerocket-os/bottlerocket-admin-container/issues/17 and its PR.  We're also working on other ways to take some of the burden off of developers who want to customize the host containers, related to that request.

**Comment by diranged** [comment]
Thanks for the detailed response - that's super helpful to have the context! Generally speaking, the only valid use-case I would have for getting into the orchestration container is to collect logs and gather information about the environment. If we could enable that through another container (or more ideally just through the "control" container) in a safe read-only fashion, I would be happy.

I am basically trying to solve the "Operator having a problem with $INSTANCE, needs to gather X, Y and Z data for AWS Support Engineer" problem. I've done some vague poking around in the orchestrator to see how things work as well, but that isn't my main focus.

> That's possible today; the superpowered flag is a setting like any other. See this README section. For example, you could add some instance user data like this:
> 
> ```
> [settings.host-containers.control]
> superpowered = true
> ```
> 

On this particular topic - is there a way to replicate `sudo sheltie` from the control container, if we were to make it privileged?

**Comment by tjkirch** [comment]
> I am basically trying to solve the "Operator having a problem with $INSTANCE, needs to gather X, Y and Z data for AWS Support Engineer" problem

We're hoping that's what [logdog](https://github.com/bottlerocket-os/bottlerocket/#logs) will solve as we continue to increase the data it gathers and improve how you can get access to it.  It currently needs the admin container so that it has access to the Bottlerocket filesystem, and also because retrieving the resulting file back out through SSH is easier than getting a file out through SSM.  (Of course there are other alternatives there, like pre-signed S3 URLs, etc.)  For the moment, since this is an occasional need rather than a production use case, you could use the admin container, or use a superpowered control container to access the Bottlerocket filesystem through `/.bottlerocket/rootfs`.  (For regular gathering, it would probably be better to have a monitoring container run through the orchestrator.)

> is there a way to replicate sudo sheltie from the control container, if we were to make it privileged?

I don't think it would be possible to replicate exactly, because there's no `su`/`sudo` in the control container, since it's not intended for "root" access.  There might be a way to get a shell with a reduced level of access that doesn't need root - I bet @samuelkarp would have ideas here.

I do think it'd be better to solve the problem in this issue (accessing the admin container through the control container) rather than giving the control container more access to fully replicate sheltie.  It would be possible to add settings to the control container to allow access to more system data, but it goes against the purpose a bit, so I'm hoping the other directions work out.

**Comment by samuelkarp** [comment]
> I don't think it would be possible to replicate exactly, because there's no `su`/`sudo` in the control container, since it's not intended for "root" access. There might be a way to get a shell with a reduced level of access that doesn't need root - I bet @samuelkarp would have ideas here.

The control container image that we build isn't meant for the same kinds of administrative access that the admin container image is, so we don't include the same tools.  Even if you ran the control container privileged, you'd still need a mechanism to escalate to root before you can transition between namespaces; that would require some sort of setuid binary like `su` or `sudo` to be present.  Beyond that, we don't actually have a shell in Bottlerocket, nor do we necessarily have all the libraries that a shell would need, so the admin container image includes a [fully-static `bash` binary](https://github.com/bottlerocket-os/bottlerocket-admin-container/blob/eec7430012182bb77a68a327f10065abdcc73a3f/Dockerfile#L25-L41) and then we [use that binary after transitioning to the host's mount namespace](https://github.com/bottlerocket-os/bottlerocket-admin-container/blob/eec7430012182bb77a68a327f10065abdcc73a3f/sheltie#L11-L21).

If you want to build your own image, you can use that in place of the ones that we provide.  If you're comfortable with the security implications of an always-on "superpowered" container with its access controlled via SSM, you could run a container that is a hybrid of what we've built in our control and admin containers: SSM-based, but including sudo, the statically-linked bash binary and the sheltie script.

**Comment by diranged** [comment]
@samuelkarp I like the idea of the individual containers doing their own thing, but at the same time I feel strongly about the ability to do deep troubleshooting through the SSM session. Is there a middleground - for example, some pre-generated SSH credentials between the control<->admin container?

**Comment by samuelkarp** [comment]
@diranged Yep, figuring out that middle ground is exactly what this issue is about.  The top few comments on this issue have most of the discussion; we haven't landed anywhere specific yet in terms of implementation.

**Comment by tjkirch** [comment]
Just a quick update.  For anyone looking to connect to the admin container without needing open ports or public IPs, you can now [SSH through SSM](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html) and it works well - just `ssh i-012345abcdef` and have a normal SSH session, just proxied through SSM.

I plan to document that, but it doesn't address all use cases intended by this issue.  I'm researching how to connect between host containers without needing to worry about SSH key management.  One idea is to take advantage of the existing API socket for authentication, and add an API call that prepares communication into a host container, with apiclient having something like an "exec" mode that works like docker or kubectl exec.

**Comment by tjkirch** [comment]
> I'm researching how to connect between host containers without needing to worry about SSH key management. One idea is to take advantage of the existing API socket for authentication, and add an API call that prepares communication into a host container, with apiclient having something like an "exec" mode that works like docker or kubectl exec.

Another quick update - I've been working on a prototype of this idea, and have so far found ways to get the major points of it to work.  I have a local prototype, not integrated with the API system, that allows processes to run over a websocket on the apiclient socket.  I'm still working through some terminal-related issues, and need to make sure that there aren't any blockers with integration into the API system, but this would get us the access and debugging capabilities we want without new authentication.

**Comment by haarchri** [comment]
@tjkirch did you add Docs for ssm ssh ? Can you point me to these Docs ?

**Comment by bcressey** [comment]
@haarchri here are the docs for [apiclient exec](https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/api/apiclient/README.md#exec-mode).

The control container - where SSM sessions end up - has a wrapper script, `enter-admin-container`, that handles these underlying API operations.
