### ISSUE TITLE
RLIMIT_NOFILE does not always apply

### ISSUE THREAD

**Issue by jRilkef** [bottlerocket-os/bottlerocket#3672]
**Image I'm using:**
ami-0c41fa45c3d448987 (bottlerocket-aws-k8s-1.24-x86_64-v1.16.1-763f6d4c)

**What I expected to happen:**
System limits set via `apiclient` or user data should apply to containers launched on a given node.

**What actually happened:**
Such limits, in particular `nofile`, are not applied.
<details>

```
$ aws ssm start-session --target i-01a23b45c67d89eff
[...]
[ssm-user@control]$ apiclient get settings.oci-defaults.resource-limits
{"settings":{"oci-defaults":{"resource-limits":{"max-open-files":{"hard-limit":2097152,"soft-limit":131072}}}}}
[ssm-user@control]$ cat /proc/self/limits
Limit                     Soft Limit           Hard Limit           Units
[...]
Max open files            1024                 1024                 files
[ssm-user@control]$ ulimit -S -n
1024
[ssm-user@control]$ ulimit -H -n
1024
```

</details>

**How to reproduce the problem:**
Launch a Bottlerocket node and check ulimits.

---
I have an EKS cluster running Bottlerocket nodes. Among other things, we build container images with Podman. For some reason, ulimits set for the node are not applied to pods/containers running such builds, soft/hard limits are set to 1024, even though the default is much higher. This breaks some of Node JS builds.

Checking ulimits in control/admin containers gives 1024.
Checking during a build with `RUN ulimit <something>` also gives 1024.
If I check these values in the same build container ran locally, I get higher values.

Is this expected behavior? Am I missing some configuration option somewhere?

**Comment by webern** [comment]
I believe some of the behavior you described is expected, but where we expect/want to see the change would be:

> Checking during a build with RUN ulimit <something> also gives 1024

The setting `settings.oci-defaults.resource-limits` changes the defaults for the instance of containerd that is used to run Kuberenetes pods. After that, new pods launched by Kubernetes should get the resource limits. So if I'm not mistaken, we would not expect to see the change in `/proc/self/limits` or the host-container instances of containerd (which is isolated from the orchestrator's instance of containerd).

I'm not familiar with podman and how it might affect these settings, but can you confirm that pod in which you checked ulimit was launched after the change was made to the oci-defaults setting (and not, for instance, already running when the setting was changed)?

Can you describe how podman and kubernetes pods are interacting here? Is it possible that podman sets a nofile ulimit itself that is lower than the one being provided to the kubernetes pod?

**Comment by jRilkef** [comment]
The pod with low limits has indeed been launched after the change.

Interaction is like this. In k8s, I have a gitlab-runner pod that creates other pods when CI jobs are available. Then I have a Gitlab CI pipeline which uses an image with podman as a `service` (Gitlab's helper containers sharing the same network namespace at least). This image has a CMD which makes podman listen on a socket which then gets mounted into the builder image. It's pretty much how D-in-D works but with podman.

It is possible that podman has its own defaults, but in this case I'd expect the ulimit value to be the same when I run the container locally, and that's not the case. I tried increasing the limits in `/etc/security/limits.conf` (PAM) and `/etc/containers/containers.conf` (podman), to no effect.

**Comment by webern** [comment]
Thank you for the further clarification. I'm asking around the team to see if any of us has an intuition about what is going on here.

**Comment by webern** [comment]
I have verified that the oci-defaults are correctly being used for Kubernetes containers in aws-k8s-1.24 v1.16.1 with the series of steps shown below.

This means that it is very likely that something about how podman is working is setting the defaults to 1024 for the containers that podman is orchestrating. I am continuing to discuss with the team to see if we have insight that can be actionable for you in your setup.

```
bash-5.1# apiclient get settings.oci-defaults.resource-limits
{
  "settings": {
    "oci-defaults": {
      "resource-limits": {
        "max-open-files": {
          "hard-limit": 1048576,
          "soft-limit": 65536
        }
      }
    }
  }
}
```

```
$ kubectl run ubuntu --rm -i --tty --image ubuntu -- bash
root@ubuntu:/# ulimit -S -n
65536
root@ubuntu:/# ulimit -H -n
1048576
```


```
apiclient set --json  '{"settings":{"oci-defaults":{"resource-limits":{"max-open-files":{"hard-limit":2097152,"soft-limit":131072}}}}}'
apiclient get settings.oci-defaults.resource-limits
{
  "settings": {
    "oci-defaults": {
      "resource-limits": {
        "max-open-files": {
          "hard-limit": 2097152,
          "soft-limit": 131072
        }
      }
    }
  }
}
```

```
kubectl run ubuntu --rm -i --tty --image ubuntu -- bash
root@ubuntu:/# ulimit -S -n
131072
root@ubuntu:/# ulimit -H -n
2097152
```

**Comment by webern** [comment]
Does the container inside of which podman is running have a `/usr/share/containers/containers.conf` file? Does it say 1024?

https://github.com/containers/podman/issues/6093#issuecomment-624193781

**Comment by jRilkef** [comment]
The file is there, but the only uncommented lines are these:
```
default_sysctls = [
  "net.ipv4.ping_group_range=0 0",
]
```

**Comment by webern** [comment]
My hunch is that you need to configure Podman's NOFILE values in that configuration file. Can you try reading the documentation on configuring podman's NOFILE values and try doing so in the configuration file?  I think it looks like this, based on this comment in the linked GitHub issue. https://github.com/containers/podman/issues/6093#issuecomment-624197447

```
[containers]

# A list of ulimits to be set in containers by default, specified as
# "<ulimit name>=<soft limit>:<hard limit>", for example:
# "nofile=1024:2048"
# See setrlimit(2) for a list of resource names.
# Any limit not specified here will be inherited from the process launching the
# container engine.
# Ulimits has limits for non privileged container engines.
#
default_ulimits = [
 "nofile=65535:65535",
]
```

**Comment by webern** [comment]
@jRilkef have you been able to configure podman to get higher NOFILE limits? I'd like to close this issue as I believe Bottlerocket is working correctly and the issue is with podman configuration. Thank you.

**Comment by jRilkef** [comment]
@webern it appears Bottlerocket is indeed working correctly, however I didn't manage yet to convince podman otherwise.
