### ISSUE TITLE
Builds for `shim` package fail intermittently

### ISSUE THREAD

**Issue by jpculp** [bottlerocket-os/bottlerocket#3710]
**Platform I'm building on:**

Ubuntu (GitHub Actions) and Amazon Linux 2023

**What I expected to happen:**

`shim 0.1.0` to compile. 

**What actually happened:**

```
 error: failed to run custom build command for `shim v0.1.0 (/home/runner/work/bottlerocket/bottlerocket/packages/shim)`

Caused by:
  process didn't exit successfully: `/home/runner/work/bottlerocket/bottlerocket/variants/target/x86_64/debug/build/shim-dab70c2c0d9f68f5/build-script-build` (exit status: 1)
  ```
[full output](https://github.com/bottlerocket-os/bottlerocket/actions/runs/7481087990/job/20365758536#step:11:2710)

**How to reproduce the problem:**

The problem is intermittent (maybe 1 in every 50 builds) without an obvious pattern. It started to pop up around the time of the SDK v0.36.0 release, where the base image went from Fedora 37 to 39 and Golang went from 1.20.x to 1.21.x.

**Comment by bcressey** [comment]
We may need to quiet down the build in order to get the actual error output. I can't see the error in [this run](https://github.com/bottlerocket-os/bottlerocket/actions/runs/7732331488/job/21082037296?pr=3750).

Locally I can set these values for the docker daemon to get more output, but I'm not sure how to do that in the CI context:
```
BUILDKIT_STEP_LOG_MAX_SIZE=100000000
BUILDKIT_STEP_LOG_MAX_SPEED=100000000
```

**Comment by markusboehme** [comment]
I have not tracked down the actual issue, but in the couple times building shim failed for me, files that previously should have been created during the build were missing (e.g. I remember a file being compiled, but shortly after in the link step being reported as not existing). I didn't keep logs, unfortunately, but maybe it rings a bell for someone.
