### ISSUE TITLE
v1.19.1 💘 Tracking Issue

### ISSUE THREAD

**Issue by arnaldo2792** [bottlerocket-os/bottlerocket#3760]
This is a "_living_" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.19.1.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But **[anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee** anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.18.x` branch and `develop` (the latest changes that will eventually land in the `1.19.x` branch).

---

## v1.19.1 💘 
**Release captains 🧑‍✈️**

@arnaldo2792  @sam-berning 

**Targeting 🎯**

- [x] #3759

**Bug Fixes :lady_beetle:**

- [x] #3757 

**Maintenance 🔧**

- [x] #3762
- [x] #3765
- [x] #3763

**Comment by stockholmux** [comment]
I see a [tag for 1.19.1](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.19.1) should we close this?

**Comment by yeazelm** [comment]
Yes let's close it!
