### ISSUE TITLE
Issue with Bottlerocket image 

### ISSUE THREAD

**Issue by bhavasarpritesh** [bottlerocket-os/bottlerocket#3764]
**Image I'm using:1.19.0-2b1a7872**

**What I expected to happen:able to pull image**

**What actually happened:but getting unauthorised**

![Capture](https://github.com/bottlerocket-os/bottlerocket/assets/57290154/1bcc2dd7-e56c-4f49-93d4-047c1bf8c57b)

**How to reproduce the problem:updated eks to v1.29**

**Comment by bcressey** [comment]
Tracked in #3745.
