### ISSUE TITLE
BottleRocket in local VM - Cannot SSH into admin container

### ISSUE THREAD

**Issue by nosumm** [bottlerocket-os/bottlerocket#3821]
**Image I'm using:** Bottlerocket OS 1.19.2 (metal-dev)

**What I expected to happen:** The start-local-vm wrapper forwards the host's TCP port 2222 to the VM's port 22. After enabling the admin container with user-data.toml, I expected to connect to the container with `$ ssh -p 2222 ec2-user@localhost`

I want to use the admin container because I need remote access to the VM. 

**What actually happened:**

`kex_exchange_identification: Connection closed by remote host
Connection closed by 127.0.0.1 port 2222`

Here is the verbose output: 

[root@000000000314 noah]# ssh -vvv -p 2222 ec2-user@localhost
OpenSSH_8.7p1, OpenSSL 3.0.7 1 Nov 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug3: /etc/ssh/ssh_config line 55: Including file /etc/ssh/ssh_config.d/50-redhat.conf depth 0
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug2: checking match for 'final all' host localhost originally localhost
debug3: /etc/ssh/ssh_config.d/50-redhat.conf line 3: not matched 'final'
debug2: match not found
debug3: /etc/ssh/ssh_config.d/50-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1 (parse only)
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-]
debug3: kex names ok: [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512]
debug1: configuration requests final Match pass
debug1: re-parsing configuration
debug1: Reading configuration data /etc/ssh/ssh_config
debug3: /etc/ssh/ssh_config line 55: Including file /etc/ssh/ssh_config.d/50-redhat.conf depth 0
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug2: checking match for 'final all' host localhost originally localhost
debug3: /etc/ssh/ssh_config.d/50-redhat.conf line 3: matched 'final'
debug2: match found
debug3: /etc/ssh/ssh_config.d/50-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-]
debug3: kex names ok: [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512]
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'
debug2: resolving "localhost" port 2222
debug3: ssh_connect_direct: entering
debug1: Connecting to localhost [::1] port 2222.
debug3: set_sock_tos: set socket 3 IPV6_TCLASS 0x48
debug1: connect to address ::1 port 2222: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 2222.
debug3: set_sock_tos: set socket 3 IP_TOS 0x48
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type 0
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa_sk type -1
debug1: identity file /root/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_ed25519_sk type -1
debug1: identity file /root/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: identity file /root/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.7
kex_exchange_identification: read: Connection reset by peer
Connection reset by 127.0.0.1 port 2222

From the serial console that start-local-vm connects me to, I can see that ssh does not exist. This is where I am confused, how can I ssh into the VM if the service is not set up? Is this expected because I should be connecting to the admin container directly or is something wrong here? 

From the BottleRocket VM: 

bash-5.2# systemctl status sshd
Unit sshd.service could not be found.

**How to reproduce the problem:**

I'm following the quickstart guide for launching a BottleRocket VM using QEMU and KVM:
https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-LOCAL.md 

Enable the admin container with the user-data.toml file provided in the guide. 

Boot VM with `$ ./tools/start-local-vm --variant metal-dev --arch $(uname -m) --inject-file net.toml --inject-file user-data.toml`

Attempt to connect with `$ ssh -p 2222 ec2-user@localhost`

I have disabled firewall already.

**Comment by webern** [comment]
Taking a look. It is to be expected that you cannot find an ssh service from the console since ssh runs in the admin container.

Can you try checking that the admin container is running with `systemctl status host-containers@admin.service`?

How confident are you that you have the correct public key, base64 encoded, in your `user-data.toml` file and that you have the corresponding private key loaded in your ssh-agent?

Can you show us the `net.toml` file?

Thank you.

**Comment by nosumm** [comment]
> Taking a look. It is to be expected that you cannot find an ssh service from the console since ssh runs in the admin container.
> 
> Can you try checking that the admin container is running with `systemctl status host-containers@admin.service`?
> 
> How confident are you that you have the correct public key, base64 encoded, in your `user-data.toml` file and that you have the corresponding private key loaded in your ssh-agent?
> 
> Can you show us the `net.toml` file?
> 
> Thank you.

I'm confident the base64 encoded public key in user-data is correct and I've verified the corresponding private key is loaded in my ssh-agent. 

Here's the output from the admin container status. I see "unauthenticated pull". The issue appears to be that I cannot pull "public.ecr.aws/bottlerocket/bottlerocket-admin:v0.11.1"  due to failed authorization. Any idea how to troubleshoot this? I have my AWS credentials configured with AWS CLI. I can use AWS CLI commands no problem.

`bash-5.2# systemctl status host-containers@admin.service
● host-containers@admin.service - Host container: admin
     Loaded: loaded (/x86_64-bottlerocket-linux-gnu/sys-root/usr/lib/systemd/system/host-containers@.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-03-28 18:11:46 UTC; 13s ago
   Main PID: 1755 (host-ctr)
      Tasks: 11 (limit: 38164)
     Memory: 51.2M
        CPU: 55ms
     CGroup: /system.slice/system-host\x2dcontainers.slice/host-containers@admin.service
             └─1755 /usr/bin/host-ctr run --container-id=admin --source=public.ecr.aws/bottlerocket/bottlerocket-admin:v0.11.1 --superpowered=true --registry-config=/etc/host-containers/host-ctr.toml

Mar 28 18:11:46 10.0.2.15 systemd[1]: Started Host container: admin.
Mar 28 18:11:46 10.0.2.15 host-ctr[1755]: time="2024-03-28T18:11:46Z" level=info msg="Image does not exist, proceeding to pull image from source." ref="public.ecr.aws/bottlerocket/bottlerocket-admin:v0.11.1"
Mar 28 18:11:59 10.0.2.15 host-ctr[1755]: time="2024-03-28T18:11:59Z" level=warning msg="ecr-public: failed to get authorization token, falling back to default resolver (unauthenticated pull)"`


Here is my net.toml file: 

version = 1
[enp0s16]
dhcp4 = true

Thank you.

**Comment by arnaldo2792** [comment]
hmm, what do you see with `ctr containers list --address /run/host-containerd/containerd.sock`, are there any containers running? It is weird that `systemctl status <>` shows the unit as active.

**Comment by nosumm** [comment]
> hmm, what do you see with `ctr containers list --address /run/host-containerd/containerd.sock`, are there any containers running? It is weird that `systemctl status <>` shows the unit as active.

No, I don't see any containers running. 

bash-5.2# ctr containers list
CONTAINER    IMAGE    RUNTIME


Here's the current output from systemctl status. 

`bash-5.2# systemctl status host-containers@admin.service
● host-containers@admin.service - Host container: admin
     Loaded: loaded (/x86_64-bottlerocket-linux-gnu/sys-root/usr/lib/systemd/system/host-containers@.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-03-29 20:49:14 UTC; 2min 56s ago
   Main PID: 1751 (host-ctr)
      Tasks: 11 (limit: 38164)
     Memory: 52.5M
        CPU: 105ms
     CGroup: /system.slice/system-host\x2dcontainers.slice/host-containers@admin.service
             └─1751 /usr/bin/host-ctr run --container-id=admin --source=public.ecr.aws/bottlerocket/bottlerocket-admin:v0.11.1 --superpowered=true --registry-config=/etc/host-containers/host-ctr.toml

Mar 29 20:49:27 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:49:27Z" level=warning msg="ecr-public: failed to get authorization token, falling back to default resolver (unauthenticated pull)"
Mar 29 20:49:57 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:49:57Z" level=info msg="trying next host" error="failed to do request: Head \"https://public.ecr.aws/v2/bottlerocket/bottlerocket-admin/manifests/v0.11.1\": dial tcp 99.83.145.10:443: i/o timeout" host=public.ecr.aws
Mar 29 20:49:57 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:49:57Z" level=warning msg="failed to pull image. waiting 4.139s before retrying..." error="failed to resolve reference \"public.ecr.aws/bottlerocket/bottlerocket-admin:v0.11.1\": failed to do request: Head \"https://public.ecr.aws/v2/bottlerocket/bottlerocket-admin/manifests/v0.11.1\": dial tcp 99.83.145.10:443: i/o timeout"
Mar 29 20:50:14 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:50:14Z" level=warning msg="ecr-public: failed to get authorization token, falling back to default resolver (unauthenticated pull)"
Mar 29 20:50:44 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:50:44Z" level=info msg="trying next host" error="failed to do request: Head \"https://public.ecr.aws/v2/bottlerocket/bottlerocket-admin/manifests/v0.11.1\": dial tcp 99.83.145.10:443: i/o timeout" host=public.ecr.aws
Mar 29 20:50:44 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:50:44Z" level=warning msg="failed to pull image. waiting 6.393s before retrying..." error="failed to resolve reference \"public.ecr.aws/bottlerocket/bottlerocket-admin:v0.11.1\": failed to do request: Head \"https://public.ecr.aws/v2/bottlerocket/bottlerocket-admin/manifests/v0.11.1\": dial tcp 99.83.145.10:443: i/o timeout"
Mar 29 20:51:02 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:51:02Z" level=warning msg="ecr-public: failed to get authorization token, falling back to default resolver (unauthenticated pull)"
Mar 29 20:51:32 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:51:32Z" level=info msg="trying next host" error="failed to do request: Head \"https://public.ecr.aws/v2/bottlerocket/bottlerocket-admin/manifests/v0.11.1\": dial tcp 99.83.145.10:443: i/o timeout" host=public.ecr.aws
Mar 29 20:51:32 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:51:32Z" level=warning msg="failed to pull image. waiting 8.815s before retrying..." error="failed to resolve reference \"public.ecr.aws/bottlerocket/bottlerocket-admin:v0.11.1\": failed to do request: Head \"https://public.ecr.aws/v2/bottlerocket/bottlerocket-admin/manifests/v0.11.1\": dial tcp 99.83.145.10:443: i/o timeout"
Mar 29 20:51:54 10.0.2.15 host-ctr[1751]: time="2024-03-29T20:51:54Z" level=warning msg="ecr-public: failed to get authorization token, falling back to default resolver (unauthenticated pull)"`

**Comment by rpkelly** [comment]
ecr-public allows for [unauthenticated pulls](https://docs.aws.amazon.com/AmazonECR/latest/public/docker-pull-ecr-image.html), which is why that message is only a warning, and I believe may be a red herring.

Looking through the comments I don't think I see anything confirming if this VM has access to the internet, and if that's not enabled that could explain this behavior since we need to pull the container.

Could you please confirm that the networking for QEMU is configured to allow internet access, and that the VM is able to `ping public.ecr.aws`?

**Comment by nosumm** [comment]
> ecr-public allows for [unauthenticated pulls](https://docs.aws.amazon.com/AmazonECR/latest/public/docker-pull-ecr-image.html), which is why that message is only a warning, and I believe may be a red herring.
> 
> Looking through the comments I don't think I see anything confirming if this VM has access to the internet, and if that's not enabled that could explain this behavior since we need to pull the container.
> 
> Could you please confirm that the networking for QEMU is configured to allow internet access, and that the VM is able to `ping public.ecr.aws`?

Thank you this was really helpful. You were right I was going down the wrong path with the unauthenticated pull warning. ping didn't work, then I realized this was probably a proxy setting issue. It was. Adding the proxy info to my user-data.toml file fixed it.

[settings.network]
https-proxy = "<address:port>"
no-proxy = ["localhost", "127.0.0.1"]
