### ISSUE TITLE
v1.19.3 💘 Tracking Issue

### ISSUE THREAD

**Issue by gthao313** [bottlerocket-os/bottlerocket#3827]
This is a "_living_" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.19.3.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But **[anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee** anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.18.x` branch and `develop` (the latest changes that will eventually land in the `1.19.x` branch).

---

## v1.19.3 💘 
**Release captains 🧑‍✈️**

@tianhg  @rpkelly

**Targeting 🎯**

**Bug Fixes :lady_beetle:**

- [x] #3808 

**Maintenance 🔧**

- [x] #3816
- [x] #3823
- [x] Update third party packages
- [x] #3826
- [x] #3825
- [x] #3839

**Comment by kitsirota** [comment]
@gthao313, We are just waiting on the last review on this right? https://github.com/bottlerocket-os/bottlerocket/pull/3830

**Comment by gthao313** [comment]
@kitsirota Yeah, we are viewing the PR now. If everything is going well, we will start to release.
