### ISSUE TITLE
Can't use nvidia GPU since v1.19.1

### ISSUE THREAD

**Issue by awoimbee** [bottlerocket-os/bottlerocket#3849]
**Image I'm using:**

* Working image: `bottlerocket-aws-k8s-1.29-nvidia-x86_64-v1.19.0-2b1a7872`
* Not working images: `bottlerocket-aws-k8s-1.29-nvidia-x86_64-v1.19.1-c325a08b`, `bottlerocket-aws-k8s-1.29-nvidia-x86_64-v1.19.2-29cc92cc` 

I have tried to troubleshoot both in a pod that has a GPU attached and in `sudo sheltie` from the admin container.
`nvidia-smi` gives `nvidia-smi: command not found`, pytorch gives me `No supported gpu backend found!`.
But `nvidia-k8s-device-plugin` sees the GPU(s), DCGM-exporter too, `ls -l /proc/driver/nvidia/gpus/` too.
From a pod, I can:
```
# cat /proc/driver/nvidia/gpus/*/*
Model: 		NVIDIA A10G
IRQ:   		10
GPU UUID: 	GPU-c8e6b01b-de0a-f84f-8f00-82dcd7da266a
Video BIOS: 	94.02.75.00.01
Bus Type: 	PCIe
DMA Size: 	47 bits
DMA Mask: 	0x7fffffffffff
Bus Location: 	0000:00:1e.0
Device Minor: 	0
GPU Firmware: 	535.161.07
GPU Excluded:	No
Runtime D3 status:          Disabled by default
Video Memory:               Active

GPU Hardware Support:
 Video Memory Self Refresh: Not Supported
 Video Memory Off:          Not Supported
Binary: ""
```

**Comment by vyaghras** [comment]
@awoimbee Thanks for raising this issue. I will look in to this issue and get back to you.

**Comment by vyaghras** [comment]
@awoimbee Are you running device-plugin in daemonset? If yes, then the recommendation is to use taints or other Kubernetes mechanisms to prevent the daemonset from running on Bottlerocket nodes.

>If you already have a daemonset for the device plugin in your cluster, you may need to use taints and tolerations to keep it from running on Bottlerocket nodes.

https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-EKS.md#aws-k8s--nvidia-variants

**Comment by awoimbee** [comment]
Hi, that was the issue, thanks !
I don't know what changed in v1.19.1, but since actually following the docs fixes it I'm going to close this issue.

**Comment by vyaghras** [comment]
@awoimbee  Thanks for confirmation.
