### ISSUE TITLE
Upgrading containerd version to 1.7.x

### ISSUE THREAD

**Issue by hitsub2** [bottlerocket-os/bottlerocket#3876]
**What I'd like:**

We have adopted Bottlerocket for Spark and Flink on EKS. Currently we consider using [koordinator](https://koordinator.sh/) with [NRI](https://github.com/containerd/nri) enabled, the NRI and koodinator require containerd version >= 1.7.0. It seems that BR currently latest version is 1.6.31, however the AL ami is 1.7.11-1.amzn2.0.1.

**Any alternatives you've considered:**

Converting to AL?

**Comment by rpkelly** [comment]
Hi @hitsub2, thanks for opening this issue. Previously we'd remained on containerd 1.6.x due to it's LTS nature, but, now that 1.7.x has had it's EoL extended to match 1.6.x the concerns of moving off of an LTS release no longer apply. Because of this, we will explore moving to 1.7.x

**Comment by hitsub2** [comment]
Is there ETA for this? And is there any suggested workaround?

**Comment by vyaghras** [comment]
This isn't being actively worked on right now, but on the roadmap for the year. We will update this issue with more details once we will plan moving to 1.7.x.

**Comment by stevehipwell** [comment]
Bottlerocket having a different (older) version of Containerd than AL2 and AL2023 is problematic for consistency and breaks the narrative around why Bottlerocket is the best AWS container OS (even if this isn't a material issue, the Containerd version is reported front and center in most tools).
