### ISSUE TITLE
OOTB: package builds should not be aware of image features

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#3883]
Some packages in Bottlerocket are built differently based on what image features are found in the variant Cargo.toml. We need packages to be unaware of variant and built the same for all variants.

In concert with https://github.com/bottlerocket-os/twoliter/issues/193

These are the Bottlerocket packages affected:

```
packages/kernel-5.10/Cargo.toml
9:variant-sensitive = "platform"

packages/systemd/Cargo.toml
13:package-features = ["unified-cgroup-hierarchy"]

packages/kernel-5.15/Cargo.toml
9:variant-sensitive = "platform"

packages/os/Cargo.toml
9:variant-sensitive = true
27:package-features = [ "systemd-networkd" ]

packages/kernel-6.1/Cargo.toml
9:variant-sensitive = "platform"
```

**Comment by webern** [comment]
We might have this done.

grep spec files for image-features in packages. If we don't find any we should try building without passing image features to the package builds.

**Comment by bcressey** [comment]
Done in #4008.

**Comment by webern** [comment]
But... we should still delete the deprecated loading of the variant manifest here.
