### ISSUE TITLE
Looking for aws-dev variant AMI ID

### ISSUE THREAD

**Issue by rajivr** [bottlerocket-os/bottlerocket#3933]
**What I'd like:**

I am very new to Bottlerocket OS. I tried looking for bottlerocket-aws-dev-x86_64-v1.19.2 AMI but was unable to find it.

I was wondering where I might be able find the AMI ID for this release in us-east-2 region?

**Any alternatives you've considered:**

**Comment by ginglis13** [comment]
Hi @rajivr, thanks for the issue. The `*-dev` variants do not get published during releases. These variants are only used for development purposes.

If you're interested in getting hands on with the `aws-dev` variant, you can follow the [BUILDING.md](https://github.com/bottlerocket-os/bottlerocket/blob/develop/BUILDING.md) guide and publish your built variant to an AWS account you own by following the [PUBLISHING.md](https://github.com/bottlerocket-os/bottlerocket/blob/develop/PUBLISHING.md) guide.

I'll close this issue, but feel free to follow up with any further questions you have
