### ISSUE TITLE
Publish AMI IDs for K8s with Nvidia support via public SSM parameters, just like other AMIs

### ISSUE THREAD

**Issue by Nuru** [bottlerocket-os/bottlerocket#4046]
**What I'd like:**

Per the [Quickstart-EKS](https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-EKS.md):

> The official AMI IDs are stored in [public SSM parameters](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters.html). The parameter names look like this: `/aws/service/bottlerocket/aws-k8s-1.24/x86_64/latest/image_id`
>
> Just change the variant (`aws-k8s-1.24`) and architecture (x86_64) to the ones you want to use. Supported variants and architectures are described in the [README](https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md#variants). For the purposes of SSM parameters, the valid architecture names are `x86_64` and `arm64` (also known as aarch64). Also, if you know a specific Bottlerocket version you'd like to use, for example `1.11.0`, you can replace latest with that version.

However, there are no public SSM parameters for the `aws-k8s-*-nvidia` variants.

**Any alternatives you've considered:**

I can find the AMI with the latest creation date, but that is not necessarily the one with the latest version, apparently due to build issues. But in any case, now I have to have a special case, a whole other method for finding BottleRocket AMIs with Nvidia support.

**Comment by bcressey** [comment]
There are nvidia parameters also. For example:

```

/aws/service/bottlerocket/aws-k8s-1.24-nvidia/x86_64/latest/image_id
```

They're available for k8s 1.23 through 1.30, x86_64 and arm64.

**Comment by Nuru** [comment]
@bcressey Thank you for that information. Please convert this issue to a documentation request, because I looked hard (I think for over an hour) to find the right parameter name but could not.

**Comment by larvacea** [comment]
Absolutely! You have demonstrated that we could be clearer here. I can sympathize.

**Comment by larvacea** [comment]
@nuru, as you can see I've opened a pull request #4047 to address this. I'd welcome any feedback: would this have helped you?
