### ISSUE TITLE
Update docker-engine to v25.0.6 for 1.20.x Bottlerocket releases

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket#4106]
**What I'd like:**

Update `docker-engine` to `v25.0.6` for the 1.20.5 Bottlerocket release. https://github.com/moby/moby/releases/tag/v25.0.6

**Any alternatives you've considered:**

n/a

**Comment by ytsssun** [comment]
This is done as part of the 1.20.5 release.
