### ISSUE TITLE
Ensure we write migrations for datastore format changes

### ISSUE THREAD

**Issue by sam-aws** [bottlerocket-os/bottlerocket#415]
The changes in https://github.com/amazonlinux/PRIVATE-thar/commit/b40d9390cfd32273bab366788ebcc1b28fff6d9f inadvertently caused a datastore format change. I looked into writing a migration to manually add to an instance before upgrading from an older version but realised it won't work since there is no change in datastore version between the two images.

We should find a way of making datastore changes like this very obvious when committing them or an automated check that warns so we can be sure the datastore version changes whenever there is a format change.

**Comment by stmcginnis** [comment]
I believe @cbgbt is planning some future data store changes, but it will be awhile. Assigning to him for now to see if this can roll into that work.

**Comment by webern** [comment]
I think this is an issue that can never be done. We are going to create a new Datastore format soon, and we will definitely need to design a migration or facade system to accommodate that change. Closing.
