### ISSUE TITLE
Update Nvidia driver to 545

### ISSUE THREAD

**Issue by seunghkong** [bottlerocket-os/bottlerocket#4174]
**What I'd like:**
When can I expect newer NVIDIA driver versions for bottlerocket OS AMIs in EKS? One of our image requires nvidia driver >=545, but the latest AMI uses 535 since 1.20.1. I would appreciate a roadmap, or a general timeframe of when newer drivers are expected.

**Any alternatives you've considered:**
I did consider building a varient with custom nvidia drivers but deemed risky for prod.

**Comment by yeazelm** [comment]
Hello @seunghkong, thanks for cutting this issue! Bottlerocket currently stays on the latest [Long Term Support Branch](https://docs.nvidia.com/datacenter/tesla/drivers/index.html) until a new one is available. When NVIDIA releases a new LTS branch, we will move to it. 

What in your image requires the 545 branch of the driver? The latest production branch in 550 from NVIDIA so it would be useful to know what this would unlock for users.

**Comment by seunghkong** [comment]
Thanks for the quick response,
We're currently transitioning from using a deprecated [fastertransformers](https://github.com/NVIDIA/FasterTransformer) to [tensorrt-llm](https://github.com/NVIDIA/TensorRT-LLM) which requires [nvidia container version 24.07 or above, which supports cuda 12.5.1](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html). We would milk out fastertransformers for a bit longer, but ran into security compliance issues, as its stuck at using ubuntu22.04.

**Comment by yeazelm** [comment]
From that link on the NVIDIA container - "However, if you are running on a data center GPU (for example, T4 or any other data center GPU), you can use NVIDIA driver release 470.57 (or later R470), 525.85 (or later R525), 535.86 (or later R535), or 545.23 (or later R545)." Bottlerocket is typically running on data center GPUs so the 535 branch we include should work. Did you notice issues when trying to use the R535 drivers?

**Comment by seunghkong** [comment]
I did see that part but I prematurely assumed the mismatching cuda version would throw me an issue, as I had previously experienced issues running on nodes with mismatching/lower driver and cuda versions. 
I tested out the base nvidia 24.07 image and did not find any issue running it on eks. I appreciate the help.
