### ISSUE TITLE
Update ECS agent to v1.86.3

### ISSUE THREAD

**Issue by krystianhub** [bottlerocket-os/bottlerocket#4186]
**What I'd like:**
Update the ecs agent to the [latest version](https://github.com/aws/amazon-ecs-agent/blob/master/CHANGELOG.md) (v1.86.3) or at the very least to v1.86.x, because v1.86.0 introduced Container Restart Policy we'd like to use.

**Comment by remiflament** [comment]
Hello @bcressey @arnaldo2792 

Upgrading the agent also resolved a bug keeping the agent disconnected, without trying to re-connect.
See this PR merged:  
- https://github.com/aws/amazon-ecs-agent/pull/4233
- https://github.com/aws/amazon-ecs-agent/pull/4233
- https://github.com/aws/amazon-ecs-agent/issues/4270

I'm personally having this bug in one of my eu-west-1 cluster with the actual agent `1.82.3`

If you can put the label bug also, thank you

**Comment by remiflament** [comment]
Should we close this issue with the latest v1.24.1 ?

**Comment by ytsssun** [comment]
@remiflament Yes, v1.24.1 is released with the ECS agent version bump to v1.86.3. Closing this issue.
