### ISSUE TITLE
Missing documentation for bootstrap commands

### ISSUE THREAD

**Issue by stevehipwell** [bottlerocket-os/bottlerocket#4232]
**What I'd like:**
I'd like there to be documentation for the bootstrap command functionality added in #4131 and released as part of [1.22.0](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.22.0).

**Any alternatives you've considered:**
The docs are currently available at https://github.com/bottlerocket-os/bottlerocket-core-kit/blob/develop/sources/bootstrap-commands/README.md (thanks @dims).

**Comment by ginglis13** [comment]
We're tracking adding the docs for bootstrap commands to the website in https://github.com/bottlerocket-os/bottlerocket-project-website/issues/473. As you mention, there are some initial docs available at https://github.com/bottlerocket-os/bottlerocket-core-kit/blob/develop/sources/bootstrap-commands/README.md

**Comment by stevehipwell** [comment]
@ginglis13 the README in this repo is missing a reference to the bootstrap command settings too (that's actually where I was expecting to find them).

**Comment by piyush-jena** [comment]
@stevehipwell We have updated our documentation to include bootstrap commands - [concepts](https://bottlerocket.dev/en/os/1.22.x/concepts/bootstrap-commands/), [settings reference](https://bottlerocket.dev/en/os/1.22.x/api/settings/bootstrap-commands/). Were you expecting a link to this documentation in the README?

**Comment by stevehipwell** [comment]
@piyush-jena yes I was expecting to see a reference to the docs in the repo README by the [bootstrap-containers-settings](https://github.com/bottlerocket-os/bottlerocket?tab=readme-ov-file#bootstrap-containers-settings) section.

**Comment by piyush-jena** [comment]
Thank you for cutting this issue. We have now added a link to the documentation in the repository.
