### ISSUE TITLE
Git operations time vary across different pods running on Bottlerocket AMI Instance

### ISSUE THREAD

**Issue by divlaks** [bottlerocket-os/bottlerocket#4238]
Hi Team,

We are seeing different git operation time for various pods that are being provisioned on the same node that uses Bottlerocket AMI.
We observed that the first pod takes a longer time for git operations, whereas the subsequent pods take lesser time for the same operations.

Regards,
Dhivya

**Comment by ginglis13** [comment]
Hi @divlaks, thanks for the issue. I have a few questions

* Have you run into this same issue on a different AMI (either some general purpose OS or another container optimized OS)? That will help to narrow down if this issue you're facing is specific to Bottlerocket.

* What specifically are the git operations these pods are running?

* Can you please provide more data regarding this issue? If there are any metrics you could share, that would be great in sorting this out.

**Comment by divlaks** [comment]
Have you run into this same issue on a different AMI (either some general-purpose OS or another container optimized OS)? That will help to narrow down if this issue you're facing is specific to Bottlerocket. 
     We tried running on a general-purpose AMI, and faced the same issue

What specifically are the git operations these pods are running?
    git reset --hard is the operation that takes around 20 mins for the first build. 
    The docker image that is used has the repo pre-cloned

**Comment by ginglis13** [comment]
> We tried running on a general-purpose AMI, and faced the same issue

This may not be Bottlerocket specific then. 

> git reset --hard is the operation that takes around 20 mins for the first build.
The docker image that is used has the repo pre-cloned

Is the repo very large? `git reset --hard` will copy the entire git index, and if the repo has a lot of git history, this can be a particularly lengthy operation. If possible, you may want to evaluate using `git reset --soft` https://git-scm.com/docs/git-reset#Documentation/git-reset.txt---soft

I'm going to close this issue as it does not pertain specifically to Bottlerocket.
