### ISSUE TITLE
v1.26.1 ⚱️Tracking Issue

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket#4266]
This is a "living" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.26.1.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the 1.26.x branch and develop.

Release captains 🧑‍✈️
@KCSesh @jpculp  @gthao313  

Bug Fix 🐛 
- [x] https://github.com/bottlerocket-os/bottlerocket-core-kit/pull/215

Maintenance 🔧
- [x] Update to bottlerocket-core-kit to v3.1.1 https://github.com/bottlerocket-os/bottlerocket/pull/4264

**Comment by gthao313** [comment]
The 1.26.1 has passed validation and will be published shortly. AMIs are public and the SSM parameters should be available for this release or will be shortly. Watch for the release at https://github.com/bottlerocket-os/bottlerocket/releases to signal when the release is complete.

**Comment by patkinson01** [comment]
Hi @gthao313 , thanks for getting 1.26.1 out so quickly, much appreciated.    It's deployed to a test cluster through Brupop and looks good. 

I can see the AMIs are available, however SSM parameters haven't been updated yet (eu-west-1).  This could cause issues for users who use the latest available AMI to configured their node groups/pools with Karpenter and Terraform. 

e.g. InvalidParameterException: Requested release version 1.26.1-943d9a41 is not valid for kubernetes version 1.30.

Do you have an ETA when they will be updated? Thanks.

**Comment by jpculp** [comment]
> e.g. InvalidParameterException: Requested release version 1.26.1-943d9a41 is not valid for kubernetes version 1.30.

I wonder if this is a caching issue. If I query SSM directly in eu-west-1 I get AMI IDs for both x86_64 and aarch64.

**Comment by patkinson01** [comment]
Hi @jpculp , I've tried again this morning, in several AWS accounts and different K8s versions but still get the same value:

 aws ssm get-parameter --name /aws/service/bottlerocket/aws-k8s-1.30/x86_64/latest/image_version
{
    "Parameter": {
        "Name": "/aws/service/bottlerocket/aws-k8s-1.30/x86_64/latest/image_version",
        "Type": "String",
        "Value": "1.25.0-388e1050",
        "Version": 16,
        "LastModifiedDate": "2024-10-24T04:31:55.575000+01:00",
        "ARN": "arn:aws:ssm:eu-west-1::parameter/aws/service/bottlerocket/aws-k8s-1.30/x86_64/latest/image_version",
        "DataType": "text"
    }
}

**Comment by rpkelly** [comment]
Hi @patkinson01, if you're waiting for `latest` we decided it was prudent to make the images and version locked SSM parameters available Friday, but that it would not be a good idea to flip `latest` Friday night/early Saturday.  Watch this issue for an announcement for the completion of the release of you are waiting on `latest`

**Comment by patkinson01** [comment]
Hi @rpkelly, I'd assumed that was the case.  I was just pointing out that releasing the AMI but not updating SSM could cause issue for some people.

**Comment by gthao313** [comment]
Bottlerocket 1.26.1 has been released! 🚀

Please see https://github.com/bottlerocket-os/bottlerocket/releases/v1.26.1 for more details.

**Comment by gthao313** [comment]
@patkinson01 we just promote SSM parameter to latest. You should be good to use them now. thanks!
