### ISSUE TITLE
Standard support info collection tool

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#452]
It would be useful to have a way for users to collect a standard set of information about the running OS - runtime settings and perhaps some log contents.  There should be a simple way of sending that info to help with getting support.

Perhaps there could be a detailed form sent for support, and a simple form without any personal information that could be attached to issues.

**Comment by gregbdunn** [comment]
Not necessarily as lightweight as you might be thinking of, but we do have an AWS project that does a lot of this already. https://github.com/awslabs/aws-ec2rescue-linux

We've attempted to make it quite easy to extend via a modular system, as well.

**Comment by tjkirch** [comment]
Hi Greg, thanks for the link!  You're right that we're looking for something more lightweight, as we don't plan for Bottlerocket to have any [interpreters installed](https://github.com/bottlerocket-os/bottlerocket/blob/develop/SECURITY_FEATURES.md#no-shell-or-interpreters-installed).
