### ISSUE TITLE
Auto-reconcile settings at startup

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#473]
@bcressey's idea: instead of needing to write a migration each time we add a service or configuration file to the API model (so that downgrades don't see an unexpected thing and fail) we could have them automatically reconciled at startup.  These objects are read-only, meaning no customer data, so we could probably safely remove any we don't expect.  (We're already adding any new ones on upgrade.)

The simplest way may be to remove any services/configuration-files that don't have a default value; it'd be difficult to introspect the model itself at runtime with the current system.

**Comment by jpmcb** [comment]
Closing. Similar to #415, we are planning some settings and datastore changes in the future (no GitHub issue or design yet!) which will invalidate this ask.
