### ISSUE TITLE
updog: auto-validate lists of updates

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#480]
Instead of needing to remember to call validate, what if we reify a "list of updates" type and error immediately if adding an update with an incompatible wave?

_Originally posted by @tjkirch in https://github.com/amazonlinux/PRIVATE-thar/pull/265#discussion_r338703376_

**Comment by jpmcb** [comment]
Closing. `WaveArgs.validate` no longer exists in Updog source code.
