### ISSUE TITLE
Before upgrade/reboot, test data store migration

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#532]
If we won't be able to migrate the data store after boot, we shouldn't upgrade or reboot, because the system will be in an ugly state that's difficult to recover or debug.

There was some discussion of doing this by dry-running migrations against the data store.  If we do so, we should shut down the API first, so changes after the testing don't break upgrade.

This is sort of an enhancement of #91.

**Comment by jpmcb** [comment]
Closing. We have ongoing efforts to make testing and datastore migrations better (see https://github.com/bottlerocket-os/bottlerocket/issues/415)

If there is an ongoing desire for some dryrun feature before boot or upgrade, let's open a new issue.
