### ISSUE TITLE
Usage of simplelog requires tty

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket#576]
**Image I'm using:**

Build off of `develop`, a snapshot RC release.

**What I expected to happen:**

I expected that my Pod would be able to execute `updog check-update` without issue. The command is running in a Pod running the `dogswatch` in Agent mode, would be able to execute `updog check-update` in order to retrieve update information output.

**What actually happened:**

```log
time="2019-12-04T22:33:40Z" level=debug msg="command output" cmd="/usr/bin/updog check-update" component=updog output="Logger setup error: A terminal could not be opened\n" subcomponent=host-bin
```

**How to reproduce the problem:**

Run `updog` command, and presumably other `simplelog` based binaries, without having a TTY attached.

**Comment by gregdek** [comment]
Switched from TermLogger to SimpleLogger, closed by #1282
