### ISSUE TITLE
Automatically apply read-only settings at boot

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#640]
From discussion around #473, we had the idea of automatically applying some read-only parts of the API model, like services and configuration-files, on every boot.  They can't be (and we don't want them to be) changed in the API, so there's no need to deal with migrations - we can safely replace that part of the tree in full.

This could be done with special knowledge of those subtrees in storewolf, or by moving them to a new part of the tree.

**Comment by webern** [comment]
Closing as superseded by Settings 2.0 design work.
