### ISSUE TITLE
Create a "release" library crate

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#648]
We should have a crate that, at a minimum, contains a struct that represents `Release.toml`.

This will give us a uniform struct that we can de/serialize into and allow us to define and evolve it in a single place.  Potentially in the future this crate expands to contain additional release interfaces but we can discuss that at a later time.

**Comment by stmcginnis** [comment]
We don't believe this is needed with the way things have evolved since this was filed. If we come across a similar need going forward we will file a new issue to track that work.
