### ISSUE TITLE
Actix usage

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#661]
The [actix-web repo](https://github.com/actix/actix-web) was wiped today.  We need to watch for maintained forks, and investigate alternative frameworks that support Unix-domain socket connections.

**Comment by kzys** [comment]
Actix is back and should be fine now. That being said, Firecracker's [micro-http](https://github.com/firecracker-microvm/micro-http/) could be an interesting alternative if you want to reduce dependencies.

**Comment by tjkirch** [comment]
Thanks for the pointer!  I agree that actix seems healthy now.  We want something a bit higher-level than micro-http, and actix-web gives a nice interface that we use in the Bottlerocket apiserver, so I'm glad.
