### ISSUE TITLE
next steps for SELinux

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#764]
We landed the first cut at SELinux support in #683 but have more to do.

First up is the removal of `typepermissive` on all domains. If we don't hear reports of AVC denials we should be OK to make this change in the next major release.

Next is figuring out how to protect layers from tampering. For this we need `containerd` to add a "context=..." mount option when it assembles the snapshot, or else for `runc` to remount the filesystem to add that option before running the container.

We want to label all components that are expected to directly modify the data store - `apiserver`, `storewolf`, `migrator`, maybe others - and move to a whitelist model where only those processes can write to that filesystem.

Finally, we want to add all classes and actions to our policy, so we can set `(handleunknown deny)`. This will prevent us from automatically allowing actions supported by newer kernels. 

- [x] Remove `typepermissive` on all domains
- [x] Add `context=...` option for overlay mount
- [x] Label API components with `api_t`
- [x] Add all classes and actions for 5.4 kernel to policy
- [x] Deny unknown actions

**Comment by estesp** [comment]
You might be interested in this merged PR (would by default end up in the next release; 1.4) re: containerd and mount label support: https://github.com/containerd/containerd/pull/4051

An open PR in the CRI plugin to then use this capability and fully enable SELinux via the K8s CRI path is ongoing: https://github.com/containerd/cri/pull/1246

**Comment by bcressey** [comment]
Indeed, that's very relevant and timely. Thanks for the link!
