### ISSUE TITLE
Track EKS IMDS v2 support

### ISSUE THREAD

**Issue by iliana** [bottlerocket-os/bottlerocket#784]
kubelet and the CNI plugin image need aws-sdk-go updated to support IMDSv2-only instances.

**Comment by jhaynes** [comment]
CNI plugin work is merged here: https://github.com/aws/amazon-vpc-cni-k8s/issues/793
Kubernetes has merged updates to the aws sdk and released with 1.18: https://github.com/kubernetes/kubernetes/pull/87253

**Comment by etungsten** [comment]
Currently the `aws-1.17-k8s` and `aws-1.16-k8s` works when IMDSv2 is enforced.

`aws-1.15-k8s` does not work because v1.15 `kubelet` does not have the required `aws-go-sdk` version to support IMDSv2.

A `aws-vpc-cni-k8s` version of at least v1.6.0 is required for cluster node to work with IMDSv2.
