### ISSUE TITLE
ECS Support

### ISSUE THREAD

**Issue by jhaynes** [bottlerocket-os/bottlerocket#815]
**What I'd like:**

An ECS Variant of Bottlerocket. ECS today uses Docker as the container runtime and packages a go agent as a container along with a package to handle running the agent container correctly.

**Comment by samuelkarp** [comment]
Hey everyone!

I wanted to let you all know what our plan is for the ECS variant.  As of now, we’ll be closing this issue with the next release of Bottlerocket, which will be the first one to include AMIs for the new `aws-ecs-1` variant!   At this initial release, Bottlerocket will support all the following features:

* Logging drivers: awslogs, json-file, journald, none
* Volumes: Local and unencrypted/unauthenticated EFS
* Networking: bridge, host, and none
* IAM roles (both task roles and execution roles)
* Agent introspection and task metadata
* SELinux (Bottlerocket’s container_t, control_t, and super_t labels can be assigned in the task definition)
* Docker’s default seccomp profile
* Privileged mode (disabled by default)
* Troubleshooting log collector (logdog - similar to ecs-logs-collector)
* Custom attributes (set in user-data)
* Intel, AMD, and Graviton/Graviton2 instance types

I’ve created tracking issues for the features that are not currently supported in Bottlerocket.  Please follow those issues and vote with reactions (:+1:) to let us know which you think we should prioritize first:

* Devices
    * [GPU support](https://github.com/bottlerocket-os/bottlerocket/issues/1074)
    * [Inferentia support](https://github.com/bottlerocket-os/bottlerocket/issues/1075)
    * [Elastic Inference support](https://github.com/bottlerocket-os/bottlerocket/issues/1076)
* Networking
    * [awsvpc mode](https://github.com/bottlerocket-os/bottlerocket/issues/1077)
    * [App Mesh support](https://github.com/bottlerocket-os/bottlerocket/issues/1078)
* Logging
    * [FireLens support](https://github.com/bottlerocket-os/bottlerocket/issues/1079)
* Volumes
    * [EFS encryption and IAM authentication support](https://github.com/bottlerocket-os/bottlerocket/issues/1080)

If I’ve missed anything that you’d like to see supported, please feel free to create an issue!

Thanks!
Sam

**Comment by mwarkentin** [comment]
Cool!

**Comment by samuelkarp** [comment]
The new aws-ecs-1 variant is [now available](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.0.0)!  Check out the [getting started guide](https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-ECS.md) and [this blog post](https://aws.amazon.com/blogs/opensource/announcing-the-general-availability-of-bottlerocket-an-open-source-linux-distribution-purpose-built-to-run-containers/) for more details!

**Comment by erlend-sh** [comment]
Huge congrats on the v1.0 release! I must say it was done with great stealth. Will you be making a blog post or other such announcement to speak more about what you’ve accomplished over the past year?

**Comment by chathsuom** [comment]
Are only mentioned settings in the guide supported? Would like to have other settings as well.
for e.g.
ECS_RESERVED_PORTS
ECS_CONTAINER_STOP_TIMEOUT

**Comment by samuelkarp** [comment]
@erlend-sh Check out [this blog post](https://aws.amazon.com/blogs/opensource/announcing-the-general-availability-of-bottlerocket-an-open-source-linux-distribution-purpose-built-to-run-containers/).

@chathsuom Only the settings mentioned in the [README](https://github.com/bottlerocket-os/bottlerocket#amazon-ecs-settings) are supported today.  I've opened https://github.com/bottlerocket-os/bottlerocket/issues/1116 for the ReservedPorts setting.  For the stop timeout, are you looking to increase or decrease the default?  Please note that the stop timeout can be configured on a per-container basis through the [`stopTimeout` field of the task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_timeout).

For any other settings or features you'd like to see, please open a new issue!

**Comment by chathsuom** [comment]
@samuelkarp Thanks. Yea I think we can use task definition level stopTimeout. We used do it global level, but that's ok.
For Ports, our real requirement is to use our own custom build SSH container. I am not sure I can use Admin controller to facilitate this

**Comment by chathsuom** [comment]
Does host-containers supports private docker registries?
