### ISSUE TITLE
missing `objtool` from kernel-devel

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#819]
While troubleshooting an issue with an out-of-tree module, I found that it failed with an error like this when building in a Docker container:
> make[1]: *** No rule to make target 'kmod.o'

When building in a host container, the same invocation succeeded.

Docker command:
```
docker run -it --rm --net host \
  --mount type=bind,source=${HOME}/mod,target=/tmp/mod \
  --mount type=bind,source=${HOME}/bottlerocket/build/x86_64-bottlerocket-linux-gnu/sys-root/usr/lib/modules,target=/lib/modules \
  --mount type=bind,source=${HOME}/bottlerocket/build/x86_64-bottlerocket-linux-gnu/sys-root/usr/share/bottlerocket/squashfs-root,target=/usr/src/kernels \
  bottlerocket/sdk-x86_64:v0.9.0
```

Build command:
```
make -C /lib/modules/5.4.16/build/ M=`pwd` -d modules V=1
```

I compared the output of both builds. The failing build had references to `objtool`:
```
Trying rule prerequisite 'tools/objtool/objtool'.
Looking for a rule with intermediate file 'tools/objtool/objtool'.
Rejecting impossible rule prerequisite 'tools/objtool/objtool'.
```

Adding the following mount option to the Docker command worked around the problem:
```
docker run -it --rm --net host ... \
  --mount type=bind,source=/usr/bin/true,target=/usr/src/kernels/5.4.16/tools/objtool/objtool
  bottlerocket/sdk-x86_64:v0.9.0
```

This may mean we need to find a way to cross-compile `objtool` for our target and include it in the expected path. We might also need to put it in the SDK.

First it would be good to understand why this isn't needed on inside a host container.

**Comment by sam-aws** [comment]
After staring at Makefiles for too long this looks like it comes down to this snippet in the main Makefile:
```
ifdef CONFIG_STACK_VALIDATION
  has_libelf := $(call try-run,\
                echo "int main() {}" | $(HOSTCC) -xc -o /dev/null $(HOST_LIBELF_LIBS) -,1,0)
  ifeq ($(has_libelf),1)
    objtool_target := tools/objtool FORCE
  else
    SKIP_STACK_VALIDATION := 1
    export SKIP_STACK_VALIDATION
  endif
endif
```
The host container @bcressey and I were using does not have libelf by default, but the SDK container _does_ which means it enforces stack validation and thus depends on objtool. A quick workaround is to disable stack validation when building the module, e.g.
```
[builder@u87e72aa3c6c25c mod]$ make CONFIG_STACK_VALIDATION= -C /lib/modules/5.4.16/build/ M=`pwd` modules
make: Entering directory '/usr/src/kernels/5.4.16'
  CC [M]  /tmp/mod/KMOD_XXX.o
  AS [M]  /tmp/mod/KMOD_YYY.o
  LD [M]  /tmp/mod/KMOD_ZZZ.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /tmp/mod/KMOD_ZZZ.mod.o
  LD [M]  /tmp/mod/KMOD_ZZZ.ko
make: Leaving directory '/usr/src/kernels/5.4.16'
```

I'll post a PR that makes sure we include objtool so we can take advantage of the validation properly.

**Comment by bcressey** [comment]
We'll need to revisit the cross-compiling question when the kernel's arm64 build starts using objtool, but we can resolve now that we include it in the devel package.
