### ISSUE TITLE
Documentation: local dev/test workflow

### ISSUE THREAD

**Issue by jhaynes** [bottlerocket-os/bottlerocket#834]
**What I'd like:**

When building a bottlerocket image, I get some disk images before converting them into an AMI. I'd like to be able to test them locally (e.g. via `qemu`or VMDK images) with full connectivity.

**Comment by mdaniel** [comment]
There is already [a comment](https://github.com/bottlerocket-os/bottlerocket/blob/v0.3.1/packages/kernel/config-bottlerocket#L14) saying "for local testing with qemu," so even just adding a quick doc of how the existing developers run would be an improvement

The discussion in #842 seems relevant, also (and is what I tried first, but I had the same `dm-mapper` outcome when using VBox and I don't know enough qemu flags to know how to boot it up)
