### ISSUE TITLE
Redox

### ISSUE THREAD

**Issue by BearzRobotics** [bottlerocket-os/bottlerocket#843]
Idk if this is the proper place to ask, but have you looked into redox?

Its a completely rust based unix clone, written by Jeremy from system76. All its userland applications can be compiled and run on linux.

My hope in bringing up, is if the two projects have anything in common you can hopefully work together on those portions.

https://www.redox-os.org/

**Comment by shirshak55** [comment]
i think they already know redox . this os is designed for running containers so i don't think they have to be related?

**Comment by tjkirch** [comment]
I'm a big fan of Redox!  I've been following it for a few years and would like to run it myself for some things.

That said, it does have a different purpose than Bottlerocket.  Bottlerocket is focused on running containers, and we wanted full compatibility with containers and extensions that people are using today.  Both projects are free software, though, so hopefully we can take inspiration from Redox's great work!

**Comment by jhaynes** [comment]
Since this isn't really actionable as an issue, I'm going to resolve it. But if we find ourselves drawn to redox components in the future, we'll open issues to integrate them separately.
