### ISSUE TITLE
occasional failure to prepare local storage on boot

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#845]
**Image I'm using:**
v0.3.1

**What I expected to happen:**
All instances come up in a healthy state.

**What actually happened:**
Some instances fail to boot successfully.

```
[    5.686707]  nvme1n1: p1
[    5.711577]  nvme1n1: p1
[ FAILED ] Failed to start Prepare Local Directory (/local). See 'systemctl status prepare-local.service' for details.
[    4.588335] growpart[2042]: Failed to canonicalize link for '/dev/disk/by-partlabel/BOTTLEROCKET-DATA': No such file or directory (os error 2)
```

**How to reproduce the problem:**
Launch instances.

**Comment by bcressey** [comment]
Potential culprit [here](https://github.com/bottlerocket-os/bottlerocket/blob/dc4d498557a4b2a4d48d2998c2f0d933c9dff039/packages/release/prepare-local.service#L21) - if the symlink hasn't been recreated by udevadm before the second invocation, we'd fail with this error.

Fixing this could also address #339.

**Comment by tjkirch** [comment]
A team member has also seen "growpart[2025]: Failed to reload partition table from '/dev/nvme1n1': failed to reload partition table of device" right before the "Failed to start Prepare Local Directory" message, for the record.
