### ISSUE TITLE
[question] Comparison to RancherOS

### ISSUE THREAD

**Issue by OneCricketeer** [bottlerocket-os/bottlerocket#846]
**What I'd like:**
To know similarities & differences to [RancherOS](https://github.com/rancher/os) as a container-based OS

**Comment by jhaynes** [comment]
Thanks for your interest in Bottlerocket! As a part of cultivating an open and supportive community, we won’t compare ourselves to other projects in this space. You can learn more about our high-level goals in our [charter](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CHARTER.md) and our features and user experience in our [README](https://github.com/bottlerocket-os/bottlerocket/) or, we’d love to talk in detail about components we’ve built and why we built them the way we did.

**Comment by OneCricketeer** [comment]
👍 Okay 

😷
