### ISSUE TITLE
Please make it available in ap-south-1

### ISSUE THREAD

**Issue by rverma-jm** [bottlerocket-os/bottlerocket#847]
Please make the image available in ap-south-1,   
```aws ssm get-parameter --region ap-south-1 --name "/aws/service/bottlerocket/aws-k8s-1.15/x86_64/latest/image_id" --query Parameter.Value --output text```
output error

**Comment by leandrocostam** [comment]
> Please make the image available in ap-south-1,
> `aws ssm get-parameter --region ap-south-1 --name "/aws/service/bottlerocket/aws-k8s-1.15/x86_64/latest/image_id" --query Parameter.Value --output text`
> output error

You can build your own image if Amazon-provided image is not available in your region. Please refer:
https://github.com/bottlerocket-os/bottlerocket/blob/develop/BUILDING.md

**Comment by jhaynes** [comment]
We plan to have official support in all regions when Bottlerocket is no longer in its preview phase, but to start out we focused on getting ready in a few regions (I'm updating the docs to make that clearer): us-west-2, us-east-1, ap-northeast-1, and eu-central-1. We plan to expand this list during our preview and will take your feedback into account. Thanks!

**Comment by matthewhembree** [comment]
Rollout to AWS China in parallel to the other regions would be appreciated.

**Comment by tjkirch** [comment]
Thanks for your feedback.  We added `ap-south-1` in our v0.4.0 release.
