### ISSUE TITLE
Document requirement for EC2 Instance to have access to ECR repo

### ISSUE THREAD

**Issue by mifisignal** [bottlerocket-os/bottlerocket#851]
On Amazon EC2 Instances, Bottlerocket requires access to the ECR repositories that contain the `bottlerocket-control` and `bottlerocket-admin` container images, if users want to utilize Session Manager or SSH to gain access into the instance.

This should be more clearly documented.

**Comment by zmrow** [comment]
Good callout @otterley ! We'll add some additional words to the docs for this.

For anyone else who finds this issue, the policy needed to access ECR is: `AmazonEC2ContainerRegistryReadOnly`
