### ISSUE TITLE
cannot set labels containing slashes

### ISSUE THREAD

**Issue by snstanton** [bottlerocket-os/bottlerocket#861]
I am attempting to set up the bottlerocket-update-operator, which needs the nodes to be labelled with "bottlerocket.aws/platform-version=1.0.0".  I attempted to add this to the node-labels section of the config file, but the slash in the label name appears to confuse the startup and the nodes never joined the cluster.  When I remove the entry from `[settings.kubernetes.node-labels]`, the nodes join the cluster as expected.

ami-04e994d5dc1edce6b
userdata:
```
[settings.kubernetes]
cluster-name = "dev"
api-server = <elided>
cluster-certificate = <elided>

[settings.kubernetes.node-labels]
cluster = "system"
group = "system.1"
bottlerocket.aws/platform-version = "1.0.0"

[settings.kubernetes.node-taints]
systemnode = "system:NoSchedule"

[settings.host-containers.admin]
enabled = false

[settings.host-containers.control]
enabled = true
```

**Comment by tjkirch** [comment]
Hi @snstanton - would you please try quoting the label?  User data has to be a valid TOML file, and the label includes characters that aren't valid in keys unless quoted.  https://github.com/toml-lang/toml#keys

For example:
```
[settings.kubernetes.node-labels]
"bottlerocket.aws/platform-version" = "1.0.0"
```

**Comment by snstanton** [comment]
That did the trick.  Thanks!
