### ISSUE TITLE
Would you like to provide img or qcow2 image?

### ISSUE THREAD

**Issue by caoruidong** [bottlerocket-os/bottlerocket#878]
**What I'd like:**
A image that qemu can boot directly. I know we can build it in hand.

**Comment by etungsten** [comment]
If you'd like to download images, you can do so by downloading them directly from our TUF repository with [`tuftool`](https://github.com/awslabs/tough/tree/develop/tuftool).

1. Install `tuftool` with cargo
```
cargo install --force tuftool
```
2. Create an output directory where all the image artifacts will be downloaded to.
```
mkdir ./out
```
3. Then run the following to download x86_64 images related to the aws-k8s variant (the current default variant):
```
tuftool download --allow-root-download ./out --metadata-url https://updates.bottlerocket.aws/2020-02-02/aws-k8s-1.15/x86_64/ --target-url https://updates.bottlerocket.aws/targets/
```
All the lz4 compressed x86_64 images related to the aws-k8s variant can then be found in the output directory. 

Unfortunately with this method there is no way to specify a specific version to download. 

To make this easier, we are considering providing links to download release images in the future.

**Comment by etungsten** [comment]
Updated my answer above with more information.

**Comment by caoruidong** [comment]
Great, thanks very much

**Comment by caoruidong** [comment]
Another question. After I download these images, how can I boot them use qemu?

**Comment by tjkirch** [comment]
We're tracking the documentation for usage with qemu in #834.

**Comment by caoruidong** [comment]
OK, waiting for good news.
