### ISSUE TITLE
Contribution to bottlerocket-os.

### ISSUE THREAD

**Issue by xavinux** [bottlerocket-os/bottlerocket#889]
Hi,

I'm an AWS certified arquitect and work as a cloud engineer. Have been working as a Linux sysadmin for the past 10 years in an Internet service provider. Would like to know if I can start contributing to the bottlerocket-os as a tester.

Have expierence on virtualization and Docker containers. I have a Raspberry PI 3 f this can be useful for testing bottlerocket on an ARM processor.

Maybe a Slack channel could also be useful to talk about this interesting open source project.

Thanks for your attention.

Regards.

**Comment by jhaynes** [comment]
Hi @xavinux. We'd love to have your help (and others) in whatever way you'd like to offer it. We have a slack channel as part of the `AWS Developers` workspace which you can access [here](https://awsdevelopers.slack.com/archives/CV5GQHN2Y). We'll also get that link added to our official documentation in this repo.

**Comment by xavinux** [comment]
@jhaynes Hi, thanks for your answer but seems that I need an invite to have access to the AWS Developers Slack channel. Do you know who can send me an invitation?

**Comment by samuelkarp** [comment]
Please use [this link](https://join.slack.com/t/awsdevelopers/shared_invite/zt-4y1v34vn-IWdOLW8l95qFG3VeNs7Wrg) to join the workspace, and then you'll find us in the #bottlerocket channel.
