### ISSUE TITLE
Using ZFS as a filesystem

### ISSUE THREAD

**Issue by thedrow** [bottlerocket-os/bottlerocket#900]
**What I'd like:**

Since ZFS is very useful for data storage and databases are increasingly being containerized it'd be useful to be able to use ZFS on Linux with bottlerocket.
However, it's not as easy as installing a package and following the instructions as other distributions have done since bottlerocket.
I'd like the option to deploy an image with ZFS.

**Any alternatives you've considered:**
Not using ZFS if it's not possible.

**Comment by tjkirch** [comment]
Thanks for your suggestion!  ZFS is great technology, but we wouldn't recommend trying it with Bottlerocket until it's supported natively in the Linux kernel.  At that point, we could take a patch that enables the module along with a ZFS-capable CSI driver and other required components, but we plan to stick with ext4 by default.

**Comment by thedrow** [comment]
ZFS isn't likely to ever be included in the kernel.
I still think it's useful as an option (not as a default of course).

**Comment by thedrow** [comment]
As for ZFS-capable CSI driver, we have [this](https://github.com/openebs/zfs-localpv).

It's still in alpha but looks promising.
