### ISSUE TITLE
Migration: update system integration

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#91]
Before rebooting for an update:
* [x] Pull migration list from the TUF metadata
* [x] Select relevant migrations for this update based on incoming/outgoing versions of update
* [x] Download (to persistent storage) and verify relevant migrations from metadata-specified location *if* they are not already included in the image (with matching checksum)
* [x] Cache TUF metadata required to verify the migration from the root.json installed on the verity partition
  * [x] Add functionality to record and retrieve older root.json versions in tough
* [ ] Read the directory as a filesystem-based TUF repo when running migrations
* [ ] Use [pentacle](https://github.com/iliana/pentacle) to execute the trusted version as a sealed memfd

**Comment by iliana** [comment]
Hmm, [what I'm planning on doing in tough](https://github.com/awslabs/tough/issues/80) doesn't take into account downgrades where the older partition has an older root.json.

For example, if v0.4.2 is released with root.json version 3, and a downgrade is requested to v0.4.1 with root.json version 1, the cached repository metadata wouldn't include root.json version 2.

I think updog will need to know the version of root.json present in an image, which may be a more general "can we associate arbitrary metadata with an image version" question.

**Comment by iliana** [comment]
Spoke with @bcressey and we think we can work around the rollback issue by downloading all versions of root.json, which we can do without even making any changes to tough (although the "fetch this version of root.json" method might be worth including in tough).
