### ISSUE TITLE
Support kubernetes 1.16

### ISSUE THREAD

**Issue by snstanton** [bottlerocket-os/bottlerocket#922]
Given that 1.16 is now supported on the EKS master nodes, is there a timeline for releasing a 1.16 (kubelet) bottlerocket AMI?

**Comment by zmrow** [comment]
We don't have a concrete timeline to share, but rest assured that we're [working hard on it](https://github.com/bottlerocket-os/bottlerocket/pull/919)!

**Comment by tjkirch** [comment]
@snstanton Kubernetes 1.16 support has been merged, along with a new `aws-k8s-1.16` variant of Bottlerocket.  We don't have official AMIs yet, but we'd be interested in your feedback.

**Comment by tjkirch** [comment]
Our [v0.3.4 release](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v0.3.4) includes a new aws-k8s-1.16 variant. You can find the AMIs through the [SSM parameters](https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART.md#finding-an-ami) just like aws-k8s-1.15, or build the 1.16 image with `cargo make -e BUILDSYS_VARIANT=aws-k8s-1.16`.  (It's not the default quite yet.)
