### ISSUE TITLE
Create a ready docker image

### ISSUE THREAD

**Issue by ranrib** [bottlerocket-os/bottlerocket#940]
**What I'd like:**
I'd like to have a ready docker image, so I'll be able to pull it and explore it without needing to build it from scratch

**Comment by jhaynes** [comment]
Hi @ranrib Can you expand more on what you're asking for? 

Our host containers are built and available to pull from [ECR](https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/models/defaults.toml#L59-L69). 

Bottlerocket proper isn't built to be used inside a container, instead it is meant to be the OS where you run containers (an EC2 instance or VM). Bottlerocket releases are currently available as [AWS AMIs](https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART.md#finding-an-ami) that can be launched in EC2. If you have other use cases in mind, let us know!

**Comment by ranrib** [comment]
Oh thanks! That's helpful. Is there any AMI ready with SSH enabled? The one I tried didn't seem to have

**Comment by tjkirch** [comment]
> Oh thanks! That's helpful. Is there any AMI ready with SSH enabled? The one I tried didn't seem to have

Hi @ranrib - please see our docs on [Bottlerocket exploration](https://github.com/bottlerocket-os/bottlerocket/#exploration) - SSH isn't enabled by default for security reasons, but you can enable it, or use other methods of access.

**Comment by ranrib** [comment]
I'm sorry but I'm struggling with any path in the README. I've tried to build an image, but it yields:
```
cargo make
[cargo-make] INFO - cargo make 0.31.0
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: setup
[cargo-make] INFO - Running Task: fetch-sdk
[cargo-make] INFO - Running Task: fetch-sources
chmod: -R: No such file or directory
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

From the exploration part, I don't really understand any relevant steps to make, It's just overkill for me to set up a k8s cluster just to play and feel this.

All I'm really looking for a way to `docker run -it <bottlerocket-image> /bin/bash` into without setting a complex setup of the environment.

**Comment by mdaniel** [comment]
> From the exploration part, I don't really understand any relevant steps to make, It's just overkill for me to set up a k8s cluster just to play and feel this.

The discussion in [#842](https://github.com/bottlerocket-os/bottlerocket/issues/842#issuecomment-598563729) will interest you, as might subscribing to #834 

Be forewarned that since this entire OS is centered around essentially booting directly into `kubelet`, you may not find the `run ... /bin/bash` experience that you're looking for without some major patches applied. The [`aws-dev` variant](https://github.com/bottlerocket-os/bottlerocket/tree/v0.3.4/variants#aws-dev-development-build) might get you pretty close, or serve as a good starting point
