### ISSUE TITLE
NodePort services inaccessible/blocked by iptables

### ISSUE THREAD

**Issue by cmanzi** [bottlerocket-os/bottlerocket#982]
**Platform I'm building on:**
EKS 1.16.8, Bottlerocket v0.4.0

**What I expected to happen:**
I can access NodePort services from external clients/LoadBalancers.

**What actually happened:**
After creating a NodePort service for nginx ingress controller (with a NLB in front of the worker node ASG), none of the workers would register as healthy with the target group, and I could not access the nodeport from a different machine.

I verified that the nodes were indeed listening on the port (31443), and that I could `curl` the nginx controller from the node itself. Outside of the node, iptables was blocking any connections to port 31443. Disabling the KUBE-FIREWALL iptables rule allows connections, but TLS handshakes do not complete successfully. 

There are no security group rules that could be blocking these connections.

I also tried downgrading to v0.3.4, since I had this setup working at one point, but now it no longer does. 

**How to reproduce the problem:**

Set up the following:
- EKS 1.16.8
- worker node ASG with bottlerocket OS v0.4.0
- NLB in front of the ASG, with a target group forwarding to a nodeport for an example service
Userrdata for nodes:
```
# Cluster settings
[settings.kubernetes]
api-server = "https://xxxxxxxxx.gr7.us-east-1.eks.amazonaws.com"
cluster-certificate = "LS0tLS1CRUdJTiB..."
cluster-name = "[redacted]"
max-pods = 55
[settings.kubernetes.node-labels]
"bottlerocket.aws/updater-interface-version" = "1.0.0"
[settings.host-containers.admin]
enabled = true
[settings.host-containers.control]
enabled = true
```

**Comment by nike21oct** [comment]
hi @cmanzi , i have a EKS cluster which is using bottlerocket AMI and nginx as a ingress controller and when i implemented these IP tables rules by bootstrap-container my application stop open from outside the cluster , i mean my ingress is not functioning my nginx ingress controller pod went to crashloopbackoff , ngix controller load balancer in aws in target group the Protocol : Port is TLS: 32443 and health check is using protocol http and port is 32002, so what should i need to do?
please help me here
