### ISSUE TITLE
update-api, updog: `updog` returns exit status 0 even when the update is in a later wave and no update is performed

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket#990]
**Image I'm using:**
aws-k8s-1.15 0.4.0

**What I expected to happen:**
`updog` to return a non-zero exit code if no update is performed when asked to update via `updog update` or `updog updog-image`

**What actually happened:**
`updog` returns a exit code of 0, which can be confusing when the caller expects the update to be performed if the command is successful.

This problem manifest itself in the update API when `thar-be-updates` tries to ask `updog` to perform an update and thinks the action was successful because updog's exit code is 0, but nothing actually happened.

**How to reproduce the problem:**
Launch an instance, get a shell via admin container:

```
bash-5.0# updog update
Update available in later wave
bash-5.0# echo $?
0
bash-5.0# updog update-image
Update available in later wave
bash-5.0# echo $?           
0
```

From the Update API, state shouldn't have transitioned to `Staged` because nothing was staged. `updog` didn't prepare the update image because the update is in a later wave.
```
[ec2-user@- ~]$ apiclient -u /actions/prepare-update -m POST
[ec2-user@- ~]$ apiclient -u /updates/status
{
  "update_state": "Staged",
  "available_updates": [
    "0.4.1",
    "0.4.0",
    "0.3.4",
    "0.3.3",
    "0.3.2",
    "0.3.1",
    "0.3.0"
  ],
  "chosen_update": {
    "arch": "x86_64",
    "version": "0.4.1",
    "variant": "aws-k8s-1.15"
  },
  "active_partition": {
    "image": {
      "arch": "x86_64",
      "version": "0.3.4",
      "variant": "aws-k8s-1.15"
    },
    "next_to_boot": true
  },
  "staging_partition": {
    "image": {
      "arch": "x86_64",
      "version": "0.4.1",
      "variant": "aws-k8s-1.15"
    },
    "next_to_boot": false
  },
  "most_recent_command": {
    "cmd_type": "prepare",
    "cmd_status": "Success",
    "timestamp": "2020-07-13T19:33:49.619114940Z",
    "exit_status": 0,
    "stderr": "Update available in later wave\n"
  }
}
```

**Comment by tjkirch** [comment]
I'm not sure I agree, in all cases.  If you just run `updog update`, and there are no updates available, then you're on the latest available version and everything is healthy.  I don't see anything wrong with running that even if you haven't previously checked whether there's a new update, and I think that's a known workflow from other tools.  At a minimum, I don't think everyone would agree on whether it should return non-zero, so it could be a case for a new flag, but... meh.

I would agree if the user passed `-i VERSION` and we're not able to update to that version because of wave timing - then we're not able to do what they've asked.

**Comment by etungsten** [comment]
Had an offline discussion about this with @tjkirch. We agreed that the current exit code for `updog update` or `updog update-image` is fine. 

The problem lies with `check-update` `updog` where  would return a non-zero exit code if an update was not available which is inconsistent with `update` and `update-image`. However currently brupop depends on this exit code to determine whether to proceed with an update or not so this will have to be a separate issue.

**Comment by tjkirch** [comment]
> We agreed that the current exit code for updog update or updog update-image is fine.

To clarify, I think we'd like to change them, but we can't until we have an update strategy for `brupop` which depends on them, as mentioned above.
