### ISSUE TITLE
Build target for generating key/roles for new repo

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#999]
To use [pubsys](https://github.com/bottlerocket-os/bottlerocket/pull/964) to make a repo, you need to have key(s) and roles signed with them.  We should make a build target in `Makefile.toml` so users can use the common setup process and don't need to understand `tuftool` and related commands.

**Comment by bcressey** [comment]
We now have the `publish-setup` target, and this functionality is integrated into `repo` target.
